ITEM.name = "3601: The Forgotten Voices"
ITEM.model = Model("models/props_lab/binderbluelabel.mdl")
ITEM.description = "A blue book with the number 3601."
ITEM.price = 150

ITEM.text = [[
<font color='red' size='4'>The Forgotten Voices</font>
<font color='red' size='1'>By Abebe Ejigu</font>
I would like to share with you some details that are known to all too many people in the world, but that have until this date been left out of the narrative surrounding humanities future. But in this new world, our voices will no longer be silenced.
In my time, I have met many citizens who dislike the Universal Union, also known as the Combine. These people always talk about how bad the Combine is, how much the Combine has taken away from them, how terrible our lives are under the Combine. So I look at these people and I ask myself, who were you before?
Inevitably, they are of one type; People of the first world. People of the west. They are the people from those comfy countries where even the lower classes had many luxuries, good access to healthcare and clothing and clean water and electricity and whose homes were kept safe.
Please, do not misunderstand me. I do not mean to speak down to you, if you are one of these people, I do not mean to insult you. You are good people, I am certain, but you do not know how good you had it before. You are devoid of the context of the wider world, of how many of us struggled and bled.
I myself was born in Ethiopia. At age 12, I was kidnapped and forced to work for a Somalian warlord. My mother was killed in front of me, my village burnt at the hands of these people. I was their slave, in effect, until the day that the Union finally came and freed me.
I have a friend now who I met in City Twenty Four who came from a place he called Bosnia and Herzegovina. He lived in a city called Sarajevo- where he was trapped for three whole years, constantly being shot at by snipers day in and day out on his way to work. At night, he would lie back in his bed and listen to the artillery fire crash into the city. All the while, the rest of the world looked on and did nothing. Finally, when he was able to leave Sarajevo and return to his home town of Srebrenica, he found that all the men of his family had been exterminated by Republika Srpska soldiers.
I could continue with the stories, the stories of peoples lives before. Stories of people who had it so horrible you would not even believe me if I told you them.
You do not know the lives of the people who came before. You do not realise how good you had it. The Combine may be many things and their methods may not always be gentle, but they have given me a home, they have given me safety. They have given me food, and clothing, and healthcare, and water that is safe to drink. They have given me work, work that I can go to without worrying if someone is going to going to snipe me or my friends for being the wrong ethnicity. At night I can turn on the light in my room, and lie back watching Doctor Breen\rquote s show on the television. These are luxuries I would never have dare dreamed of before. You do not understand what it is like to watch people die of infections that could be treated by any doctor in the first world, because the clinic run by volunteers out of a rotting shack hasn\rquote t received enough donations to buy antibiotics.
I could not even write this myself. I had to dictate this to a good friend of mine, who graciously agreed to write it for me. I cannot read or write in any language, even my native tongue, because there was no school where I grew up. Think already that you have taken this for granted.
You may no longer have the privileges you once had in the old world. I understand, that makes you angry. But for billions of people, the Combine did not come here to Earth as conquerors- they came here as liberators. Liberators from the oppression you had built your comforts off. Yet under the Combine we have been urged to forgive you, to embrace our common humanity with you. And I do. You are my brothers and sisters, we are all human and we can move forward with our lives together.
Let me finish by saying; Thank you, Doctor Breen. Thank you, our Benefactors. Come my friends, it is never too late to help build a new world.
]]