ITEM.name = "The Study of Dreams"
ITEM.model = Model("models/props_lab/binderbluelabel.mdl")
ITEM.description = "A book with a with cloud imprinted on the front."
ITEM.price = 10

ITEM.text = [[
<font color='red' size='4'>Written by Andrew Killington.</font>

The study of dreams occupies a particular place in psychoanalysis. One book, by the "Father of Psychology" was a monumental contribution to psychology and was a revolutionary idea inside of the minds of nearly all intellectuals. The psychoanalytic theory of dreams may be formulated as follows. The subjective experience which appears in the unconsciousness during sleep and which, after waking, is referred to by the sleeper as a dream us is the end result of unconsciousness during this activity. By its own nature or its intensity, it attempts to interfere with sleep itself. Instead of simply waking (which would result in many hours of sleep loss). Though the sleeper may not remember the dream, or may clearly pick-out vivid details from the activity. The unconscious thoughts and wishes which threaten to wake the sleeper, we call, "Latent Dream Content." The unconscious mental operations which latent dream content form are what psychologists such as I call, "Dream Work." But what we do dream (both remembered and not) are called, "Manifest Dreams."
The word, "Dream" should strictly be kept inside of the psychoanalytic terminology views. The total phenomenon of which the latent dream content, the dream work, and manifest dream are the several parts to the definition. However, it is essential for the reader who is not fully at home in the field of, "Dream Theory" is to think of wondrous and fantastic memories, or even the slightly hysterical and arousing, "Wet Dreams" that are sometimes quite childish. The average reader without an in-depth study of this field, is most likely to not understand the rest of this passage, thus will simply scroll through these words without retaining sponge-like memory. Though I digress slightly, there are plenty of bases to be covered within this book. Having defined the three parts above from the psychological standpoint, we should proceed with the topics of what initiates the process of dreaming, and more importantly, the latent dreaming content. The first of three categories is quite obvious with this field of study. Impressions of nocturnal sensory. Such impressions are impinging on the sleeper's sense organs and at times of part of the latent content of the dreams, may change easily or harshly (depending on the dream). The example for an older generation within your sectors, may simply be the, "Alarm Clock Theory" where the sounds disrupt the organ's processes. Thirst, hunger, urination or fecal problems, pain from previous injuries or from a slightly abstract positioning of the body may also disrupt the sleeping process. Heat, temperatures and cold is another drastic problem with sleeping. When the body becomes too hot or too cold, information from the manifest may not be accessed to the brain and will awaken the sleeper if drastic enough of a problem, and may morph latent dream content. Not all people are the same, as we now know though. Some may be able to sleep through a yelling argument close-by while others may immediately wake from the opening of a door or the drop of an object. The acute hearing problems do not seem to bother any person with sleeping though when they awaken. In some studies from earlier years, the best hearing people could become the heaviest sleepers of all.
The second category of latent dream content is full of the thoughts and ideas that are trapped within the, "Black Box" of our minds. Our, "I.D.s and Super-Egos" as Freud formally called the pair. Where our mind in consciousness does not and can not access no matter how hard we struggle to explore. These thoughts or ideas are the threshold that connect under-surface feelings and views towards our minds (along with other preoccupations of the dreamer's life). Examples of this are quite limitless to any efficiently functioning human. Hopes, fears, pride, humiliation, interests and even common delights are within the second category, and sometimes may be easily translated by the common citizens, or may take many hours of thinking to understand the slight details from the manifesto. Future events and other current interests within the dreamer's life may seem clear to the sleeping person after they awaken. Many other details from these dreams have never been recorded, due to less scientific research from the Universal Union.
The third would simply be the most spectacular of the three. In my personal opinion, since it complies of several, "I.D. Impulses" which at least in their original infantile form are barred by the ego's defenses. This part of the I.D. that is used, are called, "Repressed Memories" that may psychologically and truly shake the foundations of the sleeper's life. The third category of the latent dream content may relate to previous histories that have disrupted the foundation of mental growth at youth. This includes molestation, household violence, neglect, parental problems, injuries, or other disturbing cases that are pushed away from the mind. Accordingly, this part of latent dream content is infantile and not from current scarring memories. The brain simply does not compute with the severe mental memories with the same force of repression, due to being fully developed. This does not mean that the brain, "shuts out" the newer memories, due to that would go against all forms of therapeutic psychology.
]]