ITEM.name = "Love Throughout The Ages"
ITEM.model = Model("models/props_lab/binderblue.mdl")
ITEM.description = "A book with a clock on the front, a heart at the end of the minute and hour hand."
ITEM.price = 10

ITEM.text = [[
<font color='red' size='4'>Written by Amelia Bark.</font>
Obviously, love it's self has been prevalent throughout history, most often expressed as being closely tied to it's sexual element. Love can of course be experienced in many ways other than romantic love; There's obviously Romantic love, Platonic Love and the Love one has for their family. In the Classical Periods, the Greeks (Noting that the Greeks were one of the major classical powers, along with the Romans.) had three different words for love; Storge, philia, eros and agape. Familial, platonic, romantic/sexual and divine love, respectively. The original definition of 'divine love' I won't really cover because I don't feel it's really pertinent, however it eventually evolved into being romantic love in modern day Greece while eros is sexual love.
The Romans absorbed a lot of culture from the Greeks however they didn't absorb the ideas of storge, philia, eros or agape. Rome instead had two words for love; Amare and amicitia/Diligere. Amare was the romantic and sexual love whereas Amicitia was platonic love, also being used to denote friendship (Diligere)
Eros has been very prevalent throughout the ages, most people tend to think of some of Shakespears writings (such as Romeo and Juliet) as being the apex of romantic love. It's very much a 'forbidden love' story and you see it reproduced time and time again even in modern media. While Romeo and Juliet is perhaps the best known of these types of forbidden love stories, it certainly wasn't the start of the idea. The Trojan war is also a well known story within this category depending on the version read; Athena, Aphrodite and Hera have an argument over who is the fairest after the goddess of discord gives them a golden apple marked 'for the fairest'. Zeus decides to settle the dispute by sending the three to a mortal man, Paris, who judged that Aphrodite was the fairest. As thanks, Aphrodite made Helen, who was said to be the most beautiful woman in Greece, fall in love and enlope with Paris, which angered her husband Menelaus of Sparta and sparks the war. Ultimately, these stories are, to a lesser or greater degree, about forbidden love and in some cases the trouble it causes (Romeo and Juliet has been interpreted as a caution against young love, and Troy might be interpreted as a tale about how love can cause more harm than good given that almost everyone is dead by the end of the tale.)
A common misconception about Eros is that erotic media is prevelant today where it once was not. Romantic love is, to a degree, inseperable from sexual desire and this isn't something new, this has been the case throughout all of history. Examples would be certain paintings from the Renaissance such as Venus with a Mirror or, going back even further to thousands of years before the current era, the Akkadian erotic poem 'Ishtar will not tire', possibly written by Enheduanna, high priestess of the temple (The first poet in history whose name is known). Thus it can be argued that there hasn't been much evolution in regards to love; To a degree aspects of it are much the same today as they were in the past. Throughout history, marriages have been political/financial/status and typically loveless, which is why it wasn't uncommon for people to have extramaritial relationships despite the pressure of religion. The major change since then has been that marriage has changed from being for pragmatic reasons to being for romantic reasons. While it was always idealised as being something more to do with love than pragmatic, in practice the 'duty' part of marriage was often held as being far more important than the 'love' part, whereas today these ideals have reversed; Love is held as being more important in the marriage vows than duty is. If the Love is gone, the marriage ends whereas in the past when love was gone or non-existent the marriage had to be maintained because it was the dutifiul thing to do. Exceptions exist, of course, for example the infamous Henry VIII who married six times.
Another aspect of love which has changed somewhat throughout the ages is the element of betrayal. In the medieval period betrayal was more performed on the part of a woman and served to drive her over the moral event horizon so to speak as marriage was considered permenant. Divorce was a feared word that mostly raised it's head only in gossip. Ironically, despite the fact that infidelity was held as being such a terrible thing it was not at all uncommon for those who were married to have extramaritial affairs. However, before this, infidelity was not always so easily criminialised. In the Greek myths, the gods commonly cheated on their partners and didn't seem to care whether the subjects of their desire were even willing. In these tales, it was not the gods who were punished when the infidelity or their sexual behavoir was discovered but rather the mortal lover; An example being Medusa who was the lover of Poseidon and was cursed by Athena after Poseidon and Medusa decided to have intercourse in Athena's Temple. In modern times, however, it has very much flipped around; In literature, it is more common for men to cheat on their lovers and a female adulteress is usually portrayed far more sympathetically than a male one. This has always been a very common theme throughout the ages; Betrayal is as old as love it's self after all. It is usually associated with lust and envy, for example in 'The Great Gatsby', early in the book, Gatsby is looking out across a body of water towards a blinking light located on the end of the dock where Tom and Daisy live. The light is green, which is a colour associated with envy. In Troilus and Criseyde, Troilus is struck with an insatiable desire for Criseyde by the God of Love in retalliation for him mocking the concept of love however Criseyde inevitably betrays him and takes on Diomede as a lover.
]]