ITEM.name = "Audit on the Universal Union, Volume One"
ITEM.model = Model("models/props_lab/bindergreenlabel.mdl")
ITEM.description = "A blue book with a Universal Union logo on the front."
ITEM.price = 8

ITEM.text = [[
<font color='red' size='4'>Writen by X.</font>

The Universal Union, commonly known as the Combine, is the English rendition of the name for the immense inter-universal empire spanning across multiple parallel dimensions. By its very nature this organisation may be completely undefinable by the narrow scope of thought available to the human race; By this I mean that the human mind may not even be able to comprehend the vast scale of this organisation and, contrariwise, the vast emptiness between the dimensions that this organisation controls.

This raises many questions, but the human language and mind, despite the influence of the Union, remains irrevocably human. Ergo, some of my answers will be understood, and some of them will not. Consequently, while the first question may or may not be the most pertinent, some may or may not interpret it as being the most irrelevant.

The first question is of course, what the purpose of the Union is. Some would claim that it is the conditions in which humanity finds itself under the occupation and subsequently the conclusions that can be drawn from it which will provide the most accurate answer. There are several possible interpretations for the organisation and it's affiliates drawn directly from the conditions themself.

The main view held by the majority of humanity is that the Union is an ultimately insidious organisation that desires the destruction of the human race. Within this interpretation, there are two sub-interpretations that must be differentiated between; 

First and foremost, and by far the most commonly accepted, is that the Combine is an unstoppable force that no human born organisation could possible stand up to. This interpretation views the affiliates of the Union in the Overwatch as the implacable and terrifying soldiers of an inevitable reaper; the inexorable emissaries of death itself. Indeed, this image is very much justified; It goes without saying that no one need be reminded about the invasion and the decimation of all of Earth's military forces in but a few hours, or the capabilities of the occupying Overwatch forces themselves.

The second interpretation, one that is still rather common, is that the Combine can in some way be defeated by an armed uprising of citizens. This view is rather romanticised by many in the citizen population, it does however, raise the question of just how a group of untrained civilians could possibly overthrow a organisation so powerful that it could crush all of Earths formal militaries in just several hours, and it is obvious from scale alone that the Combine did not even dedicate a large portion of their forces to seizing earth but instead a small subdivision. Indeed, the innumerable forces on the planet now are but a skeleton crew, a small fraction of the original invasion force left simply to maintain order. The conclusion that we must reach from this information is that this is a hopeless endeavour; At best it would succeed in playing as a thorn in the side of this organisation for a short while until it is completely crushed. The only driving force behind this belief is hope, which is the quintessential human delusion, simultaneously the source of humanities greatest strength and greatest weakness. 

No doubt there are various other subinterpretations in existence, but these two are by far the most common and no doubt there are other interpretations some will draw from the conditions themselves, though again this is the most commonly accepted. The problem is, however, that this method of interpreting the intentions of the Union is completely flawed by design; Humans will always favour themselves in any situation and in some ways it can be argued that the lives of some select human beings on the planet have been improved since the seven hour war, and thus these people would see the union is a more positive light. The conclusion that can be drawn from this is that, naturally, any interpretation drawn from the conditions of living will be inherently subjective.

To continue our investigation into the purpose of this organisation and its end goals, we must look towards the opposite end of the scale, to the Union's human servants. The most loyal of these beings tend to hold the belief that the Union is truly here to help and truly here to assist humanity. We can give some credence to this idea; Humanity has not been outright exterminated and it is an undeniable mathematical fact that the Universal Union could do so within a short time span, and the Universal Unions technological advancement precludes the need for a slave species of workers. However, one could be forgiven for rejecting the notion of the involuntary euthanisation of beings as being for their own good or for the good of humanity as a whole, indeed some might find it hard to understand how this could even be construed in such a way.

What might lend more credence to the possible benefits the Union might bring to humanity is the transhuman arm its self. These enigmatic beings, of whom little is publicly known, possess a level of power that no unaugmented human being could possibly hope to acquire even with decades of training. Rest assured, tranhumanism is not a new concept that only arrived with the Union, it is a branch of thought that was even present in human circles; A common feature of human transhumanist theory is the future vision of a new intelligent species, into which humanity will evolve and eventually will supplement or supersede it; The posthuman state. One can easily see how the transhuman arm can be interpreted as the continuation of Transhumanist theory; a merging, a combination if you will, of both Terrestrial and Extra-terrestrial theories regarding the accelerated evolution of species.

The conclusion that can be drawn from this is one of the most harrowing and simultaneously comforting realisations possible; Both sides of this argument are correct. The Unions ultimate goal is the extinction of the anatomically modern Homo Sapiens, as per the argument put forward by the Unions opponents, however this extinction is achieved by the replacement of the Homo Sapiens Sapiens with a new species of Human, perhaps known as Homo Sapiens Auctum or Homo Sapiens Confero. This is a revelation which manages to be utterly terrifying and yet bring some solace at the same time. On one hand, such a conclusion would prove that the Union is not an evil organisation dedicated solely to torment and destruction and to some extent might even be seen as benevolent but on the other hand this would also confirm that it inevitably strives to drive the modern human species to extinction and replace it with an evolved human species, something which most humans will find abhorrent due to innate psychological own group biases. Though this may seem to be one of the most evil things imaginable, we must remember that the natural result of the rise of a new species is the extinction of its predecessor, as was the case with humanities evolution up to this point, with the new species supplanting the old species and subsequently being eliminated when it spawned a new species of its own. The only different here is the timescale and process by which this will occur. Although hard and tragic, it is inevitably how evolution occurs. This scenario is unique in that rather than the members of the new species being entirely new individuals, members of the old species are being subsumed into the new. Further, with the eventual promised disabling of the suppression field and the rise of the new humans that will inevitably be born of this, we can conclude they humanity will survive. It will be changed and different, evolved and superior. Fear is understandable, yet through the Union, salvation for our species shall be found.
]]