ITEM.name = "Imperial Britain and Trade Dominance"
ITEM.model = Model("models/props_lab/binderredlabel.mdl")
ITEM.description = "A book with an old looking clipper transport on the front."
ITEM.price = 10

ITEM.text = [[
<font color='red' size='4'>Written by Gavin Mcleod.</font>

Britain’s dominance of world trade in the mid-nineteenth century was primarily through its naval power. Though there were other significant factors such as her Empire, early industrialisation and geographical factors, its naval power that truly allowed Britain to dominate the worlds trade.
By the start of the 19th Century, Britain was already a powerful and well established trading power. Kenneth Morgan notes that “North America and the West Indies received 57 per cent of British exports, and supplied 32 per cent of imports.”   This ensured that at the turn of the century Britain was already in a secure position. Following Napoleons defeat at Waterloo in 1815, Britain emerged as the dominant super power of the world and would remain so until the latter half of the century. This dominance resulted in a lot of influence and prestige and this helped to make British goods more common than those of her rivals, however this position would have quickly fallen apart or never even existed were it not for the power of the Royal Navy.
The shift of Britain and the more gradual shift of Europe towards free trade certainly played a part. Eric J Evans points out that “By 1850, free trade had become an unshakeable tenet of government faith, relevant alike to social conditions and economic policy.”  This shift towards Laissez-faire policies was beneficial to the UK as it allowed them to trade freely with the worlds markets. Free trade benefits the biggest powers and the result was that Britain was in a favourable position. However, this resulted in protectionist policies from other countries in Europe and furthermore there were still aspects of British society which persisted without laissez-faire, for example the Corn Laws were only repealed in 1846. This shows that Britain’s trade dominance at this time was unlikely to be a result of Laissez-faire policies.
The biggest factor in Britain’s dominance over trade was the Royal Navy. As a clear result of the position of Britain as an island nation (this geographical element cannot be ignored as it placed Britain in the luxurious position of being free of land borders and thus at will to put money into colonising other continents), the Royal Navy had evolved to be, at the time, the largest and most powerful naval force in the world. A powerful navy could protect Britain’s trade interests and her trade vessels. The international ban on privateering in the mid-nineteenth century may have helped to reduce the number of threats however without Britain’s navy, her trading ships would still have been easy targets for pirates. Furthermore, this naval power meant that she could also strong-arm trading rivals out, ensuring that Britain had some control over who was trading and where they could do it. As Kenneth Morgan notes “British oceanic enterprise provided the shipping, commerce, settlers and entrepreneurs that held these far-flung territories together.” 
It’s early industrialisation certainly played a major role in Britain’s domination of world trade in the mid-nineteenth century. Pat Hudson argues that “…manufactured items were produced more efficiently and competitively in Britain than elsewhere. She also had the commercial, financial and political power to edge out rivals...”  This allowed Britain to flood the market with cheap yet quality goods and consequently to establish a dominant position within the market. However, Britain’s early industrialisation cannot be the primary reason for her dominance during the mid-nineteenth century as were Britain unable to protect her trade routes then these goods would be lost and as such the Royal Navy was more instrumental in ensuring British trade dominance in the mid-nineteenth century.
To conclude while there were many major factors in Britain’s dominance of world trade, the biggest overarching factor that plays into almost every other factor is her Royal Navy. While Kenneth Morgan notes that “In the Indian Ocean, the English India Company dominated trade with India, south east Asia and China” it cannot be ignored that it was highly corrupt and eventually caused the Indian mutiny which, by risking the loss of one of Britain’s most important colonies, was a major threat to British trade dominance.   Further, Britain’s dominance continued for years after its dissolution and thus it was clearly not vitally important. It was the unification of Germany and the development of both her navy and industry that truly spelt the end for British trade dominance as it negated Britain’s two biggest advantages, namely her overwhelmingly powerful navy and her strong industry.
]]