Schema.voices.Add("Civil Protection", ",", ",", "npc/metropolice/vo/_comma.wav")
Schema.voices.Add("Civil Protection", "ZERO", "Zero", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("Civil Protection", "ONE", "One", "npc/metropolice/vo/one.wav")
Schema.voices.Add("Civil Protection", "TWO", "Two", "npc/metropolice/vo/two.wav")
Schema.voices.Add("Civil Protection", "THREE", "Three", "npc/metropolice/vo/three.wav")
Schema.voices.Add("Civil Protection", "FOUR", "Four", "npc/metropolice/vo/four.wav")
Schema.voices.Add("Civil Protection", "FIVE", "Five", "npc/metropolice/vo/five.wav")
Schema.voices.Add("Civil Protection", "SIX", "Six", "npc/metropolice/vo/six.wav")
Schema.voices.Add("Civil Protection", "SEVEN", "Seven", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("Civil Protection", "EIGHT", "Eight", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("Civil Protection", "NINE", "Nine", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("Civil Protection", "TEN", "Ten", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("Civil Protection", "ELEVEN", "Eleven", "npc/metropolice/vo/eleven.wav")
Schema.voices.Add("Civil Protection", "TWELVE", "Twelve", "npc/metropolice/vo/twelve.wav")
Schema.voices.Add("Civil Protection", "THIRTEEN", "Thirteen", "npc/metropolice/vo/thirteen.wav")
Schema.voices.Add("Civil Protection", "FOURTEEN", "Fourteen", "npc/metropolice/vo/fourteen.wav")
Schema.voices.Add("Civil Protection", "FIFTEEN", "Fifteen", "npc/metropolice/vo/fifteen.wav")
Schema.voices.Add("Civil Protection", "SIXTEEN", "Sixteen", "npc/metropolice/vo/sixteen.wav")
Schema.voices.Add("Civil Protection", "SEVENTEEN", "Seventeen", "npc/metropolice/vo/seventeen.wav")
Schema.voices.Add("Civil Protection", "EIGHTEEN", "Eighteen", "npc/metropolice/vo/eighteen.wav")
Schema.voices.Add("Civil Protection", "NINETEEN", "Nineteen", "npc/metropolice/vo/nineteen.wav")
Schema.voices.Add("Civil Protection", "TWENTY", "Twenty", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("Civil Protection", "THIRTY", "Thirty", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("Civil Protection", "FOURTY", "Fourty", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("Civil Protection", "FIFTY", "Fifty", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("Civil Protection", "SIXTY", "Sixty", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("Civil Protection", "SEVENTY", "Seventy", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("Civil Protection", "EIGHTY", "Eighty", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("Civil Protection", "NINETY", "Ninety", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("Civil Protection", "ONE HUNDRED", "One-hundred", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("Civil Protection", "TWO HUNDRED", "Two-hundred", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("Civil Protection", "THREE HUNDRED", "Three-hundred", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("Civil Protection", "0", "Zero", "npc/combine_soldier/vo/zero.wav")
Schema.voices.Add("Civil Protection", "1", "One", "npc/combine_soldier/vo/one.wav")
Schema.voices.Add("Civil Protection", "2", "Two", "npc/combine_soldier/vo/two.wav")
Schema.voices.Add("Civil Protection", "3", "Three", "npc/combine_soldier/vo/three.wav")
Schema.voices.Add("Civil Protection", "4", "Four", "npc/combine_soldier/vo/four.wav")
Schema.voices.Add("Civil Protection", "5", "Five", "npc/combine_soldier/vo/five.wav")
Schema.voices.Add("Civil Protection", "6", "Six", "npc/combine_soldier/vo/six.wav")
Schema.voices.Add("Civil Protection", "7", "Seven", "npc/combine_soldier/vo/seven.wav")
Schema.voices.Add("Civil Protection", "8", "Eight", "npc/combine_soldier/vo/eight.wav")
Schema.voices.Add("Civil Protection", "9", "Nine", "npc/combine_soldier/vo/niner.wav")
Schema.voices.Add("Civil Protection", "10", "Ten", "npc/combine_soldier/vo/ten.wav")
Schema.voices.Add("Civil Protection", "11", "Eleven", "npc/combine_soldier/vo/eleven.wav")
Schema.voices.Add("Civil Protection", "12", "Twelve", "npc/combine_soldier/vo/twelve.wav")
Schema.voices.Add("Civil Protection", "13", "Thirteen", "npc/combine_soldier/vo/thirteen.wav")
Schema.voices.Add("Civil Protection", "14", "Fourteen", "npc/combine_soldier/vo/fourteen.wav")
Schema.voices.Add("Civil Protection", "15", "Fifteen", "npc/combine_soldier/vo/fifteen.wav")
Schema.voices.Add("Civil Protection", "16", "Sixteen", "npc/combine_soldier/vo/sixteen.wav")
Schema.voices.Add("Civil Protection", "17", "Seventeen", "npc/combine_soldier/vo/seventeen.wav")
Schema.voices.Add("Civil Protection", "18", "Eighteen", "npc/combine_soldier/vo/eighteen.wav")
Schema.voices.Add("Civil Protection", "19", "Nineteen", "npc/combine_soldier/vo/nineteen.wav")
Schema.voices.Add("Civil Protection", "20", "Twenty", "npc/combine_soldier/vo/twenty.wav")
Schema.voices.Add("Civil Protection", "30", "Thirty", "npc/combine_soldier/vo/thirty.wav")
Schema.voices.Add("Civil Protection", "40", "Fourty", "npc/combine_soldier/vo/fourty.wav")
Schema.voices.Add("Civil Protection", "50", "Fifty", "npc/combine_soldier/vo/fifty.wav")
Schema.voices.Add("Civil Protection", "60", "Sixty", "npc/combine_soldier/vo/sixty.wav")
Schema.voices.Add("Civil Protection", "70", "Seventy", "npc/combine_soldier/vo/seventy.wav")
Schema.voices.Add("Civil Protection", "80", "Eighty", "npc/combine_soldier/vo/eighty.wav")
Schema.voices.Add("Civil Protection", "90", "Ninety", "npc/combine_soldier/vo/ninety.wav")
Schema.voices.Add("Civil Protection", "100", "One-hundred", "npc/combine_soldier/vo/onehundred.wav")
Schema.voices.Add("Civil Protection", "200", "Two-hundred", "npc/combine_soldier/vo/twohundred.wav")
Schema.voices.Add("Civil Protection", "300", "Three-hundred", "npc/combine_soldier/vo/threehundred.wav")
Schema.voices.Add("Civil Protection", "10-0 HUNTING", "10-0, 10-0; viscerator is hunting!.", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("Civil Protection", "10-103 TAG", "Possible 10-103, my location, alert TAG units!.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("Civil Protection", "10-14 DUTY", "Holding on 10-14 duty; at code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("Civil Protection", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("Civil Protection", "10-25 SUSPECT", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("Civil Protection", "10-30 RESPONDING", "I have a 10-30, my 10-20; responding, code two.", "npc/metropolice/vo/ihave10-30my10-20responding.wav")
Schema.voices.Add("Civil Protection", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("Civil Protection", "10-8 STANDING BY", "10-8; standing by.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("Civil Protection", "10-8", "Unit is on-duty; 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("Civil Protection", "10-91D COUNT", "10-91d count is.", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("Civil Protection", "10-97 GOA", "10-97; that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("Civil Protection", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("Civil Protection", "10-99", "Officer down, I am 10-99; I repeat, I am 10-99!", "npc/metropolice/vo/officerdowniam10-99.wav")
Schema.voices.Add("Civil Protection", "11-44 INBOUND", "Get that 11-44 inbound; we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("Civil Protection", "11-99", "11-99; officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("Civil Protection", "34S AT", "All units, BOL; we have 34-S at", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("Civil Protection", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("Civil Protection", "408 AT LOCATION", "I've got a 408 here at location.", "npc/metropolice/vo/ivegot408hereatlocation.wav")
Schema.voices.Add("Civil Protection", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("Civil Protection", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("Civil Protection", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("Civil Protection", "A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("Civil Protection", "ACQUIRING", "Acquiring on visual.", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("Civil Protection", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("Civil Protection", "ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("Civil Protection", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("Civil Protection", "AFFIRMATIVE2", "Affirmative.", "npc/metropolice/vo/affirmative2.wav")
Schema.voices.Add("Civil Protection", "AIRWATCH 505", "Dispatch, we need AirWatch; subject is 505.", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("Civil Protection", "AIRWATCH TAG", "I have a 10-107 here; send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("Civil Protection", "ALERT", "Alert one!", "npc/combine_soldier/vo/alert1.wav")
Schema.voices.Add("Civil Protection", "ALL UNITS MOVE IN", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("Civil Protection", "AMPUTATE", "Amputate", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("Civil Protection", "ANTI CITIZEN ONE", "Anti-Citizen One.", "npc/combine_soldier/vo/anticitizenone.wav")
Schema.voices.Add("Civil Protection", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Civil Protection", "ANTI-CITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("Civil Protection", "APEX", "APEX.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("Civil Protection", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("Civil Protection", "ARREST POSITIONS", "All units, move to arrest positions.", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("Civil Protection", "ASSAULT POINT SECURED", "Assault-point secured; advance.", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("Civil Protection", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("Civil Protection", "AT CODE", "Is at code.", "npc/combine_soldier/vo/isatcode.wav")
Schema.voices.Add("Civil Protection", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("Civil Protection", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("Civil Protection", "BACK UP", "Back up!", "vo/trainyard/ba_backup.wav")
Schema.voices.Add("Civil Protection", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("Civil Protection", "BEARING", "Bearing.", "npc/combine_soldier/vo/bearing.wav")
Schema.voices.Add("Civil Protection", "BELIEVE THAT", "You expect me to believe that?", "npc/metropolice/mc1ans_youexpectme.wav")
Schema.voices.Add("Civil Protection", "BELIEVE", "Believe what you want.", "npc/metropolice/mc1ans_believewhatyouwant.wav")
Schema.voices.Add("Civil Protection", "BELLYACHING", "Quit 'yer bellyaching!", "npc/metropolice/mc1ans_bellyaching.wav")
Schema.voices.Add("Civil Protection", "BETTER THINGS TO DO", "I've got better things to do.", "npc/metropolice/mc1que_betterthings.wav")
Schema.voices.Add("Civil Protection", "BIOTIC HERE", "We got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav")
Schema.voices.Add("Civil Protection", "BLADE", "BLADE.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("Civil Protection", "BLEEDING", "Suspect is bleeding from multiple wounds.", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("Civil Protection", "BLIP", "Catch that blip on the stabilization readout.", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("Civil Protection", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("Civil Protection", "BLOCK", "Block.", "npc/metropolice/vo/block.wav")
Schema.voices.Add("Civil Protection", "BODYPACK", "Bodypack holding!", "npc/combine_soldier/vo/bodypackholding.wav")
Schema.voices.Add("Civil Protection", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("Civil Protection", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("Civil Protection", "BOUNCER", "Bouncer, bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav")
Schema.voices.Add("Civil Protection", "BREAK COVER", "Break his cover.", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("Civil Protection", "BUGS LOOSE", "We have bugs on the loose.", "npc/metropolice/vo/bugsontheloose.wav")
Schema.voices.Add("Civil Protection", "BUGS", "Bugs.", "npc/metropolice/vo/bugs.wav")
Schema.voices.Add("Civil Protection", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("Civil Protection", "CAN2", "Pick. up. the. can.", "npc/metropolice/vo/pickupthecan2.wav")
Schema.voices.Add("Civil Protection", "CAN3", "I said pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("Civil Protection", "CAN4", "Now, put it in the trash can.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("Civil Protection", "CAN5", "I said put it in the trash can!", "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("Civil Protection", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("Civil Protection", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("Civil Protection", "CANALBLOCK", "Canal block.", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("Civil Protection", "CAREER CHOICE", "Yep, this was definitely the best career choice I ever made.", "npc/metropolice/mc1que_career.wav")
Schema.voices.Add("Civil Protection", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("Civil Protection", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("Civil Protection", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("Civil Protection", "CITIZEN SUMMONED", "Reporting citizen summoned to voluntary conscription for general public service detail; T94-322.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("Civil Protection", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("Civil Protection", "CLASSIFY DB", "Classify subject name as 'DB', this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("Civil Protection", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("Civil Protection", "CLEANUP", "Engaged in cleanup.", "npc/combine_soldier/vo/engagedincleanup.wav")
Schema.voices.Add("Civil Protection", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("Civil Protection", "CLOSE ON SUSPECT", "All units, close on suspect.", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("Civil Protection", "CLOSING", "Closing.", "npc/combine_soldier/vo/closing.wav")
Schema.voices.Add("Civil Protection", "CLOSING2", "Closing.", "npc/combine_soldier/vo/closing2.wav")
Schema.voices.Add("Civil Protection", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("Civil Protection", "CODE 2", "All units, code two.", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("Civil Protection", "CODE 3", "Officer down; request all units code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("Civil Protection", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("Civil Protection", "COME WITH ME", "You, citizen! Come with me.", "vo/trainyard/ba_youcomewith.wav")
Schema.voices.Add("Civil Protection", "CONDEMNED", "Condemned zone.", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("Civil Protection", "CONTACT 243", "Contact with 243 suspect; my 10-20 is", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("Civil Protection", "CONTACT CONFIRM", "Contact confirmed!", "npc/combine_soldier/vo/contactconfim.wav")
Schema.voices.Add("Civil Protection", "CONTACT CONFIRM2", "Contact confirmed, prosecuting!", "npc/combine_soldier/vo/contactconfirmprosecuting.wav")
Schema.voices.Add("Civil Protection", "CONTACT PRIORITY", "I have contact with a priority two.", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("Civil Protection", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("Civil Protection", "CONTAIN PROCEED", "Containment Proceeding.", "npc/combine_soldier/vo/containmentproceeding.wav")
Schema.voices.Add("Civil Protection", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("Civil Protection", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("Civil Protection", "CONTROLSECTION", "Control section.", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("Civil Protection", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
Schema.voices.Add("Civil Protection", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
Schema.voices.Add("Civil Protection", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("Civil Protection", "COPY2", "Copy.", "npc/combine_soldier/vo/copy.wav")
Schema.voices.Add("Civil Protection", "COULD BE", "Uh, could be.", "npc/metropolice/mc1ans_couldbe.wav")
Schema.voices.Add("Civil Protection", "COVER ME", "Cover me.", "npc/combine_soldier/vo/coverme.wav")
Schema.voices.Add("Civil Protection", "COVER", "Cover.", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("Civil Protection", "COVERED", "We have you covered.", "npc/metropolice/hiding05.wav")
Schema.voices.Add("Civil Protection", "CP COMPROMISED", "CP is compromised; re-establish.", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("Civil Protection", "CP ESTABLISH", "CP, we need to establish our perimeter at", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("Civil Protection", "CP OVERRUN", "CP is overrun; we have no containment.", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("Civil Protection", "DAGGER", "DAGGER.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("Civil Protection", "DASH", "DASH.", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("Civil Protection", "DB COUNT", "DB count is", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("Civil Protection", "DEFENDER", "DEFENDER.", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("Civil Protection", "DEGREES", "Degrees.", "npc/combine_soldier/vo/degrees.wav")
Schema.voices.Add("Civil Protection", "DELIVERED", "Delivered.", "npc/combine_soldier/vo/delivered")
Schema.voices.Add("Civil Protection", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("Civil Protection", "DESIGNATE SUSPECT", "Designate suspect as.", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("Civil Protection", "DESIGNATE TARGET", "Designate target as.", "npc/combine_soldier/vo/designatetargetas.wav")
Schema.voices.Add("Civil Protection", "DESTROY COVER", "Destroy that cover.", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("Civil Protection", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose.", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("Civil Protection", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("Civil Protection", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("Civil Protection", "DISPLACE", "Displace!", "npc/combine_soldier/vo/displace.wav")
Schema.voices.Add("Civil Protection", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("Civil Protection", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("Civil Protection", "DON'T BE RIDICULOUS", "Don't be ridiculous.", "npc/metropolice/mc1ans_dontberidic.wav")
Schema.voices.Add("Civil Protection", "DON'T MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("Civil Protection", "DON'T WANNA TALK", "I don't wanna talk about it.", "npc/metropolice/mc1ans_dontwannatalk.wav")
Schema.voices.Add("Civil Protection", "DONT LET HIM", "Don't let him get away!", "npc/metropolice/pointer04.wav")
Schema.voices.Add("Civil Protection", "DROP YOUR WEAPON", "Drop your weapon, get down!", "npc/metropolice/dropweapon.wav")
Schema.voices.Add("Civil Protection", "ENGAGING", "Engaging.", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("Civil Protection", "ENOUGH OUTTA YOU", "That's enough outta you!", "npc/metropolice/mc1ans_enoughouttayou.wav")
Schema.voices.Add("Civil Protection", "ESCAPE", "You have no chance of escape!", "npc/metropolice/hiding03.wav")
Schema.voices.Add("Civil Protection", "ESCAPEE", "Priority two escapee.", "npc/combine_soldier/vo/prioritytwoescapee.wav")
Schema.voices.Add("Civil Protection", "ESTABLISH NEW CP", "Fall out, establish a new CP.", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("Civil Protection", "EVERYTHING I HOPED IT WOULD BE", "This is everything I hoped it would be.", "npc/metropolice/mc1que_everythingihoped.wav")
Schema.voices.Add("Civil Protection", "EXPIRED", "Expired.", "npc/metropolice/vo/expired.wav")
Schema.voices.Add("Civil Protection", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("Civil Protection", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("Civil Protection", "EXTRACTOR AWAY", "Extractor away!", "npc/combine_soldier/vo/extractoraway.wav")
Schema.voices.Add("Civil Protection", "EXTRACTOR LIVE", "Extractor is live!", "npc/combine_soldier/vo/extractorislive.wav")
Schema.voices.Add("Civil Protection", "FASCINATING", "Fascinating.", "npc/metropolice/mc1ans_fascinating.wav")
Schema.voices.Add("Civil Protection", "FEELING GOOD", "I'm feelin' pretty good about myself today.", "npc/metropolice/mc1que_feelinggood.wav")
Schema.voices.Add("Civil Protection", "FEET", "My feet're killin' me.", "npc/metropolice/mc1que_feetkillin.wav")
Schema.voices.Add("Civil Protection", "FIELD PROMOTED", "is field promoted to LEADER-1, holding.", "npc/combine_soldier/vo/isfieldpromoted.wav")
Schema.voices.Add("Civil Protection", "FIGURES", "Figures.", "npc/metropolice/mc1ans_figures.wav")
Schema.voices.Add("Civil Protection", "FINAL BACKUP", "Is final team unit backup.", "npc/combine_soldier/vo/isfinalteamunitbackup.wav")
Schema.voices.Add("Civil Protection", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("Civil Protection", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("Civil Protection", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("Civil Protection", "FIST", "FIST.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("Civil Protection", "FIX SIGHT LINES", "Fix sight lines, move in.", "npc/combine_soldier/vo/fixsightlinesmovein.wav")
Schema.voices.Add("Civil Protection", "FLARE DOWN", "Flare down.", "npc/combine_soldier/vo/flaredown.wav")
Schema.voices.Add("Civil Protection", "FLASH FLASH FLASH", "Five, four, three, two, one, flash flash flash!", "npc/combine_soldier/vo/flashflashflash.wav")
Schema.voices.Add("Civil Protection", "FLASH", "FLASH.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("Civil Protection", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("Civil Protection", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("Civil Protection", "FREE NECROTICS", "I have free necrotics.", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("Civil Protection", "FREEZE", "Freeze!", "npc/metropolice/freeze.wav")
Schema.voices.Add("Civil Protection", "FULL ACTIVE", "Full active.", "npc/combine_soldier/vo/fullactive.wav")
Schema.voices.Add("Civil Protection", "FULL RESPONSE", "Executing full response.", "npc/combine_soldier/vo/executingfullresponse.wav")
Schema.voices.Add("Civil Protection", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("Civil Protection", "GET IN HERE", "Get in here.", "vo/trainyard/ba_inhere01.wav")
Schema.voices.Add("Civil Protection", "GET IN", "Get in!", "vo/trainyard/ba_getin.wav")
Schema.voices.Add("Civil Protection", "GET ON THE GROUND", "Stay where you are! Get on the ground, do it now!", "npc/metropolice/getonground.wav")
Schema.voices.Add("Civil Protection", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("Civil Protection", "GET OUTTA", "Get outta there.", "npc/metropolice/hiding01.wav")
Schema.voices.Add("Civil Protection", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("Civil Protection", "GETTING A RAISE", "Supposedly we're getting a raise next week.", "npc/metropolice/mc1que_raise.wav")
Schema.voices.Add("Civil Protection", "GHOST", "GHOST.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("Civil Protection", "GO ACTIVE", "Go active, intercept!", "npc/combine_soldier/vo/goactiveintercept.wav")
Schema.voices.Add("Civil Protection", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("Civil Protection", "GO ON", "Go on!", "vo/trainyard/ba_goon.wav")
Schema.voices.Add("Civil Protection", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("Civil Protection", "GO SHARP2", "Go sharp, go sharp!", "npc/combine_soldier/vo/gosharpgosharp.wav")
Schema.voices.Add("Civil Protection", "GOING IN", "Cover me, I'm goin' in!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("Civil Protection", "GOT A DB", "Uh, we got a DB here; cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("Civil Protection", "GOT HIM AGAIN", "Got him again; suspect's 10-20 at", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("Civil Protection", "GOT HIM NOW", "Affirmative we got him now.", "npc/combine_soldier/vo/affirmativewegothimnow.wav")
Schema.voices.Add("Civil Protection", "GOT HIM", "I got him!", "npc/metropolice/shooter02.wav")
Schema.voices.Add("Civil Protection", "GOT ONE ACCOMPLICE", "I got one accomplice here.", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("Civil Protection", "GOT SUSPECT ONE", "I got suspect one here.", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("Civil Protection", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Civil Protection", "GRID", "GRID.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("Civil Protection", "HAD TO GET YOU", "I had to get you for a partner.", "npc/metropolice/mc1ans_hadtopartner.wav")
Schema.voices.Add("Civil Protection", "HAMMER", "HAMMER.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("Civil Protection", "HANDS UP", "Hands up.", "npc/metropolice/deploy01.wav")
Schema.voices.Add("Civil Protection", "HANDS", "Hands.", "npc/metropolice/deploy04.wav")
Schema.voices.Add("Civil Protection", "HARDEN POSITION", "Harden that position.", "npc/combine_soldier/vo/hardenthatposition.wav")
Schema.voices.Add("Civil Protection", "HARDPOINT PROSECUTE", "Is at hardpoint; ready to prosecute.", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("Civil Protection", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("Civil Protection", "HAVE A 10-108", "We have a 10-108.", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("Civil Protection", "HEAVY RESISTANCE", "Overwatch advise, we have heavy resistance.", "npc/combine_soldier/vo/heavyresistance.wav")
Schema.voices.Add("Civil Protection", "HELIX", "HELIX.", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("Civil Protection", "HELLUVA MOOD", "You're in a helluva mood.", "npc/metropolice/mc1ans_helluvamood.wav")
Schema.voices.Add("Civil Protection", "HELP", "Help!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("Civil Protection", "HERO", "HERO.", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("Civil Protection", "HES 148", "He's gone 148.", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("Civil Protection", "HES MINE", "He's mine!", "npc/metropolice/shooter03.wav")
Schema.voices.Add("Civil Protection", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("Civil Protection", "HM", "Hmph.", "npc/metropolice/mc1ans_hm.wav")
Schema.voices.Add("Civil Protection", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("Civil Protection", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("Civil Protection", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("Civil Protection", "HOLDING AT CODE", "Is holding at code.", "npc/combine_soldier/vo/isholdingatcode.wav")
Schema.voices.Add("Civil Protection", "HOTPOINT", "Call hotpoint!", "npc/combine_soldier/vo/callhotpoint.wav")
Schema.voices.Add("Civil Protection", "HUH FIGURES", "Huh, figures.", "npc/metropolice/mc1ans_huhfigures.wav")
Schema.voices.Add("Civil Protection", "HUNTER", "HUNTER.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("Civil Protection", "HURRICANE", "HURRICANE.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("Civil Protection", "HVT", "Overwatch confirm, HVT contained.", "npc/combine_soldier/vo/overwatchconfirmhvtcontained.wav")
Schema.voices.Add("Civil Protection", "I NEED 10-78", "Dispatch, I need 10-78; officer in trouble!", "npc/metropolice/vo/dispatchineed10-78.wav")
Schema.voices.Add("Civil Protection", "I SAID MOVE ALONG", "I said move along.", "npc/metropolice/vo/isaidmovealong.wav")
Schema.voices.Add("Civil Protection", "I SAID MOVE", "I said move!", "vo/trainyard/ba_move01.wav")
Schema.voices.Add("Civil Protection", "I SEE HIM", "Yes, I see him.", "npc/metropolice/shooter05.wav")
Schema.voices.Add("Civil Protection", "ICE", "ICE.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("Civil Protection", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("Civil Protection", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("Civil Protection", "INDUSTRIAL ZONE", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav")
Schema.voices.Add("Civil Protection", "INFECTION", "Infection.", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("Civil Protection", "INFESTATION ZONE", "We are in an infestation zone.", "npc/combine_soldier/vo/weareinaninfestationzone.wav")
Schema.voices.Add("Civil Protection", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("Civil Protection", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("Civil Protection", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("Civil Protection", "INTERCEDE", "Intercede.", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("Civil Protection", "INTERLOCK", "Interlock.", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("Civil Protection", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("Civil Protection", "INVESTIGATING 10-103", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("Civil Protection", "ION", "ION.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("Civil Protection", "IS 10-108", "Is 10-108.", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("Civil Protection", "IS 10-8", "Unit is 10-8; standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("Civil Protection", "IS CLOSING", "Is closing on suspect.", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("Civil Protection", "IS DOWN", "Is down.", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("Civil Protection", "IS MOVING", "Is moving in.", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("Civil Protection", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("Civil Protection", "IS READY TO GO", "Is ready to go.", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("Civil Protection", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("Civil Protection", "JET", "JET.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("Civil Protection", "JUDGE", "JUDGE.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("Civil Protection", "JUDGEMENT", "Suspect, prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("Civil Protection", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("Civil Protection", "JURY", "JURY.", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("Civil Protection", "JUST THOUGHT OF SOMETHING", "I just thought of something. Uh, wait. maybe not.", "npc/metropolice/mc1que_justthought.wav")
Schema.voices.Add("Civil Protection", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("Civil Protection", "KIDS", "I wouldn't have kids even if they let me.", "npc/metropolice/mc1que_kids.wav")
Schema.voices.Add("Civil Protection", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("Civil Protection", "KING", "King.", "npc/metropolice/vo/king.wav")
Schema.voices.Add("Civil Protection", "LAST JOB", "Beats the shit outta my last job.", "npc/metropolice/mc1que_lastjob.wav")
Schema.voices.Add("Civil Protection", "LAST SEEN AT", "Hiding; last seen at range", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("Civil Protection", "LEADER", "LEADER.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("Civil Protection", "LET ME THINK", "Uh, let me think about that.", "npc/metropolice/mc1ans_letmethink.wav")
Schema.voices.Add("Civil Protection", "LEVEL 3", "I have a level three civil-privacy violator here.", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("Civil Protection", "LINE", "LINE.", "npc/metropolice/vo/line.wav")
Schema.voices.Add("Civil Protection", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("Civil Protection", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("Civil Protection", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("Civil Protection", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("Civil Protection", "LOOSE PARASITICS", "Loose parasitics.", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("Civil Protection", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("Civil Protection", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("Civil Protection", "LOYALTY CHECK FAILURE", "Patrol, I have a failure to comply with loyalty check, tag as possible 10-103M.", "npc/metropolice/vo/loyaltycheckfailure.wav")
Schema.voices.Add("Civil Protection", "LOYALTY CHECK", "Uh, roger that, we'll run standard loyalty check procedure 243, my 10-20 to intake station, over.", "npc/metropolice/vo/standardloyaltycheck.wav")
Schema.voices.Add("Civil Protection", "MACE", "MACE.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("Civil Protection", "MAINTAIN CP", "All units, maintain this CP.", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("Civil Protection", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("Civil Protection", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20; preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("Civil Protection", "MALIGNANT", "Malignant.", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("Civil Protection", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("Civil Protection", "METERS", "Meters.", "npc/combine_soldier/vo/meters.wav")
Schema.voices.Add("Civil Protection", "MIGHT BE", "Might be.", "npc/metropolice/mc1ans_mightbe.wav")
Schema.voices.Add("Civil Protection", "MIGHT NOT", "Might not.", "npc/metropolice/mc1ans_mightnot.wav")
Schema.voices.Add("Civil Protection", "MINOR HITS", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("Civil Protection", "MOTION CHECK", "Motion check, all radials!", "npc/combine_soldier/vo/motioncheckallradials.wav")
Schema.voices.Add("Civil Protection", "MOUTH", "Watch 'yer mouth!", "npc/metropolice/mc1ans_watchyermouth.wav")
Schema.voices.Add("Civil Protection", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
Schema.voices.Add("Civil Protection", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("Civil Protection", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("Civil Protection", "MOVE IT!", "Move it!", "npc/metropolice/vo/moveit.wav")
Schema.voices.Add("Civil Protection", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit2.wav")
Schema.voices.Add("Civil Protection", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("Civil Protection", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("Civil Protection", "MOVING TO HARDPOINT", "Moving to hardpoint.", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("Civil Protection", "NECROTICS", "Necrotics.", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("Civil Protection", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Civil Protection", "NEEDS ASSISTANCE", "Officer needs assistance; I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("Civil Protection", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("Civil Protection", "NEW STUNSTICKS", "I heard we aren't getting those new stunsticks this year.", "npc/metropolice/mc1que_stunsticks.wav")
Schema.voices.Add("Civil Protection", "NO 647", "Clear; no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("Civil Protection", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("Civil Protection", "NO IM GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("Civil Protection", "NO MOVEMENT", "Has negative movement.", "npc/combine_soldier/vo/hasnegativemovement.wav")
Schema.voices.Add("Civil Protection", "NO POINT IN HIDING", "There's no point in hiding!", "npc/metropolice/hiding02.wav")
Schema.voices.Add("Civil Protection", "NO VISCON", "No viscon.", "npc/combine_soldier/vo/noviscon.wav")
Schema.voices.Add("Civil Protection", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("Civil Protection", "NOMAD", "NOMAD.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("Civil Protection", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
Schema.voices.Add("Civil Protection", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Civil Protection", "NONTAGGED VIROMES", "Non-tagged viromes here.", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("Civil Protection", "NOPE", "Nope.", "npc/metropolice/mc1ans_nope.wav")
Schema.voices.Add("Civil Protection", "NOT SECURE", "Sector is not secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("Civil Protection", "NOVA", "NOVA.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("Civil Protection", "NOW GET OUT", "Now get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
Schema.voices.Add("Civil Protection", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("Civil Protection", "ONE DOWN", "One down.", "npc/combine_soldier/vo/onedown.wav")
Schema.voices.Add("Civil Protection", "OUTBREAK SWARM", "Swarm outbreak in sector.", "npc/combine_soldier/vo/swarmoutbreakinsector.wav")
Schema.voices.Add("Civil Protection", "OUTBREAK", "Outbreak.", "npc/metropolice/vo/outbreak.wav")
Schema.voices.Add("Civil Protection", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("Civil Protection", "PACIFYING", "Pacifying.", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("Civil Protection", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
Schema.voices.Add("Civil Protection", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
Schema.voices.Add("Civil Protection", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
Schema.voices.Add("Civil Protection", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
Schema.voices.Add("Civil Protection", "PARASITES", "We have free parasites.", "npc/combine_soldier/vo/wehavefreeparasites.wav")
Schema.voices.Add("Civil Protection", "PARASITICS", "Call contact: parasitics.", "npc/combine_soldier/vo/callcontactparasitics.wav")
Schema.voices.Add("Civil Protection", "PATROL", "PATROL.", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("Civil Protection", "PAY CUT", "What do you bet we get a pay cut?", "npc/metropolice/mc1que_paycut.wav")
Schema.voices.Add("Civil Protection", "PEOPLE SUCK", "People suck. Well, except for us I mean.", "npc/metropolice/mc1que_peoplesuck.wav")
Schema.voices.Add("Civil Protection", "PERKS", "So, you getting the perks they promised you?", "npc/metropolice/mc1que_perks.wav")
Schema.voices.Add("Civil Protection", "PHANTOM", "PHANTOM.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("Civil Protection", "PICKUP 647E", "Anyone else pick up a, uh 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("Civil Protection", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("Civil Protection", "POSITION CLEAR", "Report all positions clear.", "npc/combine_soldier/vo/reportallpositionsclear.wav")
Schema.voices.Add("Civil Protection", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("Civil Protection", "POSSIBLE 404", "Possible 404 here.", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("Civil Protection", "POSSIBLE 647E", "Possible 647-E here; request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("Civil Protection", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("Civil Protection", "POSSIBLE HOSTILES", "Overwatch, reports possible hostiles.", "npc/combine_soldier/vo/overwatchreportspossiblehostiles.wav")
Schema.voices.Add("Civil Protection", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here.", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("Civil Protection", "PREP CONTACT", "Prep for contact.", "npc/combine_soldier/vo/prepforcontact.wav")
Schema.voices.Add("Civil Protection", "PREPARE FOR 10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("Civil Protection", "PREPARING TO JUDGE", "Preparing to judge a 10-107; be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("Civil Protection", "PRESERVE", "Preserve.", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("Civil Protection", "PRESSURE", "Pressure.", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("Civil Protection", "PRIORITY 1", "Confirm; priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("Civil Protection", "PRIORITY 2", "I have a priority-two anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("Civil Protection", "PRIORITY OBJECTIVE", "Priority One objective.", "npc/combine_soldier/vo/priority1objective.wav")
Schema.voices.Add("Civil Protection", "PRIVACY", "Yeah, I'm gonna need me some privacy for this!", "vo/trainyard/ba_privacy.wav")
Schema.voices.Add("Civil Protection", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("Civil Protection", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen; final warning issued.", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("Civil Protection", "PROSECUTE", "Prosecute.", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("Civil Protection", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/prosecuting.wav")
Schema.voices.Add("Civil Protection", "PROTECTION", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("Civil Protection", "QUICK", "Quick.", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("Civil Protection", "QUICKSAND", "QUICKSAND.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("Civil Protection", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("Civil Protection", "RANGER", "RANGER.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("Civil Protection", "RATHER NOT TALK", "I'd rather not talk about that.", "npc/metropolice/mc1ans_rathernottalk.wav")
Schema.voices.Add("Civil Protection", "RATHER NOT THINK", "Uh, I'd rather not think about that.", "npc/metropolice/mc1ans_rathernotthink.wav")
Schema.voices.Add("Civil Protection", "RAZOR", "RAZOR.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("Civil Protection", "READY AMPUTATE", "Ready to amputate.", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("Civil Protection", "READY CHARGES", "Ready charges.", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("Civil Protection", "READY EXTRACTORS", "Ready extractors.", "npc/combine_soldier/vo/readyextractors")
Schema.voices.Add("Civil Protection", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("Civil Protection", "READY PROSECUTE", "Ready to prosecute.", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("Civil Protection", "READY WEAPONS", "Ready weapons.", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("Civil Protection", "READY WEAPONS2", "Ready weapons hostiles inbound.", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav")
Schema.voices.Add("Civil Protection", "REAPER", "REAPER.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("Civil Protection", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three.", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("Civil Protection", "REPORT ALL RADIALS", "Report all radials free.", "npc/combine_soldier/vo/reportallradialsfree.wav")
Schema.voices.Add("Civil Protection", "REPORT IN", "CP requests all units, uhh Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("Civil Protection", "REPORT LOCATION", "All units, report location suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("Civil Protection", "REPORT STATUS", "Local CPT, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("Civil Protection", "REPORTING CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Civil Protection", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("Civil Protection", "REQUEST MEDICAL", "Request medical!", "npc/combine_soldier/vo/requestmedical.wav")
Schema.voices.Add("Civil Protection", "REQUEST REINFORCEMENT", "Overwatch, request reinforcement.", "npc/combine_soldier/vo/overwatchrequestreinforcement.wav")
Schema.voices.Add("Civil Protection", "REQUEST RESERVE", "Overwatch, request reserve activation.", "npc/combine_soldier/vo/requestreserveactivation.wav")
Schema.voices.Add("Civil Protection", "REQUEST SKYSHIELD", "Overwatch, request SKYSHIELD.", "npc/combine_soldier/vo/overwatchrequestskyshield.wav")
Schema.voices.Add("Civil Protection", "REQUEST STIMDOSE", "Request stim-dose!", "npc/combine_soldier/vo/requeststimdose.wav")
Schema.voices.Add("Civil Protection", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("Civil Protection", "RESPOND CODE 3", "All units at location, responding code three.", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("Civil Protection", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("Civil Protection", "RESTRICT", "Restrict.", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("Civil Protection", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("Civil Protection", "RESTRICTION ZONE", "Terminal restriction-zone.", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("Civil Protection", "RIPCORD RIPCORD", "Ripcord, ripcord!", "npc/combine_soldier/vo/ripcordripcord.wav")
Schema.voices.Add("Civil Protection", "RIPCORD", "Ripcord.", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("Civil Protection", "ROGER THAT", "Roger that.", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("Civil Protection", "ROLLER", "ROLLER.", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("Civil Protection", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("Civil Protection", "SACRIFICE CODE", "All units; sacrifice code one and maintain this CP.", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("Civil Protection", "SAVAGE", "SAVAGE.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("Civil Protection", "Haha", "Haha.", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("Civil Protection", "SEARCH", "Search.", "npc/metropolice/vo/search.wav")
Schema.voices.Add("Civil Protection", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("Civil Protection", "SECOND WARNING", "This is your second warning.", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("Civil Protection", "SECTOR CONTROL", "Stabilization team has sector control.", "npc/combine_soldier/vo/stabilizationteamhassector.wav")
Schema.voices.Add("Civil Protection", "SECTOR OVERRUN", "Overwatch, sector overrun! Repeat, sector overrun!", "npc/combine_soldier/vo/overwatchsectoroverrun.wav")
Schema.voices.Add("Civil Protection", "SECTOR SECURE", "Sector is secure, no viscon.", "npc/combine_soldier/vo/sectorissecurenovison.wav")
Schema.voices.Add("Civil Protection", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("Civil Protection", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("Civil Protection", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("Civil Protection", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("Civil Protection", "SHOTS FIRED", "Shots fired; hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("Civil Protection", "SHUT UP ABOUT THAT", "Just shut up about that.", "npc/metropolice/mc1ans_shutup.wav")
Schema.voices.Add("Civil Protection", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("Civil Protection", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("Civil Protection", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("Civil Protection", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("Civil Protection", "STAY ALERT", "Stay alert, report sight line.", "npc/combine_soldier/vo/stayalertreportsightlines.wav")
Schema.voices.Add("Civil Protection", "STERILIZE", "Sterilize", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("Civil Protection", "STICK", "STICK", "npc/metropolice/vo/stick.wav")
Schema.voices.Add("Civil Protection", "STOMACH", "My stomach is killin' me.", "npc/metropolice/mc1que_stomach.wav")
Schema.voices.Add("Civil Protection", "STOP WHINING", "Stop whining.", "npc/metropolice/mc1ans_stopwhining.wav")
Schema.voices.Add("Civil Protection", "STORM RUNOFF", "All units, suspect is in storm runoff system at", "npc/metropolice/vo/suspectinstormrunoff.wav")
Schema.voices.Add("Civil Protection", "SUBJECT 505", "Subject is 505.", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("Civil Protection", "SUBJECT HIGH SPEED", "All units, be advised; subject is now high-speed.", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("Civil Protection", "SUBJECT", "Subject.", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("Civil Protection", "SUPPRESSING", "Suppressing.", "npc/combine_soldier/vo/suppressing.wav")
Schema.voices.Add("Civil Protection", "SURROUNDED", "You're surrounded.", "npc/metropolice/hiding04.wav")
Schema.voices.Add("Civil Protection", "SUSPECT 11-6", "Suspect 11-6, my 10-20 is", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("Civil Protection", "SUSPECT INCURSION", "Disp reports suspect incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("Civil Protection", "SUSPECT MOVED TO", "Suspect has moved now to", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("Civil Protection", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("Civil Protection", "SUSPEND", "Suspend.", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("Civil Protection", "SWEEPING SUSPECT", "Sweeping for suspect.", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("Civil Protection", "TAG 10-91D", "Tag 10-91d.", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("Civil Protection", "TAG BUG", "Tag one bug.", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("Civil Protection", "TAG NECROTIC", "Tag one necrotic.", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("Civil Protection", "TAG PARASITIC", "Tag one parasitic.", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("Civil Protection", "TAKE A LOOK", "Going to take a look.", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("Civil Protection", "TAKE COVER", "Take cover.", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("Civil Protection", "TAKE HIM DOWN", "Take him down!", "npc/metropolice/takedown.wav")
Schema.voices.Add("Civil Protection", "TAP", "TAP.", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("Civil Protection", "TARGET 1", "Call contact: suspect target one.", "npc/combine_soldier/vo/callcontacttarget1.wav")
Schema.voices.Add("Civil Protection", "TARGET COMPROMISED", "Target compromised, move in.", "npc/combine_soldier/vo/targetcompromisedmovein.wav")
Schema.voices.Add("Civil Protection", "TARGET CONTACT AT", "Target contact at", "npc/combine_soldier/vo/targetcontactat.wav")
Schema.voices.Add("Civil Protection", "TARGET MY RADIAL", "Target my radial!", "npc/combine_soldier/vo/targetmyradial.wav")
Schema.voices.Add("Civil Protection", "TARGET STERILIZED", "Overwatch, target one sterilized.", "npc/combine_soldier/vo/overwatchtarget1sterilized.wav")
Schema.voices.Add("Civil Protection", "TEAM ADVANCE", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("Civil Protection", "TEAM DEPLOYED", "Team is deployed and scanning.", "npc/combine_soldier/vo/teamdeployedandscanning.wav")
Schema.voices.Add("Civil Protection", "TEAM DOWN", "Overwatch, team is down, sector is not controlled.", "npc/combine_soldier/vo/overwatchteamisdown.wav")
Schema.voices.Add("Civil Protection", "THERE HE GOES", "There he goes! He's at", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("Civil Protection", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("Civil Protection", "THERES YOUR PROBLEM", "There's 'yer problem, right there.", "npc/metropolice/mc1ans_theresyerproblem.wav")
Schema.voices.Add("Civil Protection", "THINK SO", "Think so.", "npc/metropolice/mc1ans_thinkso.wav")
Schema.voices.Add("Civil Protection", "THIS IS RIDICULOUS", "This is ridiculous.", "npc/metropolice/mc1que_thisridiculous.wav")
Schema.voices.Add("Civil Protection", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("Civil Protection", "TROUBLE", "Lookin' for trouble.", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("Civil Protection", "UNDER FIRE", "Officer under fire; taking cover.", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("Civil Protection", "UNION", "UNION.", "npc/metropolice/vo/union.wav")
Schema.voices.Add("Civil Protection", "UNIT CLOSING", "Unit is closing.", "npc/combine_soldier/vo/unitisclosing.wav")
Schema.voices.Add("Civil Protection", "UNIT IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("Civil Protection", "UNIT IS 10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("Civil Protection", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("Civil Protection", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("Civil Protection", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("Civil Protection", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
Schema.voices.Add("Civil Protection", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("Civil Protection", "VACATE", "Vacate, citizen.", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("Civil Protection", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("Civil Protection", "VICE", "VICE.", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("Civil Protection", "VICTOR", "VICTOR.", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("Civil Protection", "VISCON", "Viscon!", "npc/combine_soldier/vo/viscon.wav")
Schema.voices.Add("Civil Protection", "WARNING GIVEN", "Second warning given.", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("Civil Protection", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("Civil Protection", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("Civil Protection", "WEAPON OFF", "Weapons off safe, prep for contact.", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav")
Schema.voices.Add("Civil Protection", "WEAPON READY", "In position, weapon ready.", "npc/metropolice/vo/inpositiononeready.wav")
Schema.voices.Add("Civil Protection", "WHAT THE HELL", "What the hell?", "npc/metropolice/surprise4.wav")
Schema.voices.Add("Civil Protection", "WHAT THE", "What the-?", "npc/metropolice/surprise1.wav")
Schema.voices.Add("Civil Protection", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("Civil Protection", "WRAP UP", "Thats it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("Civil Protection", "XRAY", "XRAY.", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("Civil Protection", "YEAH", "Yeah.", "npc/metropolice/mc1ans_yeah.wav")
Schema.voices.Add("Civil Protection", "YELLOW", "YELLOW.", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("Civil Protection", "YEP", "Yep.", "npc/metropolice/mc1ans_yep.wav")
Schema.voices.Add("Civil Protection", "YOU CAN GO", "Alright; you can go.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("Civil Protection", "YOUR WIFE", "Your wife doesn't like me, does she?", "npc/metropolice/mc1que_yourwife.wav")
Schema.voices.Add("Civil Protection", "ZONE", "Zone.", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("Civil Protection", "ALL UNITS CODE", "All units code.", "npc/metropolice/vo/allunitscode.wav")
Schema.voices.Add("Civil Protection", "CLOSING ON SUSPECT", "Closing on suspect.", "npc/metropolice/vo/closingonsuspect.wav")
Schema.voices.Add("Civil Protection", "CONTROL 100 LOCATION", "Control is one-hundred percent this location.", "npc/metropolice/vo/controlis100percent.wav")
Schema.voices.Add("Civil Protection", "INVESTIGATING", "Investigating.", "npc/metropolice/vo/investigating.wav")
Schema.voices.Add("Civil Protection", "NEED AIRWATCH", "Dispatch, we need AirWatch.", "npc/metropolice/vo/dispweneedairwatch.wav")
Schema.voices.Add("Civil Protection", "NEGATIVE", "Negative.", "npc/metropolice/vo/negative.wav")
Schema.voices.Add("Civil Protection", "NEGATIVE2", "Negative.", "npc/metropolice/vo/negative1.wav")
Schema.voices.Add("Civil Protection", "NO SIGN 647E", "No sign of that 647-E.", "npc/metropolice/vo/nosignofthat647e.wav")
Schema.voices.Add("Civil Protection", "PROTECTION TEAMS", "Protection teams", "npc/metropolice/vo/protectionteams.wav")
Schema.voices.Add("Civil Protection", "REPORT IN", "Report in.", "npc/metropolice/vo/reportin.wav")
Schema.voices.Add("Civil Protection", "ALL UNITS LOCATION", "All units report location.", "npc/metropolice/vo/reportlocation.wav")
Schema.voices.Add("Civil Protection", "REPORT STATUS2", "Report status.", "npc/metropolice/vo/reportstatus.wav")
Schema.voices.Add("Civil Protection", "RESPONDING CODE 2", "Responding code two.", "npc/metropolice/vo/respondingcode2.wav")
Schema.voices.Add("Civil Protection", "SUSPECT", "Suspect.", "npc/metropolice/vo/suspect.wav")
Schema.voices.Add("Civil Protection", "SPEAR", "SPEAR.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("Civil Protection", "PAYBACK", "PAYBACK.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("Civil Protection", "SWORD", "SWORD.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("Civil Protection", "STORM", "STORM.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("Civil Protection", "STRIKER", "STRIKER.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("Civil Protection", "UNIFORM", "UNIFORM.", "npc/combine_soldier/vo/uniform.wav")

-- Alyx For CP.
Schema.voices.Add("Civil Protection", "HANDS UP", "Hands up, don't move!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0001.ogg")
Schema.voices.Add("Civil Protection", "HANDS UP2", "Put your hands up!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0021.ogg")
Schema.voices.Add("Civil Protection", "HANDS UP3", "Get those hands up!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0022.ogg")
Schema.voices.Add("Civil Protection", "HANDS UP4", "Keep 'em up!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0019.ogg")
Schema.voices.Add("Civil Protection", "HANDS UP5", "Keep those hands up!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0020.ogg")
Schema.voices.Add("Civil Protection", "GET BACK", "Get back!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0002.ogg")
Schema.voices.Add("Civil Protection", "GET BACK2", "Stop, get back!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0003.ogg")
Schema.voices.Add("Civil Protection", "GET BACK3", "Get back!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00033.ogg")
Schema.voices.Add("Civil Protection", "STOP GET BACK", "Stop, get back!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0003.ogg")
Schema.voices.Add("Civil Protection", "HANDS OFF BUTTON", "Hands off the button!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0004.ogg")
Schema.voices.Add("Civil Protection", "DO NOT TOUCH", "Do not touch the button!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0005.ogg")
Schema.voices.Add("Civil Protection", "HEY WATCH IT", "Hey, watch it. I don't wanna get any of this crap on me.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0008.ogg")
Schema.voices.Add("Civil Protection", "NOT DUMPING IT", "We're not dumping it in the pit because it's safe. Keep moving.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0009.ogg")
Schema.voices.Add("Civil Protection", "SHES CLEAN", "She's clean.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_0023.ogg")
Schema.voices.Add("Civil Protection", "MOVE2", "Move!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00500.ogg")
Schema.voices.Add("Civil Protection", "GO", "Go!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00501.ogg")
Schema.voices.Add("Civil Protection", "YOU MOVE", "You, move.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00502.ogg")
Schema.voices.Add("Civil Protection", "YOU MOVE2", "You, move!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00512.ogg")
Schema.voices.Add("Civil Protection", "MOVE ALONG2", "Move along.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00503.ogg")
Schema.voices.Add("Civil Protection", "KEEP IT MOVING", "You, keep it moving.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00504.ogg")
Schema.voices.Add("Civil Protection", "OFF THE STREET", "Get off the street now.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00505.ogg")
Schema.voices.Add("Civil Protection", "RETURN HOUSING BLOCK", "Return to your housing block, now!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00506.ogg")
Schema.voices.Add("Civil Protection", "COME ON THROUGH", "Come on through.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00507.ogg")
Schema.voices.Add("Civil Protection", "COME ON THROUGH2", "Come on through.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/2900508_.ogg")
Schema.voices.Add("Civil Protection", "COME ON THROUGH3", "You're clear. Come on through.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00509.ogg")
Schema.voices.Add("Civil Protection", "GET IN2", "Get in!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00510.ogg")
Schema.voices.Add("Civil Protection", "IN THE VAN", "Get in the van!", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00511.ogg")
Schema.voices.Add("Civil Protection", "WE GOT EM", "We got 'em.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00513.ogg")
Schema.voices.Add("Civil Protection", "PROBABLE ANTICITIZEN", "Probable anti-citizen, get a scan.", "interlock/player/combine/voicelines/Grunt/Choreo/Grunt1/29_00524.ogg")

Schema.voices.AddClass("Civil Protection", function(ply)
    return ( ply:Team() == FACTION_CP )
end)
