Schema.voices.Add("Charger", "MOVE IN", "Move in.", "interlock/player/combine/voicelines/Charger/advancing_on_target_01.ogg")
Schema.voices.Add("Charger", "MOVING1", "Moving now.", "interlock/player/combine/voicelines/Charger/advancing_on_target_02.ogg")
Schema.voices.Add("Charger", "MOVING2", "Pressing.", "interlock/player/combine/voicelines/Charger/advancing_on_target_03.ogg")
Schema.voices.Add("Charger", "APPROACHING1", "Approaching target.", "interlock/player/combine/voicelines/Charger/advancing_on_target_04.ogg")
Schema.voices.Add("Charger", "PRESSURE", "Pressure.", "interlock/player/combine/voicelines/Charger/advancing_on_target_05.ogg")
Schema.voices.Add("Charger", "MOVING3", "Proceeding on infected.", "interlock/player/combine/voicelines/Charger/advancing_on_target_06.ogg")
Schema.voices.Add("Charger", "MOVING4", "Forward steady.", "interlock/player/combine/voicelines/Charger/advancing_on_target_07.ogg")
Schema.voices.Add("Charger", "PUSHING1", "Pushing forward.", "interlock/player/combine/voicelines/Charger/advancing_on_target_08.ogg")
Schema.voices.Add("Charger", "MOVING5", "Wallhammer, moving.", "interlock/player/combine/voicelines/Charger/advancing_on_target_09.ogg")
Schema.voices.Add("Charger", "COPY MOVING", "Copy, moving on contaminant.", "interlock/player/combine/voicelines/Charger/advancing_on_target_10.ogg")
Schema.voices.Add("Charger", "PRESSURE2", "Pressure, pressure!", "interlock/player/combine/voicelines/Charger/advancing_on_target_11.ogg")
Schema.voices.Add("Charger", "PRESSURE3", "Stabalization teams, forward pressure.", "interlock/player/combine/voicelines/Charger/advancing_on_target_12.ogg")
Schema.voices.Add("Charger", "MOVING6", "Commencing on infected.", "interlock/player/combine/voicelines/Charger/advancing_on_target_13.ogg")
Schema.voices.Add("Charger", "PUSHING2", "Pushing.", "interlock/player/combine/voicelines/Charger/advancing_on_target_14.ogg")
Schema.voices.Add("Charger", "MOVING7", "Wallhammer is moving on infected.", "interlock/player/combine/voicelines/Charger/advancing_on_target_15.ogg")
Schema.voices.Add("Charger", "PUSHING3", "Wallhammer is pushing sector.", "interlock/player/combine/voicelines/Charger/advancing_on_target_16.ogg")
Schema.voices.Add("Charger", "APPROACHING2", "Approaching contaminant.", "interlock/player/combine/voicelines/Charger/advancing_on_target_17.ogg")
Schema.voices.Add("Charger", "ADVANCING1", "Wallhammer, advancing on target.", "interlock/player/combine/voicelines/Charger/advancing_on_target_18.ogg")
Schema.voices.Add("Charger", "ADVANCING2", "Wallhammer, advancing.", "interlock/player/combine/voicelines/Charger/advancing_on_target_19.ogg")
Schema.voices.Add("Charger", "PUSHING4", "Wallhammer, pushing.", "interlock/player/combine/voicelines/Charger/advancing_on_target_20.ogg")


Schema.voices.Add("Charger", "ATTACKING1", "Going sharp.", "interlock/player/combine/voicelines/Charger/announceattack_01.ogg")
Schema.voices.Add("Charger", "ATTACKING2", "Engaging.", "interlock/player/combine/voicelines/Charger/announceattack_02.ogg")
Schema.voices.Add("Charger", "ATTACKING3", "Target engaged.", "interlock/player/combine/voicelines/Charger/announceattack_03.ogg")
Schema.voices.Add("Charger", "PROSECUTING", "Prosecuting.", "interlock/player/combine/voicelines/Charger/announceattack_04.ogg")
Schema.voices.Add("Charger", "ATTACKING4", "Wallhammer, full active on hostile.", "interlock/player/combine/voicelines/Charger/announceattack_05.ogg")
Schema.voices.Add("Charger", "TAKING ADVANTAGE", "Taking advantage.", "interlock/player/combine/voicelines/Charger/announceattack_08.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE2", "Target locked, daggers free.", "interlock/player/combine/voicelines/Charger/announceattack_09.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE1", "Weapons free.", "interlock/player/combine/voicelines/Charger/announceattack_11.ogg")


Schema.voices.Add("Charger", "TARGET ONE", "Target-One.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_01.ogg")
Schema.voices.Add("Charger", "STOP NOW", "Stop, now.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_02.ogg")
Schema.voices.Add("Charger", "", "It's Alyx.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_04.ogg")
Schema.voices.Add("Charger", "", "Alyx confirmed.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_06.ogg")
Schema.voices.Add("Charger", "", "Daggers on Alyx.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_07.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE3", "Weapons free on Target-One.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_08.ogg")
Schema.voices.Add("Charger", "FIRING PRIMARY", "Firing on primary hostile.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_09.ogg")
Schema.voices.Add("Charger", "ITS HER", "It's her. Wallhammer, engaging.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_10.ogg")
Schema.voices.Add("Charger", "CONFIRMED1", "Primary target confirmed.", "interlock/player/combine/voicelines/Charger/announceattack_alyx_11.ogg")


Schema.voices.Add("Charger", "BREAK COVER1", "Breaking cover.", "interlock/player/combine/voicelines/Charger/announceattack_cover_01.ogg")
Schema.voices.Add("Charger", "BREAK COVER2", "Code breakdown in sector.", "interlock/player/combine/voicelines/Charger/announceattack_cover_02.ogg")
Schema.voices.Add("Charger", "BREAK COVER3", "Designate target cover as shadow.", "interlock/player/combine/voicelines/Charger/announceattack_cover_03.ogg")
Schema.voices.Add("Charger", "BREAKING COVER IN", "Exposing hostile in three...", "interlock/player/combine/voicelines/Charger/announceattack_cover_04.ogg")
Schema.voices.Add("Charger", "BREAK COVER4", "Target is protected. Rectifying.", "interlock/player/combine/voicelines/Charger/announceattack_cover_05.ogg")
Schema.voices.Add("Charger", "BREAK COVER5", "Removing support.", "interlock/player/combine/voicelines/Charger/announceattack_cover_06.ogg")
Schema.voices.Add("Charger", "BREAK COVER6", "Daggers on cover.", "interlock/player/combine/voicelines/Charger/announceattack_cover_07.ogg")
Schema.voices.Add("Charger", "BREAK COVER7", "Full-active on target cover.", "interlock/player/combine/voicelines/Charger/announceattack_cover_08.ogg")
Schema.voices.Add("Charger", "BREAK COVER8", "Wallhammer, going sharp on cover.", "interlock/player/combine/voicelines/Charger/announceattack_cover_09.ogg")


Schema.voices.Add("Charger", "GRENADE OUT1", "Bouncer out.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_01.ogg")
Schema.voices.Add("Charger", "GRENADE OUT2", "Grenade out.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_02.ogg")
Schema.voices.Add("Charger", "GRENADE OUT3", "Extractor away.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_03.ogg")
Schema.voices.Add("Charger", "GRENADE1", "Bouncer, bouncer!", "interlock/player/combine/voicelines/Charger/announceattack_grenade_04.ogg")
Schema.voices.Add("Charger", "GET DOWN", "Get down!", "interlock/player/combine/voicelines/Charger/announceattack_grenade_05.ogg")
Schema.voices.Add("Charger", "GRENADE IN", "Bouncer in three...", "interlock/player/combine/voicelines/Charger/announceattack_grenade_06.ogg")
Schema.voices.Add("Charger", "GRENADE OUT4", "Extracting.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_07.ogg")
Schema.voices.Add("Charger", "GRENADE OUT5", "Deploying grenade.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_08.ogg")
Schema.voices.Add("Charger", "STANDING BACK", "Standing back.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_09.ogg")
Schema.voices.Add("Charger", "GRENADE OUT6", "Bouncer free.", "interlock/player/combine/voicelines/Charger/announceattack_grenade_10.ogg")


Schema.voices.Add("Charger", "ANTLION1", "Antlion.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_01.ogg")
Schema.voices.Add("Charger", "ANTLION2", "Target, antlion.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_02.ogg")
Schema.voices.Add("Charger", "ANTLION3", "Contact, antlion.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_03.ogg")
Schema.voices.Add("Charger", "ANTLION4", "Antlion incoming.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_04.ogg")
Schema.voices.Add("Charger", "ANTLION5", "Wallhammer, on antlion.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_06.ogg")
Schema.voices.Add("Charger", "ANTLION6", "Antlion. Wallhammer, engaging.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_07.ogg")
Schema.voices.Add("Charger", "ANTLION7", "Antlion. Sector.", "interlock/player/combine/voicelines/Charger/announceenemy_antlion_10.ogg")


Schema.voices.Add("Charger", "HEADCRAB1", "Parasitics.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_01.ogg")
Schema.voices.Add("Charger", "HEADCRAB2", "Contact, parasitics.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_02.ogg")
Schema.voices.Add("Charger", "HEADCRAB3", "Parasitics, inbound.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_03.ogg")
Schema.voices.Add("Charger", "HEADCRAB4", "Wallhammer, visual on parasitics.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_04.ogg")
Schema.voices.Add("Charger", "HEADCRAB5", "Viscon, parasitics.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_05.ogg")
Schema.voices.Add("Charger", "HEADCRAB6", "We've got parasitics over here.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_07.ogg")
Schema.voices.Add("Charger", "HEADCRAB7", "Live parasitics.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_08.ogg")
Schema.voices.Add("Charger", "HEADCRAB8", "Parasitic infestation confirmed.", "interlock/player/combine/voicelines/Charger/announceenemy_headcrabs_10.ogg")


Schema.voices.Add("Charger", "ZOMBIE1", "Necrotics.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_01.ogg")
Schema.voices.Add("Charger", "ZOMBIE2", "Necrotics inbound.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_02.ogg")
Schema.voices.Add("Charger", "ZOMBIE3", "Infestation confirmed.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_03.ogg")
Schema.voices.Add("Charger", "ZOMBIE4", "Wallhammer, visual on necrotics.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_04.ogg")
Schema.voices.Add("Charger", "ZOMBIE5", "Contact, necrotics.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_05.ogg")
Schema.voices.Add("Charger", "ZOMBIE6", "Sightlines on necrotics.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_06.ogg")
Schema.voices.Add("Charger", "ZOMBIE7", "Necrotics active.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_08.ogg")
Schema.voices.Add("Charger", "ZOMBIE8", "Viscon, necrotics.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_09.ogg")
Schema.voices.Add("Charger", "ZOMBIE9", "Necrotics here.", "interlock/player/combine/voicelines/Charger/announceenemy_zombie_10.ogg")


Schema.voices.Add("Charger", "DEAD1", "Hostile down.", "interlock/player/combine/voicelines/Charger/announcekill_01.ogg")
Schema.voices.Add("Charger", "DEAD2", "Target down.", "interlock/player/combine/voicelines/Charger/announcekill_02.ogg")
Schema.voices.Add("Charger", "DEAD3", "Kill confirmed.", "interlock/player/combine/voicelines/Charger/announcekill_03.ogg")
Schema.voices.Add("Charger", "DEAD4", "Clean kill.", "interlock/player/combine/voicelines/Charger/announcekill_04.ogg")
Schema.voices.Add("Charger", "DEAD5", "Another one down.", "interlock/player/combine/voicelines/Charger/announcekill_05.ogg")
Schema.voices.Add("Charger", "DEAD6", "That's it.", "interlock/player/combine/voicelines/Charger/announcekill_06.ogg")
Schema.voices.Add("Charger", "DEAD7", "Contact down.", "interlock/player/combine/voicelines/Charger/announcekill_09.ogg")
Schema.voices.Add("Charger", "DEAD8", "They're dead.", "interlock/player/combine/voicelines/Charger/announcekill_11.ogg")
Schema.voices.Add("Charger", "DEAD9", "Wallhammer, kill confirmed.", "interlock/player/combine/voicelines/Charger/announcekill_12.ogg")
Schema.voices.Add("Charger", "DEAD10", "Hostile neutralized.", "interlock/player/combine/voicelines/Charger/announcekill_13.ogg")
Schema.voices.Add("Charger", "DEAD11", "Ended.", "interlock/player/combine/voicelines/Charger/announcekill_14.ogg")
Schema.voices.Add("Charger", "DEAD12", "Hostile is over.", "interlock/player/combine/voicelines/Charger/announcekill_15.ogg")


Schema.voices.Add("Charger", "ANTLION DEAD1", "Virome down.", "interlock/player/combine/voicelines/Charger/announcekill_antlion_01.ogg")
Schema.voices.Add("Charger", "ANTLION DEAD2", "Cleaned.", "interlock/player/combine/voicelines/Charger/announcekill_antlion_02.ogg")
Schema.voices.Add("Charger", "ANTLION DEAD3", "Target sterilized.", "interlock/player/combine/voicelines/Charger/announcekill_antlion_03.ogg")
Schema.voices.Add("Charger", "ANTLION DEAD4", "Cleansed.", "interlock/player/combine/voicelines/Charger/announcekill_antlion_04.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD9", "Parasitics contained.", "interlock/player/combine/voicelines/Charger/announcekill_antlion_05.ogg")


Schema.voices.Add("Charger", "HEADCRAB DEAD1", "One parasitic cleaned.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_01.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD2", "Parasitic cleaned.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_02.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD3", "That's one.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_03.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD4", "Parasitic contained.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_04.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD5", "Cleansed.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_05.ogg")
Schema.voices.Add("Charger", "GROSS", "Gross.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_06.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD6", "Outbreak ineffective.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_07.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD7", "Outbreak contained.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_08.ogg")
Schema.voices.Add("Charger", "HEADCRAB DEAD8", "One parasitic vacated.", "interlock/player/combine/voicelines/Charger/announcekill_headcrab_09.ogg")


Schema.voices.Add("Charger", "TARGET DEAD1", "HVT is contained.", "interlock/player/combine/voicelines/Charger/announcekill_player_01.ogg")
Schema.voices.Add("Charger", "TARGET DEAD2", "Ordinal, target one is quiet.", "interlock/player/combine/voicelines/Charger/announcekill_player_02.ogg")
Schema.voices.Add("Charger", "SHES DEAD", "She's ended.", "interlock/player/combine/voicelines/Charger/announcekill_player_03.ogg")
Schema.voices.Add("Charger", "", "Ordinal, Alyx is over.", "interlock/player/combine/voicelines/Charger/announcekill_player_04.ogg")
Schema.voices.Add("Charger", "", "Alyx secure.", "interlock/player/combine/voicelines/Charger/announcekill_player_05.ogg")
Schema.voices.Add("Charger", "", "Alyx delivered.", "interlock/player/combine/voicelines/Charger/announcekill_player_06.ogg")
Schema.voices.Add("Charger", "DEAD", "Dead.", "interlock/player/combine/voicelines/Charger/announcekill_player_07.ogg")
Schema.voices.Add("Charger", "ELIMINATED", "Eliminated.", "interlock/player/combine/voicelines/Charger/announcekill_player_08.ogg")


Schema.voices.Add("Charger", "ZOMBIE DEAD1", "Necro contained.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_01.ogg")
Schema.voices.Add("Charger", "ZOMBIE DEAD2", "Necrotic contained.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_02.ogg")
Schema.voices.Add("Charger", "ZOMBIE DEAD3", "Stay dead.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_03.ogg")
Schema.voices.Add("Charger", "ZOMBIE DEAD4", "Necro down, in sector.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_04.ogg")
Schema.voices.Add("Charger", "ZOMBIE DEAD5", "Necrotic eliminated.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_05.ogg")
Schema.voices.Add("Charger", "ITS DEAD", "It's dead.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_06.ogg")
Schema.voices.Add("Charger", "ZOMBIE DEAD6", "Cleanse successful.", "interlock/player/combine/voicelines/Charger/announcekill_zombie_07.ogg")


Schema.voices.Add("Charger", "ALPHA", "Alpha.", "interlock/player/combine/voicelines/Charger/calloutcode_alpha_01.ogg")
Schema.voices.Add("Charger", "AND", "And.", "interlock/player/combine/voicelines/Charger/calloutcode_and_01.ogg")
Schema.voices.Add("Charger", "BRAVO", "Bravo.", "interlock/player/combine/voicelines/Charger/calloutcode_bravo_01.ogg")
Schema.voices.Add("Charger", "CHARLIE", "Charlie.", "interlock/player/combine/voicelines/Charger/calloutcode_charlie_01.ogg")
Schema.voices.Add("Charger", "DELTA", "Delta.", "interlock/player/combine/voicelines/Charger/calloutcode_delta_01.ogg")
Schema.voices.Add("Charger", "DASH", "Dash.", "interlock/player/combine/voicelines/Charger/calloutcode_dash_01.ogg")
Schema.voices.Add("Charger", "ECHO", "Echo.", "interlock/player/combine/voicelines/Charger/calloutcode_echo_01.ogg")
Schema.voices.Add("Charger", "EIGHT", "Eight.", "interlock/player/combine/voicelines/Charger/calloutcode_eight_01.ogg")
Schema.voices.Add("Charger", "8", "Eight.", "interlock/player/combine/voicelines/Charger/calloutcode_eight_01.ogg")
Schema.voices.Add("Charger", "ELEVEN", "Eleven.", "interlock/player/combine/voicelines/Charger/calloutcode_eleven_01.ogg")
Schema.voices.Add("Charger", "11", "Eleven.", "interlock/player/combine/voicelines/Charger/calloutcode_eleven_01.ogg")
Schema.voices.Add("Charger", "FIFTY", "Fifty.", "interlock/player/combine/voicelines/Charger/calloutcode_fifty_01.ogg")
Schema.voices.Add("Charger", "50", "Fifty.", "interlock/player/combine/voicelines/Charger/calloutcode_fifty_01.ogg")
Schema.voices.Add("Charger", "FIVE", "Five.", "interlock/player/combine/voicelines/Charger/calloutcode_five_01.ogg")
Schema.voices.Add("Charger", "5", "Five.", "interlock/player/combine/voicelines/Charger/calloutcode_five_01.ogg")
Schema.voices.Add("Charger", "FOURTY", "Fourty.", "interlock/player/combine/voicelines/Charger/calloutcode_forty_01.ogg")
Schema.voices.Add("Charger", "FORTY", "Fourty.", "interlock/player/combine/voicelines/Charger/calloutcode_forty_01.ogg")
Schema.voices.Add("Charger", "40", "Fourty.", "interlock/player/combine/voicelines/Charger/calloutcode_forty_01.ogg")
Schema.voices.Add("Charger", "FOUR", "Four.", "interlock/player/combine/voicelines/Charger/calloutcode_four_01.ogg")
Schema.voices.Add("Charger", "4", "Four.", "interlock/player/combine/voicelines/Charger/calloutcode_four_01.ogg")
Schema.voices.Add("Charger", "HUNDRED", "Hundred.", "interlock/player/combine/voicelines/Charger/calloutcode_hundred_01.ogg")
Schema.voices.Add("Charger", "NINER", "Niner.", "interlock/player/combine/voicelines/Charger/calloutcode_niner_01.ogg")
Schema.voices.Add("Charger", "9", "Niner.", "interlock/player/combine/voicelines/Charger/calloutcode_niner_01.ogg")
Schema.voices.Add("Charger", "NULL", "Null.", "interlock/player/combine/voicelines/Charger/calloutcode_null_01.ogg")
Schema.voices.Add("Charger", "ONE", "One.", "interlock/player/combine/voicelines/Charger/calloutcode_one_01.ogg")
Schema.voices.Add("Charger", "1", "One.", "interlock/player/combine/voicelines/Charger/calloutcode_one_01.ogg")
Schema.voices.Add("Charger", "SECTOR", "Sector.", "interlock/player/combine/voicelines/Charger/calloutcode_sector_01.ogg")
Schema.voices.Add("Charger", "SEVEN", "Seven.", "interlock/player/combine/voicelines/Charger/calloutcode_seven_01.ogg")
Schema.voices.Add("Charger", "7", "Seven.", "interlock/player/combine/voicelines/Charger/calloutcode_seven_01.ogg")
Schema.voices.Add("Charger", "SEVENTY", "Seventy.", "interlock/player/combine/voicelines/Charger/calloutcode_seventy_01.ogg")
Schema.voices.Add("Charger", "70", "Seventy.", "interlock/player/combine/voicelines/Charger/calloutcode_seventy_01.ogg")
Schema.voices.Add("Charger", "SIX", "Six.", "interlock/player/combine/voicelines/Charger/calloutcode_six_01.ogg")
Schema.voices.Add("Charger", "6", "Six.", "interlock/player/combine/voicelines/Charger/calloutcode_six_01.ogg")
Schema.voices.Add("Charger", "SIXTY", "Sixty.", "interlock/player/combine/voicelines/Charger/calloutcode_sixty_01.ogg")
Schema.voices.Add("Charger", "60", "Sixty.", "interlock/player/combine/voicelines/Charger/calloutcode_sixty_01.ogg")
Schema.voices.Add("Charger", "TEN", "Ten.", "interlock/player/combine/voicelines/Charger/calloutcode_ten_01.ogg")
Schema.voices.Add("Charger", "10", "Ten.", "interlock/player/combine/voicelines/Charger/calloutcode_ten_01.ogg")
Schema.voices.Add("Charger", "THIRTY", "Thirty.", "interlock/player/combine/voicelines/Charger/calloutcode_thirty_01.ogg")
Schema.voices.Add("Charger", "30", "Thirty.", "interlock/player/combine/voicelines/Charger/calloutcode_thirty_01.ogg")
Schema.voices.Add("Charger", "THOUSAND", "Thousand.", "interlock/player/combine/voicelines/Charger/calloutcode_thousand_01.ogg")
Schema.voices.Add("Charger", "THREE", "Three.", "interlock/player/combine/voicelines/Charger/calloutcode_three_01.ogg")
Schema.voices.Add("Charger", "3", "Three.", "interlock/player/combine/voicelines/Charger/calloutcode_three_01.ogg")
Schema.voices.Add("Charger", "TWENTY", "Twenty.", "interlock/player/combine/voicelines/Charger/calloutcode_twenty_01.ogg")
Schema.voices.Add("Charger", "20", "Twenty.", "interlock/player/combine/voicelines/Charger/calloutcode_twenty_01.ogg")
Schema.voices.Add("Charger", "TWO", "Two.", "interlock/player/combine/voicelines/Charger/calloutcode_two_01.ogg")
Schema.voices.Add("Charger", "2", "Two.", "interlock/player/combine/voicelines/Charger/calloutcode_two_01.ogg")


Schema.voices.Add("Charger", "", "Alyx.", "interlock/player/combine/voicelines/Charger/calloutentity_alyx_01.ogg")
Schema.voices.Add("Charger", "ANTICITIZENS", "Anti-citizens.", "interlock/player/combine/voicelines/Charger/calloutentity_anticitizens_01.ogg")
Schema.voices.Add("Charger", "ANTLION", "Antlion.", "interlock/player/combine/voicelines/Charger/calloutentity_antlion_01.ogg")
Schema.voices.Add("Charger", "APF", "APF.", "interlock/player/combine/voicelines/Charger/calloutentity_apf_01.ogg")
Schema.voices.Add("Charger", "BLADEWALL", "Bladewall.", "interlock/player/combine/voicelines/Charger/calloutentity_bladewall_01.ogg")
Schema.voices.Add("Charger", "COWALL", "Co-wall.", "interlock/player/combine/voicelines/Charger/calloutentity_cowall_01.ogg")
Schema.voices.Add("Charger", "FRIENDLY", "Friendly.", "interlock/player/combine/voicelines/Charger/calloutentity_friendly_01.ogg")
Schema.voices.Add("Charger", "HAMMERWALL", "Hammerwall.", "interlock/player/combine/voicelines/Charger/calloutentity_hammerwall_01.ogg")
Schema.voices.Add("Charger", "HOSTILES", "Hostiles.", "interlock/player/combine/voicelines/Charger/calloutentity_hostiles_01.ogg")
Schema.voices.Add("Charger", "3 PARASITICS", "Three parasitics.", "interlock/player/combine/voicelines/Charger/calloutentity_manyparasitics_01.ogg")
Schema.voices.Add("Charger", "NECROTIC", "Necrotic.", "interlock/player/combine/voicelines/Charger/calloutentity_necrotic_01.ogg")
Schema.voices.Add("Charger", "PARASITIC", "Parasitic.", "interlock/player/combine/voicelines/Charger/calloutentity_parasitic_01.ogg")
Schema.voices.Add("Charger", "SAFEMAN", "Safeman.", "interlock/player/combine/voicelines/Charger/calloutentity_safeman_01.ogg")
Schema.voices.Add("Charger", "WALLHAMMER", "Wallhammer.", "interlock/player/combine/voicelines/Charger/calloutentity_wallhammer_01.ogg")

Schema.voices.Add("Charger", "ABOVE", "Above.", "interlock/player/combine/voicelines/Charger/calloutlocation_above_01.ogg")
Schema.voices.Add("Charger", "APARTMENT", "Apartment.", "interlock/player/combine/voicelines/Charger/calloutlocation_apartment_01.ogg")
Schema.voices.Add("Charger", "BARRELS", "Barrels.", "interlock/player/combine/voicelines/Charger/calloutlocation_barrells_01.ogg")
Schema.voices.Add("Charger", "BEHIND", "Behind.", "interlock/player/combine/voicelines/Charger/calloutlocation_behind_01.ogg")
Schema.voices.Add("Charger", "BELOW", "Below.", "interlock/player/combine/voicelines/Charger/calloutlocation_below_01.ogg")
Schema.voices.Add("Charger", "BRICKS", "Bricks.", "interlock/player/combine/voicelines/Charger/calloutlocation_bricks_01.ogg")
Schema.voices.Add("Charger", "RIGGS", "Riggs.", "interlock/player/combine/voicelines/Charger/calloutlocation_bricks_01.ogg")
Schema.voices.Add("Charger", "BRIDGE", "Bridge.", "interlock/player/combine/voicelines/Charger/calloutlocation_bridge_01.ogg")
Schema.voices.Add("Charger", "BUILDING", "Building.", "interlock/player/combine/voicelines/Charger/calloutlocation_building_01.ogg")
Schema.voices.Add("Charger", "CAR", "Car.", "interlock/player/combine/voicelines/Charger/calloutlocation_car_01.ogg")
Schema.voices.Add("Charger", "CRANE", "Crane.", "interlock/player/combine/voicelines/Charger/calloutlocation_crane_01.ogg")
Schema.voices.Add("Charger", "DOOR", "Door.", "interlock/player/combine/voicelines/Charger/calloutlocation_door_01.ogg")
Schema.voices.Add("Charger", "ELEVATOR", "Elevator.", "interlock/player/combine/voicelines/Charger/calloutlocation_elevator_01.ogg")
Schema.voices.Add("Charger", "FRONT", "Front.", "interlock/player/combine/voicelines/Charger/calloutlocation_front_01.ogg")
Schema.voices.Add("Charger", "HUT", "Hut.", "interlock/player/combine/voicelines/Charger/calloutlocation_hut_01.ogg")
Schema.voices.Add("Charger", "PIPES", "Pipes.", "interlock/player/combine/voicelines/Charger/calloutlocation_pipes_01.ogg")
Schema.voices.Add("Charger", "SHACK", "Shack.", "interlock/player/combine/voicelines/Charger/calloutlocation_shack_01.ogg")
Schema.voices.Add("Charger", "TOILET", "Toilet.", "interlock/player/combine/voicelines/Charger/calloutlocation_toilet_01.ogg")
Schema.voices.Add("Charger", "TRAINCAR", "Traincar.", "interlock/player/combine/voicelines/Charger/calloutlocation_traincar_01.ogg")
Schema.voices.Add("Charger", "TRASH", "Trash.", "interlock/player/combine/voicelines/Charger/calloutlocation_trash_01.ogg")
Schema.voices.Add("Charger", "TRUCK", "Truck.", "interlock/player/combine/voicelines/Charger/calloutlocation_truck_01.ogg")
Schema.voices.Add("Charger", "TUNNEL", "Tunnel.", "interlock/player/combine/voicelines/Charger/calloutlocation_tunnel_01.ogg")
Schema.voices.Add("Charger", "VAN", "Van.", "interlock/player/combine/voicelines/Charger/calloutlocation_van_01.ogg")
Schema.voices.Add("Charger", "WHEELS", "Wheels.", "interlock/player/combine/voicelines/Charger/calloutlocation_wheels_01.ogg")
Schema.voices.Add("Charger", "WOODPILE", "Woodpile.", "interlock/player/combine/voicelines/Charger/calloutlocation_woodpile_01.ogg")


Schema.voices.Add("Charger", "STRIKING1", "Striking them.", "interlock/player/combine/voicelines/Charger/charging_01.ogg")
Schema.voices.Add("Charger", "STRIKING2", "Striking now.", "interlock/player/combine/voicelines/Charger/charging_02.ogg")
Schema.voices.Add("Charger", "STRIKING", "Striking.", "interlock/player/combine/voicelines/Charger/charging_03.ogg")
Schema.voices.Add("Charger", "STRIKE", "Strike.", "interlock/player/combine/voicelines/Charger/charging_04.ogg")
Schema.voices.Add("Charger", "YELL", "*Garbled Yelling*", "interlock/player/combine/voicelines/Charger/charging_05.ogg")
Schema.voices.Add("Charger", "STRIKING3", "Strike fast.", "interlock/player/combine/voicelines/Charger/charging_06.ogg")


Schema.voices.Add("Charger", "OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "interlock/player/combine/voicelines/Charger/combat_idle_012.ogg")
Schema.voices.Add("Charger", "TARGET ACTIVE", "Negative, target is still active.", "interlock/player/combine/voicelines/Charger/combat_idle_020.ogg")
Schema.voices.Add("Charger", "CON ALPHA", "Copy that. Forming condition ALPHA.", "interlock/player/combine/voicelines/Charger/combat_idle_030.ogg")
Schema.voices.Add("Charger", "CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "interlock/player/combine/voicelines/Charger/combat_idle_031.ogg")
Schema.voices.Add("Charger", "HOLDING FOR", "Holding for advanced directive, over.", "interlock/player/combine/voicelines/Charger/combat_idle_040.ogg")
Schema.voices.Add("Charger", "RECALIBRATING", "Confirmed, recalibrating.", "interlock/player/combine/voicelines/Charger/combat_idle_050.ogg")
Schema.voices.Add("Charger", "SETTING UP", "Copy, setting up position.", "interlock/player/combine/voicelines/Charger/combat_idle_060.ogg")
Schema.voices.Add("Charger", "STILL ACTIVE", "They're still alive.", "interlock/player/combine/voicelines/Charger/combat_idle_070.ogg")
Schema.voices.Add("Charger", "CC UNDERWAY", "Copy that, contain and control is underway.", "interlock/player/combine/voicelines/Charger/combat_idle_080.ogg")
Schema.voices.Add("Charger", "RELOADING", "Reloading.", "interlock/player/combine/voicelines/Charger/combat_idle_090.ogg")
Schema.voices.Add("Charger", "LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "interlock/player/combine/voicelines/Charger/combat_idle_100.ogg")
Schema.voices.Add("Charger", "TAC ADV", "Forming tactical advantage.", "interlock/player/combine/voicelines/Charger/combat_idle_110.ogg")
Schema.voices.Add("Charger", "STILL HOLDING", "Still holding.", "interlock/player/combine/voicelines/Charger/combat_idle_120.ogg")
Schema.voices.Add("Charger", "STILL HOLDING2", "Still holding.", "interlock/player/combine/voicelines/Charger/combat_idle_121.ogg")
Schema.voices.Add("Charger", "HOLDING BIODAT", "Holding for biodat upload.", "interlock/player/combine/voicelines/Charger/combat_idle_130.ogg")
Schema.voices.Add("Charger", "PREPARE SUNDOWN", "Prepare for sundown.", "interlock/player/combine/voicelines/Charger/combat_idle_140.ogg")
Schema.voices.Add("Charger", "PREPARING SUNDOWN", "Preparing for sundown.", "interlock/player/combine/voicelines/Charger/combat_idle_141.ogg")
Schema.voices.Add("Charger", "PREPARE COMMS", "Preparing comms for extended conflict.", "interlock/player/combine/voicelines/Charger/combat_idle_150.ogg")
Schema.voices.Add("Charger", "NO DAGGERS", "Negative, no daggers needed.", "interlock/player/combine/voicelines/Charger/combat_idle_160.ogg")
Schema.voices.Add("Charger", "EXTENDING", "Extending conflict duration.", "interlock/player/combine/voicelines/Charger/combat_idle_170.ogg")
Schema.voices.Add("Charger", "SCANNING BIODATS", "Scanning hostile biodats.", "interlock/player/combine/voicelines/Charger/combat_idle_180.ogg")
Schema.voices.Add("Charger", "DISREGARDING", "Disregarding last call.", "interlock/player/combine/voicelines/Charger/combat_idle_190.ogg")
Schema.voices.Add("Charger", "OW 10-9", "Overwatch, ten-niner.", "interlock/player/combine/voicelines/Charger/combat_idle_200.ogg")


Schema.voices.Add("Charger", "GRENADE3", "Evading.", "interlock/player/combine/voicelines/Charger/danger_grenade_01.ogg")
Schema.voices.Add("Charger", "GRENADE2", "Grenade!", "interlock/player/combine/voicelines/Charger/danger_grenade_02.ogg")
Schema.voices.Add("Charger", "TAKING COVER", "Taking cover.", "interlock/player/combine/voicelines/Charger/danger_grenade_03.ogg")
Schema.voices.Add("Charger", "GRENADE4", "Live grenade.", "interlock/player/combine/voicelines/Charger/danger_grenade_04.ogg")
Schema.voices.Add("Charger", "GRENADE5", "Audible bouncer, evading.", "interlock/player/combine/voicelines/Charger/danger_grenade_05.ogg")
Schema.voices.Add("Charger", "GRENADE6", "Grenade, move!", "interlock/player/combine/voicelines/Charger/danger_grenade_06.ogg")
Schema.voices.Add("Charger", "WALL UP", "Wall, up!", "interlock/player/combine/voicelines/Charger/danger_grenade_07.ogg")
Schema.voices.Add("Charger", "ALERT RADIALS", "Alert on radials.", "interlock/player/combine/voicelines/Charger/danger_grenade_08.ogg")
Schema.voices.Add("Charger", "STAND BACK WALL", "Standing back with wall.", "interlock/player/combine/voicelines/Charger/danger_grenade_09.ogg")
Schema.voices.Add("Charger", "GRENADE7", "Live bouncer!", "interlock/player/combine/voicelines/Charger/danger_grenade_10.ogg")


Schema.voices.Add("Charger", "LOF1", "Wallhammer, closing.", "interlock/player/combine/voicelines/Charger/establishinglof_01.ogg")
Schema.voices.Add("Charger", "LOF2", "Wallhammer, switching position.", "interlock/player/combine/voicelines/Charger/establishinglof_02.ogg")
Schema.voices.Add("Charger", "LOF3", "Maintain visuals.", "interlock/player/combine/voicelines/Charger/establishinglof_03.ogg")
Schema.voices.Add("Charger", "LOF4", "Holding sightlines.", "interlock/player/combine/voicelines/Charger/establishinglof_04.ogg")
Schema.voices.Add("Charger", "LOF5", "Realigning to hostile.", "interlock/player/combine/voicelines/Charger/establishinglof_05.ogg")
Schema.voices.Add("Charger", "LOF6", "Target visual confirmation.", "interlock/player/combine/voicelines/Charger/establishinglof_06.ogg")
Schema.voices.Add("Charger", "LOF7", "I'm marking sightlines.", "interlock/player/combine/voicelines/Charger/establishinglof_07.ogg")
Schema.voices.Add("Charger", "NO VISUAL", "No visual on target. Move!", "interlock/player/combine/voicelines/Charger/establishinglof_08.ogg")
Schema.voices.Add("Charger", "LOF8", "Realigning target delta.", "interlock/player/combine/voicelines/Charger/establishinglof_09.ogg")
Schema.voices.Add("Charger", "STAY THERE", "Stay there!", "interlock/player/combine/voicelines/Charger/establishinglof_10.ogg")
Schema.voices.Add("Charger", "CHANGING POS1", "Changing position.", "interlock/player/combine/voicelines/Charger/establishinglof_11.ogg")
Schema.voices.Add("Charger", "CHANGING POS2", "Optimizing location.", "interlock/player/combine/voicelines/Charger/establishinglof_12.ogg")
Schema.voices.Add("Charger", "CHANGING POS3", "Optimizing viscon.", "interlock/player/combine/voicelines/Charger/establishinglof_13.ogg")
Schema.voices.Add("Charger", "CHANGING POS4", "Problem visual, moving.", "interlock/player/combine/voicelines/Charger/establishinglof_14.ogg")
Schema.voices.Add("Charger", "CHANGING POS5", "Clearing sightlines.", "interlock/player/combine/voicelines/Charger/establishinglof_15.ogg")
Schema.voices.Add("Charger", "CHANGING POS6", "Forming sightlines.", "interlock/player/combine/voicelines/Charger/establishinglof_16.ogg")
Schema.voices.Add("Charger", "CONTACT IN", "Contact in three...", "interlock/player/combine/voicelines/Charger/establishinglof_17.ogg")
Schema.voices.Add("Charger", "EXPOSING", "Exposing target one.", "interlock/player/combine/voicelines/Charger/establishinglof_18.ogg")
Schema.voices.Add("Charger", "DONT MOVE", "Don't move.", "interlock/player/combine/voicelines/Charger/establishinglof_19.ogg")


Schema.voices.Add("Charger", "", "Alyx!", "interlock/player/combine/voicelines/Charger/fakeout_calltoalyx_01.ogg")
Schema.voices.Add("Charger", "", "Hey, Alyx!", "interlock/player/combine/voicelines/Charger/fakeout_calltoalyx_02.ogg")
Schema.voices.Add("Charger", "", "Hey Alyx, it's us!", "interlock/player/combine/voicelines/Charger/fakeout_calltoalyx_03.ogg")
Schema.voices.Add("Charger", "", "Alyx, you there?", "interlock/player/combine/voicelines/Charger/fakeout_calltoalyx_04.ogg")
Schema.voices.Add("Charger", "", "Alyx!", "interlock/player/combine/voicelines/Charger/fakeout_calltoalyx_05.ogg")


Schema.voices.Add("Charger", "TARGET FRIENDLY", "Cease fire, target is friendly.", "interlock/player/combine/voicelines/Charger/fakeout_responseceasefire_01.ogg")
Schema.voices.Add("Charger", "STANDING DOWN", "Hammer down, Wallhammer stepping down.", "interlock/player/combine/voicelines/Charger/fakeout_responseceasefire_02.ogg")
Schema.voices.Add("Charger", "CEASE FIRE", "Cease fire! No threat, no threat!", "interlock/player/combine/voicelines/Charger/fakeout_responseceasefire_03.ogg")
Schema.voices.Add("Charger", "", "Alyx is friendly.", "interlock/player/combine/voicelines/Charger/fakeout_responseceasefire_04.ogg")
Schema.voices.Add("Charger", "", "Stop fire! Alyx is friendly!", "interlock/player/combine/voicelines/Charger/fakeout_responseceasefire_05.ogg")


Schema.voices.Add("Charger", "HAHA", "Haha.", "interlock/player/combine/voicelines/Charger/fakeout_success_01.ogg")
Schema.voices.Add("Charger", "FRIEND GAME", "Friend game effective.", "interlock/player/combine/voicelines/Charger/fakeout_success_02.ogg")
Schema.voices.Add("Charger", "HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "interlock/player/combine/voicelines/Charger/fakeout_success_03.ogg")


Schema.voices.Add("Charger", "FIRING", "Firing.", "interlock/player/combine/voicelines/Charger/firing_01.ogg")
Schema.voices.Add("Charger", "FIRING2", "Engaging target.", "interlock/player/combine/voicelines/Charger/firing_02.ogg")
Schema.voices.Add("Charger", "FIRING3", "Wallhammer engaging.", "interlock/player/combine/voicelines/Charger/firing_03.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE4", "Weapons free.", "interlock/player/combine/voicelines/Charger/firing_04.ogg")
Schema.voices.Add("Charger", "FIRING4", "Wallhammer, primary setpoint.", "interlock/player/combine/voicelines/Charger/firing_05.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE5", "Open fire, weapons free.", "interlock/player/combine/voicelines/Charger/firing_06.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE6", "Code Three, alter Delta.", "interlock/player/combine/voicelines/Charger/firing_07.ogg")
Schema.voices.Add("Charger", "FIRING5", "Cleaning sector.", "interlock/player/combine/voicelines/Charger/firing_08.ogg")
Schema.voices.Add("Charger", "FIRING6", "Committed.", "interlock/player/combine/voicelines/Charger/firing_09.ogg")
Schema.voices.Add("Charger", "WEAPONS FREE7", "Daggers free.", "interlock/player/combine/voicelines/Charger/firing_10.ogg")
Schema.voices.Add("Charger", "FIRING7", "Engaged and firing.", "interlock/player/combine/voicelines/Charger/firing_110.ogg")
Schema.voices.Add("Charger", "FIRING8", "Enforcing stability on primary target in sector.", "interlock/player/combine/voicelines/Charger/firing_120.ogg")
Schema.voices.Add("Charger", "FIRING9", "Target is in line.", "interlock/player/combine/voicelines/Charger/firing_130.ogg")
Schema.voices.Add("Charger", "FIRING10", "Target is in line and receiving spikes.", "interlock/player/combine/voicelines/Charger/firing_131.ogg")
Schema.voices.Add("Charger", "ESCALATING", "Escalating force on primary target.", "interlock/player/combine/voicelines/Charger/firing_140.ogg")
Schema.voices.Add("Charger", "GOING DOWN3", "They're going down.", "interlock/player/combine/voicelines/Charger/firing_150.ogg")
Schema.voices.Add("Charger", "GOING DOWN2", "They're going down.", "interlock/player/combine/voicelines/Charger/firing_151.ogg")
Schema.voices.Add("Charger", "GOING DOWN", "They're going down!", "interlock/player/combine/voicelines/Charger/firing_152.ogg")
Schema.voices.Add("Charger", "ALMOST OVER2", "Almost over.", "interlock/player/combine/voicelines/Charger/firing_160.ogg")
Schema.voices.Add("Charger", "ALMOST OVER", "It's almost over!", "interlock/player/combine/voicelines/Charger/firing_161.ogg")
Schema.voices.Add("Charger", "ALMOST OVER3", "It's almost over.", "interlock/player/combine/voicelines/Charger/firing_162.ogg")
Schema.voices.Add("Charger", "SENDING SPIKES", "Sending spikes.", "interlock/player/combine/voicelines/Charger/firing_170.ogg")
Schema.voices.Add("Charger", "SENDING SPIKES2", "Sending all spikes to primary target.", "interlock/player/combine/voicelines/Charger/firing_180.ogg")
Schema.voices.Add("Charger", "SENDING SPIKES3", "I'm sending all spikes.", "interlock/player/combine/voicelines/Charger/firing_190.ogg")
Schema.voices.Add("Charger", "DONT RESIST", "Don't resist.", "interlock/player/combine/voicelines/Charger/firing_200.ogg")
Schema.voices.Add("Charger", "WH ENGAGED", "Wallhammer, is engaged and firing.", "interlock/player/combine/voicelines/Charger/firing_210.ogg")
Schema.voices.Add("Charger", "ORDINAL FIRING", "Ordinal is engaged and firing.", "interlock/player/combine/voicelines/Charger/firing_220.ogg")
Schema.voices.Add("Charger", "APF FIRING", "APF is engaged and firing.", "interlock/player/combine/voicelines/Charger/firing_230.ogg")


Schema.voices.Add("Charger", "TARGET FIRE", "Open fire, priority one.", "interlock/player/combine/voicelines/Charger/firing_player_01.ogg")
Schema.voices.Add("Charger", "", "Opening fire on Alyx.", "interlock/player/combine/voicelines/Charger/firing_player_02.ogg")
Schema.voices.Add("Charger", "TARGET FIRE2", "Wallhammer, on prime target.", "interlock/player/combine/voicelines/Charger/firing_player_03.ogg")
Schema.voices.Add("Charger", "ORDINAL FIRE AT", "Ordinal, open fire at...", "interlock/player/combine/voicelines/Charger/firing_player_04.ogg")
Schema.voices.Add("Charger", "", "Daggers free on Vance.", "interlock/player/combine/voicelines/Charger/firing_player_05.ogg")


Schema.voices.Add("Charger", "FLASH FAIL", "Reflash in five.", "interlock/player/combine/voicelines/Charger/flash_failed_01.ogg")
Schema.voices.Add("Charger", "FLASH FAIL2", "Null flash, amend.", "interlock/player/combine/voicelines/Charger/flash_failed_03.ogg")
Schema.voices.Add("Charger", "FLASH FAIL3", "Requesting re-flash on target.", "interlock/player/combine/voicelines/Charger/flash_failed_05.ogg")
Schema.voices.Add("Charger", "FLASH FAIL4", "Blinder has failed.", "interlock/player/combine/voicelines/Charger/flash_failed_06.ogg")


Schema.voices.Add("Charger", "FLASHED", "Flash success, moving in.", "interlock/player/combine/voicelines/Charger/flash_success_01.ogg")
Schema.voices.Add("Charger", "FLASHED2", "Hostile is blinded.", "interlock/player/combine/voicelines/Charger/flash_success_03.ogg")
Schema.voices.Add("Charger", "FLASHED3", "Target has no visuals. Taking advantage.", "interlock/player/combine/voicelines/Charger/flash_success_04.ogg")
Schema.voices.Add("Charger", "FLASHED4", "Contaminant is scrambled.", "interlock/player/combine/voicelines/Charger/flash_success_05.ogg")
Schema.voices.Add("Charger", "FLASHED5", "Hostile is scrambled. All units, take advantage.", "interlock/player/combine/voicelines/Charger/flash_success_06.ogg")


Schema.voices.Add("Charger", "FLUSHING", "Clearing.", "interlock/player/combine/voicelines/Charger/flushing_01.ogg")
Schema.voices.Add("Charger", "FLUSHING2", "Distribution on three...", "interlock/player/combine/voicelines/Charger/flushing_02.ogg")
Schema.voices.Add("Charger", "FLUSHING3", "Wallhammer, flushing sector.", "interlock/player/combine/voicelines/Charger/flushing_03.ogg")
Schema.voices.Add("Charger", "EXTRACTING AT", "Wallhammer, extracting at...", "interlock/player/combine/voicelines/Charger/flushing_04.ogg")
Schema.voices.Add("Charger", "FLUSHING4", "Applying pressure. Flare down.", "interlock/player/combine/voicelines/Charger/flushing_05.ogg")
Schema.voices.Add("Charger", "FLUSHING5", "Extracting hostile at last known.", "interlock/player/combine/voicelines/Charger/flushing_06.ogg")
Schema.voices.Add("Charger", "FLUSHING6", "Bouncer, bouncer, on last known.", "interlock/player/combine/voicelines/Charger/flushing_07.ogg")


Schema.voices.Add("Charger", "DISPERSING", "Dispersing.", "interlock/player/combine/voicelines/Charger/getback_01.ogg")
Schema.voices.Add("Charger", "WALL UP COVER", "Wall up, taking cover.", "interlock/player/combine/voicelines/Charger/getback_02.ogg")
Schema.voices.Add("Charger", "GRENADE DOWN", "Grenade down.", "interlock/player/combine/voicelines/Charger/getback_03.ogg")
Schema.voices.Add("Charger", "BOUNCER", "Bouncer, bouncer.", "interlock/player/combine/voicelines/Charger/getback_04.ogg")
Schema.voices.Add("Charger", "EXTRACTOR", "Extractor down.", "interlock/player/combine/voicelines/Charger/getback_05.ogg")


Schema.voices.Add("Charger", "HEAR", "Audible, in sector.", "interlock/player/combine/voicelines/Charger/hear_suspicious_01.ogg")
Schema.voices.Add("Charger", "HEAR2", "Possible contaminant.", "interlock/player/combine/voicelines/Charger/hear_suspicious_02.ogg")
Schema.voices.Add("Charger", "HEAR3", "Possible hostile active.", "interlock/player/combine/voicelines/Charger/hear_suspicious_03.ogg")
Schema.voices.Add("Charger", "HEAR4", "Movement, at Wallhammer.", "interlock/player/combine/voicelines/Charger/hear_suspicious_04.ogg")
Schema.voices.Add("Charger", "SOUND ON", "Sound on.", "interlock/player/combine/voicelines/Charger/hear_suspicious_05.ogg")
Schema.voices.Add("Charger", "SOUND ON2", "Sound on, annnd reporting all contaminants.", "interlock/player/combine/voicelines/Charger/hear_suspicious_06.ogg")


Schema.voices.Add("Charger", "IDLE1", "Nothing to report, over.", "interlock/player/combine/voicelines/Charger/idle_01.ogg")
Schema.voices.Add("Charger", "IDLE2", "One, fourteen, three, six, eleven. Check. All clear on Echo-Four, over.", "interlock/player/combine/voicelines/Charger/idle_02.ogg")
Schema.voices.Add("Charger", "IDLE3", "Copy that. Sustaining viscon at sector NOMAD-KILO-THREE-DASH-SIX.", "interlock/player/combine/voicelines/Charger/idle_03.ogg")
Schema.voices.Add("Charger", "IDLE4", "Echo-One has negative movement. Grid SEVEN-DASH-TWO.", "interlock/player/combine/voicelines/Charger/idle_04.ogg")
Schema.voices.Add("Charger", "STANDING BY", "Affirmative. Standing by for opportunities.", "interlock/player/combine/voicelines/Charger/idle_05.ogg")
Schema.voices.Add("Charger", "TRANSMISSION CLEAR", "Transmission clear, radials clear, over.", "interlock/player/combine/voicelines/Charger/idle_06.ogg")
Schema.voices.Add("Charger", "REQUEST PROXY", "Overwatch, requesting proximity data on hostiles. Holding for transmission.", "interlock/player/combine/voicelines/Charger/idle_07.ogg")
Schema.voices.Add("Charger", "HOLDING TRANSMISSION", "Still holding for transmission, over.", "interlock/player/combine/voicelines/Charger/idle_08.ogg")
Schema.voices.Add("Charger", "SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "interlock/player/combine/voicelines/Charger/idle_09.ogg")
Schema.voices.Add("Charger", "IDLE5", "Affirmative, outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "interlock/player/combine/voicelines/Charger/idle_10.ogg")
Schema.voices.Add("Charger", "IDLE6", "Negative... Copy that... No sector containment, no confirmation on target one vector... waiting for secondary parameter codes.", "interlock/player/combine/voicelines/Charger/idle_11.ogg")
Schema.voices.Add("Charger", "UPDATING BIODAT", "Updating biodat... Stimdose: Thirty-Two. Dagger: Seventy-Eight. Shield: One-Hundred. Biprox: Point-Seven-Three.. Audibles: Three. Lightvis: Fifteen. Over.", "interlock/player/combine/voicelines/Charger/idle_12.ogg")
Schema.voices.Add("Charger", "IDLE7", "Roger that. Setting viscerators in Apex-Five. We have biotics at the perimeter. Waiting for contact. Over.", "interlock/player/combine/voicelines/Charger/idle_13.ogg")
Schema.voices.Add("Charger", "NON TAGGED VIROMES", "Overwatch confirms non-tagged viromes inbound. All units advisory, prepare for contact.", "interlock/player/combine/voicelines/Charger/idle_14.ogg")
Schema.voices.Add("Charger", "IDLE8", "Callout code: DELTA-ECHO-SEVEN-NINER-ALPHA-TWO-WINDER-ZERO... confirmed.", "interlock/player/combine/voicelines/Charger/idle_15.ogg")
Schema.voices.Add("Charger", "STILL HERE", "Roger that. Still here.", "interlock/player/combine/voicelines/Charger/idle_16.ogg")
Schema.voices.Add("Charger", "COPY THAT2", "Copy that.", "interlock/player/combine/voicelines/Charger/idle_17.ogg")
Schema.voices.Add("Charger", "ACCEPT DISSONANCE UPDATE", "Copy, accepted. Updating cognitive suppression biodats. Update complete in t-minus three seconds. Dissonance resolved.", "interlock/player/combine/voicelines/Charger/idle_18.ogg")
Schema.voices.Add("Charger", "DISSONANCE UPDATE", "Overwatch is requesting all units refresh and resolve. Cognitive dissonance will not be tolerated. Negative... memories included. Update is live, acceptance is mandatory.", "interlock/player/combine/voicelines/Charger/idle_19.ogg")
Schema.voices.Add("Charger", "IDLE9", "Stablization team holding position. Lightvis at Seven-Three. Audibles at... Fifteen. Overwatch confirms HVT is perimeter inbound.", "interlock/player/combine/voicelines/Charger/idle_20.ogg")


Schema.voices.Add("Charger", "INJURED", "Requesting stimdose.", "interlock/player/combine/voicelines/Charger/injured_01.ogg")
Schema.voices.Add("Charger", "INJURED2", "Ordinal... I'm hit.", "interlock/player/combine/voicelines/Charger/injured_02.ogg")
Schema.voices.Add("Charger", "INJURED3", "Taking damage.", "interlock/player/combine/voicelines/Charger/injured_03.ogg")
Schema.voices.Add("Charger", "ASSIST", "Assist on Wallhammer!", "interlock/player/combine/voicelines/Charger/injured_04.ogg")
Schema.voices.Add("Charger", "INJURED4", "Wallhammer still active.", "interlock/player/combine/voicelines/Charger/injured_05.ogg")
Schema.voices.Add("Charger", "INJURED5", "Ineffective.", "interlock/player/combine/voicelines/Charger/injured_06.ogg")
Schema.voices.Add("Charger", "INJURED6", "Bodypacks holding.", "interlock/player/combine/voicelines/Charger/injured_07.ogg")


Schema.voices.Add("Charger", "HAHA2", "Haha.", "interlock/player/combine/voicelines/Charger/laugh_01.ogg")
Schema.voices.Add("Charger", "HAHA3", "Haha.", "interlock/player/combine/voicelines/Charger/laugh_02.ogg")
Schema.voices.Add("Charger", "HAHA4", "Haha.", "interlock/player/combine/voicelines/Charger/laugh_03.ogg")
Schema.voices.Add("Charger", "HAHA5", "Haha.", "interlock/player/combine/voicelines/Charger/laugh_04.ogg")
Schema.voices.Add("Charger", "HAHA6", "Haha.", "interlock/player/combine/voicelines/Charger/laugh_05.ogg")


Schema.voices.Add("Charger", "LOST ENEMY", "Contaminant not visible.", "interlock/player/combine/voicelines/Charger/lostenemy_01.ogg")
Schema.voices.Add("Charger", "GOD DAMNIT", "God damnit.", "interlock/player/combine/voicelines/Charger/lostenemy_02.ogg")
Schema.voices.Add("Charger", "REQUESTING LOCATION", "Requesting location.", "interlock/player/combine/voicelines/Charger/lostenemy_03.ogg")
Schema.voices.Add("Charger", "LOST ENEMY2", "Target lost.", "interlock/player/combine/voicelines/Charger/lostenemy_04.ogg")
Schema.voices.Add("Charger", "LOST ENEMY3", "Location assist, Wallhammer.", "interlock/player/combine/voicelines/Charger/lostenemy_05.ogg")
Schema.voices.Add("Charger", "LOST ENEMY4", "Hostile, visual, negative.", "interlock/player/combine/voicelines/Charger/lostenemy_06.ogg")
Schema.voices.Add("Charger", "LOST ENEMY5", "Lost sight. Contain.", "interlock/player/combine/voicelines/Charger/lostenemy_07.ogg")
Schema.voices.Add("Charger", "LOST ENEMY6", "No visual, Wallhammer.", "interlock/player/combine/voicelines/Charger/lostenemy_08.ogg")


Schema.voices.Add("Charger", "LOST VISUAL", "Missing hostile, sector unknown.", "interlock/player/combine/voicelines/Charger/lostvisual_01.ogg")
Schema.voices.Add("Charger", "LOST VISUAL2", "Wallhammer, requesting target location.", "interlock/player/combine/voicelines/Charger/lostvisual_02.ogg")
Schema.voices.Add("Charger", "REQUESTING LOCATION2", "Requesting location.", "interlock/player/combine/voicelines/Charger/lostvisual_03.ogg")
Schema.voices.Add("Charger", "LOST VISUAL3", "Lost sight of hostile.", "interlock/player/combine/voicelines/Charger/lostvisual_04.ogg")
Schema.voices.Add("Charger", "LOST VISUAL4", "Location assist on Wallhammer.", "interlock/player/combine/voicelines/Charger/lostvisual_05.ogg")
Schema.voices.Add("Charger", "LOST VISUAL5", "Need location assistance.", "interlock/player/combine/voicelines/Charger/lostvisual_07.ogg")
Schema.voices.Add("Charger", "NO VISUAL", "No visual.", "interlock/player/combine/voicelines/Charger/lostvisual_08.ogg")
Schema.voices.Add("Charger", "LOST VISUAL6", "Wallhammer, negative on visual.", "interlock/player/combine/voicelines/Charger/lostvisual_09.ogg")
Schema.voices.Add("Charger", "LOST VISUAL7", "Lost location, requesting hostile location.", "interlock/player/combine/voicelines/Charger/lostvisual_10.ogg")


Schema.voices.Add("Charger", "TARGET LOST", "Contaminant is quiet, requesting last known sector.", "interlock/player/combine/voicelines/Charger/lostvisual_player_01.ogg")
Schema.voices.Add("Charger", "VISUAL BLACKOUT", "We have total visual blackout.", "interlock/player/combine/voicelines/Charger/lostvisual_player_02.ogg")
Schema.voices.Add("Charger", "TARGET LOST2", "Hostile is quiet.", "interlock/player/combine/voicelines/Charger/lostvisual_player_03.ogg")
Schema.voices.Add("Charger", "TARGET LOST3", "Contaminant is evasive.", "interlock/player/combine/voicelines/Charger/lostvisual_player_04.ogg")
Schema.voices.Add("Charger", "CHECKING COVER", "Checking cover.", "interlock/player/combine/voicelines/Charger/lostvisual_player_05.ogg")
Schema.voices.Add("Charger", "CONTACT CHECK AT", "Contact check at...", "interlock/player/combine/voicelines/Charger/lostvisual_player_06.ogg")
Schema.voices.Add("Charger", "VISUALS LOST", "All visuals lost - eyes on.", "interlock/player/combine/voicelines/Charger/lostvisual_player_07.ogg")
Schema.voices.Add("Charger", "TARGET LOST4", "All contact quiet at Wallhammer. Requesting recon.", "interlock/player/combine/voicelines/Charger/lostvisual_player_08.ogg")


Schema.voices.Add("Charger", "PROXIMITY", "Proximity!", "interlock/player/combine/voicelines/Charger/nearpanic_02.ogg")
Schema.voices.Add("Charger", "PROXIMITY2", "Proximity threat, release!", "interlock/player/combine/voicelines/Charger/nearpanic_03.ogg")
Schema.voices.Add("Charger", "ASSIST2", "Assist, assist, assist!", "interlock/player/combine/voicelines/Charger/nearpanic_04.ogg")
Schema.voices.Add("Charger", "ASSIST3", "Wall assist, wall assist!", "interlock/player/combine/voicelines/Charger/nearpanic_05.ogg")
Schema.voices.Add("Charger", "BACK DOWN", "Back down, back down!", "interlock/player/combine/voicelines/Charger/nearpanic_07.ogg")


Schema.voices.Add("Charger", "COPY", "Copy.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_01.ogg")
Schema.voices.Add("Charger", "ROGER", "Roger.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_02.ogg")
Schema.voices.Add("Charger", "COPY THAT", "Copy that.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_03.ogg")
Schema.voices.Add("Charger", "POSITIVE", "Positive.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_04.ogg")
Schema.voices.Add("Charger", "PROCEEDING", "Proceeding.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_05.ogg")
Schema.voices.Add("Charger", "AFFIRMATIVE", "Affirmative.", "interlock/player/combine/voicelines/Charger/orderresponse_positive_06.ogg")


Schema.voices.Add("Charger", "HOLDING", "Holding position.", "interlock/player/combine/voicelines/Charger/overwatch_01.ogg")
Schema.voices.Add("Charger", "LOCATION LOCKED", "Location locked.", "interlock/player/combine/voicelines/Charger/overwatch_02.ogg")
Schema.voices.Add("Charger", "WEAPONS READY", "Weapons ready.", "interlock/player/combine/voicelines/Charger/overwatch_03.ogg")
Schema.voices.Add("Charger", "VISCON LAST", "Viscon on last known position.", "interlock/player/combine/voicelines/Charger/overwatch_04.ogg")
Schema.voices.Add("Charger", "EYES LAST KNOWN", "Eyes on last known.", "interlock/player/combine/voicelines/Charger/overwatch_05.ogg")
Schema.voices.Add("Charger", "OBSERVING", "Observing.", "interlock/player/combine/voicelines/Charger/overwatch_06.ogg")
Schema.voices.Add("Charger", "IN POSITION", "Wallhammer, in position.", "interlock/player/combine/voicelines/Charger/overwatch_07.ogg")
Schema.voices.Add("Charger", "HOLDING2", "Holding focus.", "interlock/player/combine/voicelines/Charger/overwatch_08.ogg")
Schema.voices.Add("Charger", "STOP SOUND", "Stop sound, stop sound.", "interlock/player/combine/voicelines/Charger/overwatch_09.ogg")
Schema.voices.Add("Charger", "HOSTILE UNWILLING", "Hostile unwilling, stand by.", "interlock/player/combine/voicelines/Charger/overwatch_10.ogg")
Schema.voices.Add("Charger", "HOLD", "Hold.", "interlock/player/combine/voicelines/Charger/overwatch_11.ogg")
Schema.voices.Add("Charger", "WAITING CONTACT", "Waiting for contact.", "interlock/player/combine/voicelines/Charger/overwatch_12.ogg")
Schema.voices.Add("Charger", "EVALUATING", "Evaluating.", "interlock/player/combine/voicelines/Charger/overwatch_13.ogg")
Schema.voices.Add("Charger", "AWAITING", "Awaiting problem.", "interlock/player/combine/voicelines/Charger/overwatch_14.ogg")
Schema.voices.Add("Charger", "WAITING CONTAINMENT", "Waiting for containment.", "interlock/player/combine/voicelines/Charger/overwatch_15.ogg")
Schema.voices.Add("Charger", "HOLDING3", "Wallhammer, holding.", "interlock/player/combine/voicelines/Charger/overwatch_16.ogg")
Schema.voices.Add("Charger", "EYES ON", "Wallhammer, eyes on.", "interlock/player/combine/voicelines/Charger/overwatch_17.ogg")
Schema.voices.Add("Charger", "CONT LOCKED", "Contaminant is locked.", "interlock/player/combine/voicelines/Charger/overwatch_18.ogg")
Schema.voices.Add("Charger", "SECURING EDGE", "Wallhammer, securing edge.", "interlock/player/combine/voicelines/Charger/overwatch_19.ogg")
Schema.voices.Add("Charger", "CHECKING EDGES", "Checking all edges.", "interlock/player/combine/voicelines/Charger/overwatch_20.ogg")


Schema.voices.Add("Charger", "TARGET HURT", "Hostile is vulnerable.", "interlock/player/combine/voicelines/Charger/playerishurt_01.ogg")
Schema.voices.Add("Charger", "TARGET HURT2", "Target at odds.", "interlock/player/combine/voicelines/Charger/playerishurt_02.ogg")
Schema.voices.Add("Charger", "TARGET HURT3", "Target compromised.", "interlock/player/combine/voicelines/Charger/playerishurt_03.ogg")
Schema.voices.Add("Charger", "MOVE IN2", "Move in, move in!", "interlock/player/combine/voicelines/Charger/playerishurt_04.ogg")
Schema.voices.Add("Charger", "TARGET HURT4", "Contaminant at low value.", "interlock/player/combine/voicelines/Charger/playerishurt_05.ogg")
Schema.voices.Add("Charger", "TARGET HURT5", "Hostile is tagged.", "interlock/player/combine/voicelines/Charger/playerishurt_06.ogg")
Schema.voices.Add("Charger", "TARGET HURT6", "Recall on hostile.", "interlock/player/combine/voicelines/Charger/playerishurt_07.ogg")
Schema.voices.Add("Charger", "AMPLIFY WEAPONS", "Amplify weapons on Wallhammer.", "interlock/player/combine/voicelines/Charger/playerishurt_08.ogg")
Schema.voices.Add("Charger", "TARGET HURT7", "Red leak on hostile.", "interlock/player/combine/voicelines/Charger/playerishurt_09.ogg")
Schema.voices.Add("Charger", "TARGET HURT8", "Possible tag on prime.", "interlock/player/combine/voicelines/Charger/playerishurt_10.ogg")
Schema.voices.Add("Charger", "TARGET HURT9", "Hammer effective, at ZERO-NINER.", "interlock/player/combine/voicelines/Charger/playerishurt_11.ogg")
Schema.voices.Add("Charger", "ENDING TARGET", "Ending target one.", "interlock/player/combine/voicelines/Charger/playerishurt_13.ogg")


Schema.voices.Add("Charger", "BREACH READY", "Hammer ready!", "interlock/player/combine/voicelines/Charger/preparing_charge_01.ogg")
Schema.voices.Add("Charger", "BREACH READY2", "Preparing hammer.", "interlock/player/combine/voicelines/Charger/preparing_charge_02.ogg")
Schema.voices.Add("Charger", "BREACH READY3", "Hammer is ready to charge.", "interlock/player/combine/voicelines/Charger/preparing_charge_03.ogg")
Schema.voices.Add("Charger", "BREACHING", "Charging.", "interlock/player/combine/voicelines/Charger/preparing_charge_04.ogg")
Schema.voices.Add("Charger", "BREACHING AT", "Charging hammer at...", "interlock/player/combine/voicelines/Charger/preparing_charge_05.ogg")
Schema.voices.Add("Charger", "BREACHING COUNT", "Ready to hammer it in three... two... one.", "interlock/player/combine/voicelines/Charger/preparing_charge_06.ogg")


Schema.voices.Add("Charger", "WALL UP", "Wall up!", "interlock/player/combine/voicelines/Charger/preparing_shield_01.ogg")
Schema.voices.Add("Charger", "PREPARING WALL", "Preparing wall.", "interlock/player/combine/voicelines/Charger/preparing_shield_02.ogg")
Schema.voices.Add("Charger", "SHIELD UP", "Shield up.", "interlock/player/combine/voicelines/Charger/preparing_shield_03.ogg")
Schema.voices.Add("Charger", "RAISING WALL", "Raising wall.", "interlock/player/combine/voicelines/Charger/preparing_shield_04.ogg")
Schema.voices.Add("Charger", "WALL IS UP", "Wall is up.", "interlock/player/combine/voicelines/Charger/preparing_shield_05.ogg")
Schema.voices.Add("Charger", "WALL DEPLOYING IN", "Wall is ready to deploy in three... two... one.", "interlock/player/combine/voicelines/Charger/preparing_shield_06.ogg")


Schema.voices.Add("Charger", "SEARCH FINISHED", "All sectors scanned.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_01.ogg")
Schema.voices.Add("Charger", "SEARCH FINISHED2", "Contact is silent.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_02.ogg")
Schema.voices.Add("Charger", "CLEAR2", "Sector clear. Requesting stand by.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_03.ogg")
Schema.voices.Add("Charger", "CLEAR", "Area clear.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_04.ogg")
Schema.voices.Add("Charger", "HOSTILE SILENT", "Wallhammer reporting - hostile is silent.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_05.ogg")
Schema.voices.Add("Charger", "CLEAR3", "No contact.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_06.ogg")
Schema.voices.Add("Charger", "CLEAR4", "Arena secure.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_07.ogg")
Schema.voices.Add("Charger", "CLEAR5", "Looks clean.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_08.ogg")
Schema.voices.Add("Charger", "CONTACT LOST", "Contact lost, looks clear.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_09.ogg")
Schema.voices.Add("Charger", "NOTHING HERE", "Nothing here.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_10.ogg")
Schema.voices.Add("Charger", "STAYING SHARP", "Staying sharp, walls up.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_11.ogg")
Schema.voices.Add("Charger", "INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_12.ogg")
Schema.voices.Add("Charger", "STANDBY BRAVO", "Standby for code bravo.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_13.ogg")
Schema.voices.Add("Charger", "NOTHING", "Nothing.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_14.ogg")
Schema.voices.Add("Charger", "CLEAR6", "Shadow clear.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_15.ogg")
Schema.voices.Add("Charger", "END SHADOW", "Request end on condition shadow.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_16.ogg")
Schema.voices.Add("Charger", "NOT HERE", "Not here.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_18.ogg")
Schema.voices.Add("Charger", "SEARCH FINISHED3", "Location clear. Recall assist.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_19.ogg")
Schema.voices.Add("Charger", "SEARCH FINISHED4", "All sectors clear. Recall.", "interlock/player/combine/voicelines/Charger/reconnoiter_finish_20.ogg")


Schema.voices.Add("Charger", "SEARCHING", "Processing viscon.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_01.ogg")
Schema.voices.Add("Charger", "SEARCHING2", "Still searching.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_02.ogg")
Schema.voices.Add("Charger", "SEARCHING3", "Still sweeping.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_03.ogg")
Schema.voices.Add("Charger", "SEARCHING4", "Still scanning.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_04.ogg")
Schema.voices.Add("Charger", "SEARCHING5", "Wallhammer, recon in progress.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_05.ogg")
Schema.voices.Add("Charger", "SHADOW ACTIVE", "Condition shadow active.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_06.ogg")
Schema.voices.Add("Charger", "SEARCHING6", "Recon in progress.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_07.ogg")
Schema.voices.Add("Charger", "TARGET SHADOW", "Target is still shadow.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_09.ogg")
Schema.voices.Add("Charger", "CLEAR MOVING", "Sector clear, advancing.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_10.ogg")
Schema.voices.Add("Charger", "CLEAR MOVING2", "Null sector, proceeding.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_11.ogg")
Schema.voices.Add("Charger", "CLEAR MOVING3", "Area cleaned, move in.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_12.ogg")
Schema.voices.Add("Charger", "SEARCHING7", "Eyes still active.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_13.ogg")
Schema.voices.Add("Charger", "NOTHING HERE2", "Nothing here.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_14.ogg")
Schema.voices.Add("Charger", "HOSTILE QUIET", "Wallhammer reporting, hostile is still quiet.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_15.ogg")
Schema.voices.Add("Charger", "SEARCHING COMPLETE", "Scanning complete. Resuming.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_16.ogg")
Schema.voices.Add("Charger", "STILL NO VISUAL", "Still no visual.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_17.ogg")
Schema.voices.Add("Charger", "RADIALS CLEAR", "Radials clear, resume.", "interlock/player/combine/voicelines/Charger/reconnoiter_search_18.ogg")


Schema.voices.Add("Charger", "SEARCH START", "Spreading out.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_01.ogg")
Schema.voices.Add("Charger", "SEARCH START2", "Distributing.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_03.ogg")
Schema.voices.Add("Charger", "SEARCH START3", "Wallhammer unit out.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_04.ogg")
Schema.voices.Add("Charger", "SEARCH START4", "Deploying and scanning.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_06.ogg")
Schema.voices.Add("Charger", "COMMENCING CLEANUP", "Commencing cleanup.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_07.ogg")
Schema.voices.Add("Charger", "STAYING ALERT", "Staying alert.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_08.ogg")
Schema.voices.Add("Charger", "SWEEPING HOSTILES", "Sweeping for hostiles.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_09.ogg")
Schema.voices.Add("Charger", "SWEEPING CONTAMINANT", "Sweeping for contaminant.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_10.ogg")
Schema.voices.Add("Charger", "SEARCH DAGGER", "Searching, condition dagger.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_11.ogg")
Schema.voices.Add("Charger", "CLOSING ARENA", "Closing arena.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_12.ogg")
Schema.voices.Add("Charger", "CONTAINMENT PROCEEDING", "Containment proceeding.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_13.ogg")
Schema.voices.Add("Charger", "REPORTING SIGHTLINES", "Reporting sightlines.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_14.ogg")
Schema.voices.Add("Charger", "FORM TARGET IN", "Formation on target in three...", "interlock/player/combine/voicelines/Charger/reconnoiter_start_15.ogg")
Schema.voices.Add("Charger", "PROCEED EXTRACTION", "Proceeding with hostile extraction.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_16.ogg")
Schema.voices.Add("Charger", "INITIATE SHADOW", "Initiate condition shadow.", "interlock/player/combine/voicelines/Charger/reconnoiter_start_17.ogg")


Schema.voices.Add("Charger", "GOING SHARP2", "Going sharp, target delta.", "interlock/player/combine/voicelines/Charger/refindenemy_01.ogg")
Schema.voices.Add("Charger", "CONTACT", "Target contacted.", "interlock/player/combine/voicelines/Charger/refindenemy_02.ogg")
Schema.voices.Add("Charger", "CONTACT2", "Viscon, viscon, range!", "interlock/player/combine/voicelines/Charger/refindenemy_03.ogg")
Schema.voices.Add("Charger", "THERE", "There!", "interlock/player/combine/voicelines/Charger/refindenemy_04.ogg")
Schema.voices.Add("Charger", "CONTACT3", "Viscon, hostile found.", "interlock/player/combine/voicelines/Charger/refindenemy_05.ogg")
Schema.voices.Add("Charger", "OVER THERE", "Over there!", "interlock/player/combine/voicelines/Charger/refindenemy_06.ogg")
Schema.voices.Add("Charger", "MOVEMENT", "We have movement.", "interlock/player/combine/voicelines/Charger/refindenemy_07.ogg")
Schema.voices.Add("Charger", "REFIND", "Animal is back in the pit.", "interlock/player/combine/voicelines/Charger/refindenemy_08.ogg")
Schema.voices.Add("Charger", "CONTACT4", "Ready, hostile contact.", "interlock/player/combine/voicelines/Charger/refindenemy_09.ogg")
Schema.voices.Add("Charger", "REFIND2", "Hostile realigned in sector.", "interlock/player/combine/voicelines/Charger/refindenemy_10.ogg")
Schema.voices.Add("Charger", "REFIND3", "Wallhammer, recontact in sector.", "interlock/player/combine/voicelines/Charger/refindenemy_11.ogg")
Schema.voices.Add("Charger", "CONTACT5", "Hostile live, check radials.", "interlock/player/combine/voicelines/Charger/refindenemy_12.ogg")
Schema.voices.Add("Charger", "CONTACT6", "Additional sightlines confirmed.", "interlock/player/combine/voicelines/Charger/refindenemy_13.ogg")
Schema.voices.Add("Charger", "CONTACT7", "Sightlines confirmed on prime.", "interlock/player/combine/voicelines/Charger/refindenemy_14.ogg")
Schema.voices.Add("Charger", "INTERCEPTING", "Wallhammer intercepting.", "interlock/player/combine/voicelines/Charger/refindenemy_15.ogg")
Schema.voices.Add("Charger", "CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "interlock/player/combine/voicelines/Charger/refindenemy_16.ogg")
Schema.voices.Add("Charger", "VISCON IN 3", "Visual confirmation on three.", "interlock/player/combine/voicelines/Charger/refindenemy_17.ogg")
Schema.voices.Add("Charger", "ACTIVE VISUAL", "Active visual.", "interlock/player/combine/voicelines/Charger/refindenemy_18.ogg")


Schema.voices.Add("Charger", "RELOADING", "Reloading.", "interlock/player/combine/voicelines/Charger/reload_01.ogg")
Schema.voices.Add("Charger", "RELOADING2", "Refill on Wallhammer.", "interlock/player/combine/voicelines/Charger/reload_02.ogg")
Schema.voices.Add("Charger", "RELOADING3", "Wallhammer down on four... three... two... one.", "interlock/player/combine/voicelines/Charger/reload_03.ogg")
Schema.voices.Add("Charger", "RELOADING4", "Recharging.", "interlock/player/combine/voicelines/Charger/reload_05.ogg")
Schema.voices.Add("Charger", "RELOADING5", "Empty.", "interlock/player/combine/voicelines/Charger/reload_06.ogg")
Schema.voices.Add("Charger", "RELOADING6", "Empty on Wallhammer.", "interlock/player/combine/voicelines/Charger/reload_07.ogg")
Schema.voices.Add("Charger", "RELOADING7", "Provision low, reloading.", "interlock/player/combine/voicelines/Charger/reload_08.ogg")
Schema.voices.Add("Charger", "RELOADING8", "Hammer renew.", "interlock/player/combine/voicelines/Charger/reload_09.ogg")


Schema.voices.Add("Charger", "RETREAT", "Ripcord, ripcord!", "interlock/player/combine/voicelines/Charger/retreat_02.ogg")
Schema.voices.Add("Charger", "RETREAT2", "Ripcord on Wallhammer.", "interlock/player/combine/voicelines/Charger/retreat_03.ogg")
Schema.voices.Add("Charger", "RETREAT3", "Retreating.", "interlock/player/combine/voicelines/Charger/retreat_04.ogg")
Schema.voices.Add("Charger", "RETREAT4", "Falling back.", "interlock/player/combine/voicelines/Charger/retreat_05.ogg")
Schema.voices.Add("Charger", "RETREAT5", "Sector is too hot.", "interlock/player/combine/voicelines/Charger/retreat_06.ogg")
Schema.voices.Add("Charger", "RETREAT6", "Finding cover.", "interlock/player/combine/voicelines/Charger/retreat_07.ogg")
Schema.voices.Add("Charger", "RETREAT7", "Wallhammer, regroup.", "interlock/player/combine/voicelines/Charger/retreat_08.ogg")
Schema.voices.Add("Charger", "RETREAT8", "Sector volatile. Finding shade.", "interlock/player/combine/voicelines/Charger/retreat_10.ogg")


Schema.voices.Add("Charger", "MULTIPLE CONTACT", "Secondaries identified.", "interlock/player/combine/voicelines/Charger/sees_company_01.ogg")
Schema.voices.Add("Charger", "MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "interlock/player/combine/voicelines/Charger/sees_company_02.ogg")
Schema.voices.Add("Charger", "MULTIPLE CONTACT3", "Viscon on secondaries.", "interlock/player/combine/voicelines/Charger/sees_company_03.ogg")
Schema.voices.Add("Charger", "MULTIPLE CONTACT4", "Checking silhouettes. Possible multipliers.", "interlock/player/combine/voicelines/Charger/sees_company_04.ogg")
Schema.voices.Add("Charger", "MULTIPLE CONTACT5", "We have multiple contaminants.", "interlock/player/combine/voicelines/Charger/sees_company_05.ogg")


Schema.voices.Add("Charger", "TARGET GRENADES", "Target-One has bouncers.", "interlock/player/combine/voicelines/Charger/sees_grenades_01.ogg")
Schema.voices.Add("Charger", "TARGET GRENADES2", "Hostile has bouncers. Be alert.", "interlock/player/combine/voicelines/Charger/sees_grenades_02.ogg")
Schema.voices.Add("Charger", "TARGET GRENADES3", "Contaminant has grenades. Disperse.", "interlock/player/combine/voicelines/Charger/sees_grenades_03.ogg")
Schema.voices.Add("Charger", "TARGET GRENADES4", "Primary target has extractors. Responder.", "interlock/player/combine/voicelines/Charger/sees_grenades_04.ogg")


Schema.voices.Add("Charger", "TARGET RELOADING", "Hostile reloading, hammer advantage.", "interlock/player/combine/voicelines/Charger/sees_reloading_01.ogg")
Schema.voices.Add("Charger", "TARGET RELOADING2", "Target is regen, open fire.", "interlock/player/combine/voicelines/Charger/sees_reloading_02.ogg")
Schema.voices.Add("Charger", "TARGET RELOADING3", "Taking advantage.", "interlock/player/combine/voicelines/Charger/sees_reloading_03.ogg")
Schema.voices.Add("Charger", "TARGET RELOADING4", "Contaminant is vulnerable.", "interlock/player/combine/voicelines/Charger/sees_reloading_04.ogg")
Schema.voices.Add("Charger", "", "Alyx reloading, full response active.", "interlock/player/combine/voicelines/Charger/sees_reloading_05.ogg")


Schema.voices.Add("Charger", "TARGET UPGRADES", "Spikes boosted on target one.", "interlock/player/combine/voicelines/Charger/sees_upgrades_01.ogg")
Schema.voices.Add("Charger", "TARGET UPGRADES2", "Overwatch, target one has boosters.", "interlock/player/combine/voicelines/Charger/sees_upgrades_02.ogg")
Schema.voices.Add("Charger", "TARGET UPGRADES3", "Hostile spikes are boosted.", "interlock/player/combine/voicelines/Charger/sees_upgrades_03.ogg")
Schema.voices.Add("Charger", "TARGET UPGRADES4", "Hostile has illegal spikes.", "interlock/player/combine/voicelines/Charger/sees_upgrades_04.ogg")
Schema.voices.Add("Charger", "TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "interlock/player/combine/voicelines/Charger/sees_upgrades_05.ogg")


Schema.voices.Add("Charger", "MANDOWN", "Overwatch, request reserve action.", "interlock/player/combine/voicelines/Charger/squadmemberlost_01.ogg")
Schema.voices.Add("Charger", "MANDOWN2", "Overwatch, sector is not secure.", "interlock/player/combine/voicelines/Charger/squadmemberlost_02.ogg")
Schema.voices.Add("Charger", "MANDOWN3", "Outbreak in sector.", "interlock/player/combine/voicelines/Charger/squadmemberlost_03.ogg")
Schema.voices.Add("Charger", "MANDOWN4", "Overwatch, ground team is down, sector not controlled.", "interlock/player/combine/voicelines/Charger/squadmemberlost_05.ogg")
Schema.voices.Add("Charger", "MANDOWN5", "Overwatch, sector is overrun.", "interlock/player/combine/voicelines/Charger/squadmemberlost_06.ogg")
Schema.voices.Add("Charger", "MANDOWN6", "Overwatch, requesting SKYSHIELD.", "interlock/player/combine/voicelines/Charger/squadmemberlost_07.ogg")
Schema.voices.Add("Charger", "MANDOWN7", "Overwatch, recommend new formation.", "interlock/player/combine/voicelines/Charger/squadmemberlost_09.ogg")
Schema.voices.Add("Charger", "MANDOWN8", "Friendly is down.", "interlock/player/combine/voicelines/Charger/squadmemberlost_10.ogg")
Schema.voices.Add("Charger", "X IS QUIET", "...is quiet, requesting replacement", "interlock/player/combine/voicelines/Charger/squadmemberlost_11.ogg")


Schema.voices.Add("Charger", "LAST UNIT", "Overwatch, solo active.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_01.ogg")
Schema.voices.Add("Charger", "LAST UNIT2", "Overwatch, Wallhammer is last unit, requesting assist.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_02.ogg")
Schema.voices.Add("Charger", "LAST UNIT3", "Overwatch, requesting immediate shadow!", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_03.ogg")
Schema.voices.Add("Charger", "LAST UNIT4", "Overwatch, outbreak is uncontained.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_04.ogg")
Schema.voices.Add("Charger", "", "", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_05.ogg")
Schema.voices.Add("Charger", "LAST UNIT5", "Overwatch, solo contact on excessive hostiles.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_06.ogg")
Schema.voices.Add("Charger", "LAST UNIT6", "Survival mark deployed.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_07.ogg")
Schema.voices.Add("Charger", "LAST UNIT7", "Overwatch, requesting extraction on Wallhammer.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_08.ogg")
Schema.voices.Add("Charger", "LAST UNIT8", "Overwatch, be informed, Wallhammer is last responder.", "interlock/player/combine/voicelines/Charger/squadmemberlost_lastman_09.ogg")


Schema.voices.Add("Charger", "LEADER DOWN", "Overwatch, Ordinal is down.", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_01.ogg")
Schema.voices.Add("Charger", "LEADER DOWN2", "Ordinal is quiet, requesting new leader.", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_02.ogg")
Schema.voices.Add("Charger", "LEADER DOWN3", "Ordinal is condition SUNDOWN.", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_03.ogg")
Schema.voices.Add("Charger", "", "", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_04.ogg")
Schema.voices.Add("Charger", "LEADER DOWN4", "Overwatch, Ordinal is out. Respond.", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_05.ogg")
Schema.voices.Add("Charger", "LEADER DOWN5", "Ordinal silent, administer full response.", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_06.ogg")
Schema.voices.Add("Charger", "LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "interlock/player/combine/voicelines/Charger/squadmemberlost_leader_07.ogg")


Schema.voices.Add("Charger", "SWITCHING", "Switching.", "interlock/player/combine/voicelines/Charger/switching_weapons_01.ogg")
Schema.voices.Add("Charger", "SWITCHING2", "Swapping.", "interlock/player/combine/voicelines/Charger/switching_weapons_02.ogg")
Schema.voices.Add("Charger", "", "", "interlock/player/combine/voicelines/Charger/switching_weapons_03.ogg")


Schema.voices.Add("Charger", "SPIKES CLOSE", "Spikes close, no damage.", "interlock/player/combine/voicelines/Charger/takingfire_01.ogg")
Schema.voices.Add("Charger", "TAKING FIRE2", "Missed.", "interlock/player/combine/voicelines/Charger/takingfire_02.ogg")
Schema.voices.Add("Charger", "TAKING FIRE3", "Target error, take advantage.", "interlock/player/combine/voicelines/Charger/takingfire_03.ogg")
Schema.voices.Add("Charger", "TAKING FIRE4", "Hostile is inaccurate.", "interlock/player/combine/voicelines/Charger/takingfire_04.ogg")
Schema.voices.Add("Charger", "TAKING FIRE5", "Almost.", "interlock/player/combine/voicelines/Charger/takingfire_05.ogg")
Schema.voices.Add("Charger", "TAKING FIRE6", "Wallhammer is untouched.", "interlock/player/combine/voicelines/Charger/takingfire_06.ogg")
Schema.voices.Add("Charger", "TAKING FIRE7", "Missed again, taking advantage.", "interlock/player/combine/voicelines/Charger/takingfire_07.ogg")
Schema.voices.Add("Charger", "TAKING FIRE8", "Target has failed.", "interlock/player/combine/voicelines/Charger/takingfire_08.ogg")
Schema.voices.Add("Charger", "TAKING FIRE9", "Exercise advantage on hostile.", "interlock/player/combine/voicelines/Charger/takingfire_09.ogg")
Schema.voices.Add("Charger", "HOSTILE FAILED", "Hostile failed, reforming.", "interlock/player/combine/voicelines/Charger/takingfire_10.ogg")
Schema.voices.Add("Charger", "TAUNT", "Spikes ineffective. Target is unskilled.", "interlock/player/combine/voicelines/Charger/takingfire_11.ogg")


Schema.voices.Add("Charger", "TAUNT2", "Hostile is experiencing extreme panic.", "interlock/player/combine/voicelines/Charger/taunt_010.ogg")
Schema.voices.Add("Charger", "TAUNT3", "Hostile is overwhelmed.", "interlock/player/combine/voicelines/Charger/taunt_020.ogg")
Schema.voices.Add("Charger", "TAUNT4", "Target is at low motivation, take advantage.", "interlock/player/combine/voicelines/Charger/taunt_030.ogg")
Schema.voices.Add("Charger", "TAUNT5", "Target is at low motivation.", "interlock/player/combine/voicelines/Charger/taunt_031.ogg")
Schema.voices.Add("Charger", "YOU CAN COME OUT", "You can come out now!", "interlock/player/combine/voicelines/Charger/taunt_042.ogg")
Schema.voices.Add("Charger", "WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "interlock/player/combine/voicelines/Charger/taunt_050.ogg")
Schema.voices.Add("Charger", "WE CAN HELP YOU", "We can help you, it is safe.", "interlock/player/combine/voicelines/Charger/taunt_051.ogg")
Schema.voices.Add("Charger", "TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "interlock/player/combine/voicelines/Charger/taunt_060.ogg")
Schema.voices.Add("Charger", "ESCALATING2", "Proceeding with escalation.", "interlock/player/combine/voicelines/Charger/taunt_070.ogg")
Schema.voices.Add("Charger", "NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "interlock/player/combine/voicelines/Charger/taunt_071.ogg")
Schema.voices.Add("Charger", "ESCALATING3", "Code 10-307, proceeding with escalation.", "interlock/player/combine/voicelines/Charger/taunt_072.ogg")
Schema.voices.Add("Charger", "TAUNT7", "Hostile is hesitating.", "interlock/player/combine/voicelines/Charger/taunt_081.ogg")
Schema.voices.Add("Charger", "TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "interlock/player/combine/voicelines/Charger/taunt_090.ogg")
Schema.voices.Add("Charger", "STANDING DOWN2", "Activating code 10-108, standing down.", "interlock/player/combine/voicelines/Charger/taunt_100.ogg")
Schema.voices.Add("Charger", "SUSPEND FIRE", "Suspend fire, target is friendly.", "interlock/player/combine/voicelines/Charger/taunt_111.ogg")
Schema.voices.Add("Charger", "STANDING DOWN3", "Standing down, code 10-40.", "interlock/player/combine/voicelines/Charger/taunt_120.ogg")
Schema.voices.Add("Charger", "CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "interlock/player/combine/voicelines/Charger/taunt_131.ogg")
Schema.voices.Add("Charger", "DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "interlock/player/combine/voicelines/Charger/taunt_140.ogg")
Schema.voices.Add("Charger", "FRIENDLY2", "Target is friendly.", "interlock/player/combine/voicelines/Charger/taunt_150.ogg")
Schema.voices.Add("Charger", "FRIENDLY3", "Stand down, target is friendly.", "interlock/player/combine/voicelines/Charger/taunt_151.ogg")
Schema.voices.Add("Charger", "FRIENDLY4", "All units stand down, target is friendly.", "interlock/player/combine/voicelines/Charger/taunt_152.ogg")
Schema.voices.Add("Charger", "FRIENDLY5", "Friendly confirmed, cease fire.", "interlock/player/combine/voicelines/Charger/taunt_160.ogg")
Schema.voices.Add("Charger", "WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "interlock/player/combine/voicelines/Charger/taunt_170.ogg")
Schema.voices.Add("Charger", "WAIT AND SEE", "Overwatch, we have a wait and see.", "interlock/player/combine/voicelines/Charger/taunt_171.ogg")
Schema.voices.Add("Charger", "INJURED7", "Affirmative, target is low value.", "interlock/player/combine/voicelines/Charger/taunt_182.ogg")
Schema.voices.Add("Charger", "HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "interlock/player/combine/voicelines/Charger/taunt_191.ogg")
Schema.voices.Add("Charger", "INJURED8", "Hostile is showing fatigue. Prepare containment.", "interlock/player/combine/voicelines/Charger/taunt_200.ogg")


Schema.voices.Add("Charger", "NEGATIVE", "Negative.", "interlock/player/combine/voicelines/Charger/unabletocommence_01.ogg")
Schema.voices.Add("Charger", "NEGATORY", "Negatory.", "interlock/player/combine/voicelines/Charger/unabletocommence_02.ogg")
Schema.voices.Add("Charger", "NO", "No.", "interlock/player/combine/voicelines/Charger/unabletocommence_03.ogg")
Schema.voices.Add("Charger", "CANT COMPLY", "Can't comply.", "interlock/player/combine/voicelines/Charger/unabletocommence_04.ogg")
Schema.voices.Add("Charger", "DENIED", "Denied.", "interlock/player/combine/voicelines/Charger/unabletocommence_05.ogg")
Schema.voices.Add("Charger", "NEGATIVE2", "That's a negative.", "interlock/player/combine/voicelines/Charger/unabletocommence_06.ogg")
Schema.voices.Add("Charger", "CAN NOT EXECUTE", "Can not execute.", "interlock/player/combine/voicelines/Charger/unabletocommence_07.ogg")


Schema.voices.Add("Charger", "UNDERFIRE", "Spikes confirmation, wall up.", "interlock/player/combine/voicelines/Charger/underattack_01.ogg")
Schema.voices.Add("Charger", "UNDERFIRE2", "Hostile is live.", "interlock/player/combine/voicelines/Charger/underattack_02.ogg")
Schema.voices.Add("Charger", "UNDERFIRE3", "Contact!", "interlock/player/combine/voicelines/Charger/underattack_03.ogg")
Schema.voices.Add("Charger", "UNDERFIRE4", "Wallhammer, returing with pressure.", "interlock/player/combine/voicelines/Charger/underattack_04.ogg")
Schema.voices.Add("Charger", "UNDERFIRE5", "We have live contaminants.", "interlock/player/combine/voicelines/Charger/underattack_05.ogg")
Schema.voices.Add("Charger", "UNDERFIRE6", "Distribute.", "interlock/player/combine/voicelines/Charger/underattack_06.ogg")
Schema.voices.Add("Charger", "UNDERFIRE7", "Target is hostile, daggers free.", "interlock/player/combine/voicelines/Charger/underattack_07.ogg")
Schema.voices.Add("Charger", "UNDERFIRE8", "Hostile suppressing, responder on.", "interlock/player/combine/voicelines/Charger/underattack_08.ogg")
Schema.voices.Add("Charger", "UNDERFIRE9", "Overwatch, we have spikes.", "interlock/player/combine/voicelines/Charger/underattack_09.ogg")
Schema.voices.Add("Charger", "CONDITION DELTA", "Preparing condition delta.", "interlock/player/combine/voicelines/Charger/underattack_10.ogg")
Schema.voices.Add("Charger", "TAKING FIRE", "Taking fire.", "interlock/player/combine/voicelines/Charger/underattack_11.ogg")
Schema.voices.Add("Charger", "EXECUTING RESPONSE", "Executing full response.", "interlock/player/combine/voicelines/Charger/underattack_12.ogg")

Schema.voices.AddClass("Charger", function(ply)
    return ( ply:Team() == FACTION_OTA ) and ( ply:GetModel():find("heavy") )
end)