Schema.voices.Add("Dispatch", "ACTIVITY LEVEL 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CITIZEN", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "ANTI-CIVIL EVIDENCE", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "ARE CHARGED WITH", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "ASSUME POSITIONS", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "AUTONOMOUS JUDGEMENT", "Attention, all ground-protection teams, Autonomous Judgement is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "CITIZEN RELOCATION", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONSPIRACY", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "CONVICTED", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "DEDUCTED", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "EVASION BEHAVIOR", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "INDIVIDUAL CHARGED WITH", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "INSPECTION", "Citizen notice, Priority Identification-Check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "JUDGEMENT WAIVER", "Attention, all ground-protection teams, Judgement Waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISCOUNT DETECTED", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "MISSION FAILURE", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "OVERWATCH ACKNOWLEDGES", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "POTENTIAL INFECTION", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "RECEIVE YOUR VERDICT", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "STATUS EVASION", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNIDENTIFIED", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST PROCEDURE", "Attention, community: Unrest Procedure Code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "UNREST STRUCTURE", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)

Schema.voices.Add("Dispatch", "07_10000", "Alert. Ground units. Invasive operation of anti-citizen origin. Response code: Engage. Quell. Inquire.", "interlock/dispatch/07_10000.ogg", true)
Schema.voices.Add("Dispatch", "07_10001", "Alert. Response units. Update code: Flush. Escort. Continue.", "interlock/dispatch/07_10001.ogg", true)
Schema.voices.Add("Dispatch", "07_10002", "Citizen Reminder: a civilized society demands swift and targeted oversight. Prohibit fellow citizens from threatening the community.", "interlock/dispatch/07_10002.ogg", true)
Schema.voices.Add("Dispatch", "07_10003", "Ground Protection Team: alert. Incident response deployment required. Nine-two-one-two.", "interlock/dispatch/07_10003.ogg", true)
Schema.voices.Add("Dispatch", "07_10004", "Attention please. Access to this block is not permitted. To receive this message is to be in civil code violation.", "interlock/dispatch/07_10004.ogg", true)
Schema.voices.Add("Dispatch", "07_10005", "Attention please. Access to this block is not permitted. Local security deployed and designated to prosecute.", "interlock/dispatch/07_10005.ogg", true)
Schema.voices.Add("Dispatch", "07_10006", "Attention please. Access is not permitted. Anti-citizen scavenging will result in immediate capital prosecution.", "interlock/dispatch/07_10006.ogg", true)
Schema.voices.Add("Dispatch", "07_10007", "Alert ground units. Alert command units. Emergency Code: Void.", "interlock/dispatch/07_10007.ogg", true)
Schema.voices.Add("Dispatch", "07_10008", "Security alert. Re-administration in progress. Asset allocation adjustment code: Flint. Inspect. Extirpate. Priority: immediate.", "interlock/dispatch/07_10008.ogg", true)
Schema.voices.Add("Dispatch", "07_10009", "Security alert. Critical civil insurrection. Deploy technician teams to Blocks 49, 64, 77. Maintain priority.", "interlock/dispatch/07_10009.ogg", true)
Schema.voices.Add("Dispatch", "07_10010", "Security alert. Reminder, ground teams: Mission failure will result in permanent relocation. Response code: Breach. Maneuver. Inoculate.", "interlock/dispatch/07_10010.ogg", true)
Schema.voices.Add("Dispatch", "07_10011", "Critical breach. Stand by. Stand by.", "interlock/dispatch/07_10011.ogg", true)
Schema.voices.Add("Dispatch", "07_10012", "Full system alert. Operation engagement five-one-two-nine. Immediate, concurrent deployment. Five-one-two-nine.", "interlock/dispatch/07_10012.ogg", true)
Schema.voices.Add("Dispatch", "07_10013", "Response code: Shield. Key. Migrate.", "interlock/dispatch/07_10013.ogg", true)
Schema.voices.Add("Dispatch", "07_10014", "Alert. Response team. Overload protocol: Angle. Cauterize. Flash. Angle. Cauterize. Flash.", "interlock/dispatch/07_10014.ogg", true)
Schema.voices.Add("Dispatch", "07_10015", "Overwatch acknowledges activity. Confirm sector zero-two, possible necrotic interference. Sweep sector, report containment status.", "interlock/dispatch/07_10015.ogg", true)
Schema.voices.Add("Dispatch", "07_10016", "Converge sector station one, weapons free. Target has been designated as primary one objective. Prosecute on sight.", "interlock/dispatch/07_10016.ogg", true)
Schema.voices.Add("Dispatch", "07_10017", "Individual, you are now charged with multiple level five anti-civil activity violations. Please cooperate with ground protection team. Ground protection team: alert. Code: Engage. Isolate. Neutralize.", "interlock/dispatch/07_10017.ogg", true)
Schema.voices.Add("Dispatch", "07_10018", "Overwatch acknowledges containment failure. Hold for reinforcement. Suppressor inbound.", "interlock/dispatch/07_10018.ogg", true)

Schema.voices.AddClass("Dispatch", function(ply)
   return ( ply:IsDispatch() )
end)
