Schema.voices.Add("Suppressor", "MOVE IN", "Move in.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_01.ogg")
Schema.voices.Add("Suppressor", "MOVING1", "Moving now.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_02.ogg")
Schema.voices.Add("Suppressor", "MOVING2", "Pressing.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_03.ogg")
Schema.voices.Add("Suppressor", "APPROACHING1", "Approaching target.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_04.ogg")
Schema.voices.Add("Suppressor", "PRESSURE", "Pressure.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_05.ogg")
Schema.voices.Add("Suppressor", "MOVING3", "Proceeding on infected.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_06.ogg")
Schema.voices.Add("Suppressor", "MOVING4", "APF closing in..", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_07.ogg")
Schema.voices.Add("Suppressor", "PUSHING1", "Pushing forward.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_08.ogg")
Schema.voices.Add("Suppressor", "MOVING5", "Sweeping in.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_09.ogg")
Schema.voices.Add("Suppressor", "COPY MOVING", "Moving on contaminant.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_10.ogg")
Schema.voices.Add("Suppressor", "PRESSURE2", "Pressure, pressure!", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_11.ogg")
Schema.voices.Add("Suppressor", "PRESSURE3", "Stabalization teams, forward pressure.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_12.ogg")
Schema.voices.Add("Suppressor", "MOVING6", "Commencing on infected.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_13.ogg")
Schema.voices.Add("Suppressor", "PUSHING2", "Pushing.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_14.ogg")
Schema.voices.Add("Suppressor", "MOVING7", "Stablization Team has sector ID and is moving on infected.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_15.ogg")
Schema.voices.Add("Suppressor", "APF INBOUND", "APF unit is inbound.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_16.ogg")
Schema.voices.Add("Suppressor", "APPROACHING2", "Approaching contaminant.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_17.ogg")
Schema.voices.Add("Suppressor", "ADVANCING1", "APF, advancing on target.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_18.ogg")
Schema.voices.Add("Suppressor", "ADVANCING2", "APF, advancing.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_19.ogg")
Schema.voices.Add("Suppressor", "PUSHING4", "APF, pushing.", "interlock/player/combine/voicelines/Suppressor/advancing_on_target_20.ogg")


Schema.voices.Add("Suppressor", "ATTACKING1", "Going sharp.", "interlock/player/combine/voicelines/Suppressor/announceattack_01.ogg")
Schema.voices.Add("Suppressor", "ATTACKING2", "Engaging.", "interlock/player/combine/voicelines/Suppressor/announceattack_02.ogg")
Schema.voices.Add("Suppressor", "ATTACKING3", "Target engaged.", "interlock/player/combine/voicelines/Suppressor/announceattack_03.ogg")
Schema.voices.Add("Suppressor", "ATTACKING5", "APF suppressing.", "interlock/player/combine/voicelines/Suppressor/announceattack_04.ogg")
Schema.voices.Add("Suppressor", "ATTACKING4", "APF engaging.", "interlock/player/combine/voicelines/Suppressor/announceattack_05.ogg")
Schema.voices.Add("Suppressor", "ATTACKING6", "Execute full response.", "interlock/player/combine/voicelines/Suppressor/announceattack_06.ogg")
Schema.voices.Add("Suppressor", "TAKING ADVANTAGE", "Taking advantage.", "interlock/player/combine/voicelines/Suppressor/announceattack_08.ogg")
Schema.voices.Add("Suppressor", "WEAPONS FREE2", "Target locked, dagger out.", "interlock/player/combine/voicelines/Suppressor/announceattack_09.ogg")


Schema.voices.Add("Suppressor", "TARGET ONE", "Oppressing target one.", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_01.ogg")
Schema.voices.Add("Suppressor", "", "Disinfecting primary target.", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_02.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_04.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_06.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_07.ogg")
Schema.voices.Add("Suppressor", "", "Weapons free on Target-One.", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_08.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_09.ogg")
Schema.voices.Add("Suppressor", "", "Engaging target one.", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_10.ogg")
Schema.voices.Add("Suppressor", "CONFIRMED1", "Primary confirmed.", "interlock/player/combine/voicelines/Suppressor/announceattack_alyx_11.ogg")


Schema.voices.Add("Suppressor", "BREAK COVER1", "Breaking cover.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_01.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER2", "Engaging target. Code breakdown.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_02.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER3", "Designate target cover as shadow.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_03.ogg")
Schema.voices.Add("Suppressor", "BREAKING COVER IN", "Exposing hostile in three...", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_04.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER4", "Target is protected. Rectifying.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_05.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER5", "APF, removing support.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_06.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER6", "APF, daggers on cover.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_07.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER7", "Full-active on target cover.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_08.ogg")
Schema.voices.Add("Suppressor", "BREAK COVER8", "Going sharp on cover.", "interlock/player/combine/voicelines/Suppressor/announceattack_cover_09.ogg")


Schema.voices.Add("Suppressor", "GRENADE OUT1", "Bouncer out.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_01.ogg")
Schema.voices.Add("Suppressor", "GRENADE OUT2", "Grenade out.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_02.ogg")
Schema.voices.Add("Suppressor", "GRENADE OUT3", "Extractor away.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_03.ogg")
Schema.voices.Add("Suppressor", "GRENADE1", "Bouncer, bouncer!", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_04.ogg")
Schema.voices.Add("Suppressor", "GET DOWN", "Get down!", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_05.ogg")
Schema.voices.Add("Suppressor", "GRENADE IN", "Bouncer on three...", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_06.ogg")
Schema.voices.Add("Suppressor", "GRENADE OUT4", "Extracting.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_07.ogg")
Schema.voices.Add("Suppressor", "GRENADE OUT5", "Deploying grenade.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_08.ogg")
Schema.voices.Add("Suppressor", "STANDING BACK", "Standing back.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_09.ogg")
Schema.voices.Add("Suppressor", "GRENADE OUT6", "Bouncer free.", "interlock/player/combine/voicelines/Suppressor/announceattack_grenade_10.ogg")


Schema.voices.Add("Suppressor", "ANTLION1", "Antlion.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_01.ogg")
Schema.voices.Add("Suppressor", "ANTLION2", "Target, antlion.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_02.ogg")
Schema.voices.Add("Suppressor", "ANTLION3", "Contact, antlion.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_03.ogg")
Schema.voices.Add("Suppressor", "ANTLION4", "Antlion incoming.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_04.ogg")
Schema.voices.Add("Suppressor", "ANTLION7", "Contact, antlion.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_05.ogg")
Schema.voices.Add("Suppressor", "ANTLION5", "APF, viscon on antlion.", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_06.ogg")
Schema.voices.Add("Suppressor", "ANTLION6", "Antlion, APF engage!", "interlock/player/combine/voicelines/Suppressor/announceenemy_antlion_07.ogg")


Schema.voices.Add("Suppressor", "HEADCRAB1", "Parasitics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_01.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB2", "Call contact, parasitics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_02.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB3", "Parasitics, inbound.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_03.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB4", "APF, visual on parasitics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_04.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB5", "Contact, parasitics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_05.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB6", "We've got parasitics over here.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_07.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB7", "Live parasitics at sector.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_08.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB8", "Parasitic infestation confirmed.", "interlock/player/combine/voicelines/Suppressor/announceenemy_headcrabs_10.ogg")


Schema.voices.Add("Suppressor", "ZOMBIE1", "Necrotics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_01.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE2", "Necrotics inbound.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_02.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE3", "Infestation alert.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_03.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE4", "APF, visual on necrotics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_04.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE5", "Contact, necrotics.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_05.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE7", "Necrotics active.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_08.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE8", "Necrotics, viscon.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_09.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE9", "Necrotics here.", "interlock/player/combine/voicelines/Suppressor/announceenemy_zombie_10.ogg")


Schema.voices.Add("Suppressor", "DEAD1", "Hostile down.", "interlock/player/combine/voicelines/Suppressor/announcekill_01.ogg")
Schema.voices.Add("Suppressor", "DEAD2", "Target down.", "interlock/player/combine/voicelines/Suppressor/announcekill_02.ogg")
Schema.voices.Add("Suppressor", "DEAD3", "Kill confirmed.", "interlock/player/combine/voicelines/Suppressor/announcekill_03.ogg")
Schema.voices.Add("Suppressor", "DEAD4", "Clean kill.", "interlock/player/combine/voicelines/Suppressor/announcekill_04.ogg")
Schema.voices.Add("Suppressor", "DEAD5", "Another one down.", "interlock/player/combine/voicelines/Suppressor/announcekill_05.ogg")
Schema.voices.Add("Suppressor", "DEAD6", "That's it.", "interlock/player/combine/voicelines/Suppressor/announcekill_06.ogg")
Schema.voices.Add("Suppressor", "DEAD7", "Contact down.", "interlock/player/combine/voicelines/Suppressor/announcekill_09.ogg")
Schema.voices.Add("Suppressor", "DEAD8", "Hostile is silent.", "interlock/player/combine/voicelines/Suppressor/announcekill_11.ogg")
Schema.voices.Add("Suppressor", "DEAD9", "APF confirming kill.", "interlock/player/combine/voicelines/Suppressor/announcekill_12.ogg")
Schema.voices.Add("Suppressor", "DEAD10", "Hostile neutralized.", "interlock/player/combine/voicelines/Suppressor/announcekill_13.ogg")
Schema.voices.Add("Suppressor", "DEAD11", "It's done.", "interlock/player/combine/voicelines/Suppressor/announcekill_14.ogg")
Schema.voices.Add("Suppressor", "DEAD12", "Hostile is over.", "interlock/player/combine/voicelines/Suppressor/announcekill_15.ogg")


Schema.voices.Add("Suppressor", "ANTLION DEAD1", "Virome down.", "interlock/player/combine/voicelines/Suppressor/announcekill_antlion_01.ogg")
Schema.voices.Add("Suppressor", "ANTLION DEAD2", "Cleaned.", "interlock/player/combine/voicelines/Suppressor/announcekill_antlion_02.ogg")
Schema.voices.Add("Suppressor", "ANTLION DEAD3", "Target sterilized.", "interlock/player/combine/voicelines/Suppressor/announcekill_antlion_03.ogg")
Schema.voices.Add("Suppressor", "ANTLION DEAD4", "Cleaned.", "interlock/player/combine/voicelines/Suppressor/announcekill_antlion_04.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD9", "Parasitics contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_antlion_05.ogg")


Schema.voices.Add("Suppressor", "HEADCRAB DEAD1", "Clean.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_01.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD2", "Sector clean.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_02.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD3", "That's one.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_03.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD4", "Contaminant contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_04.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD5", "Cleaned.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_05.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD6", "Outbreak ineffective.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_07.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD7", "Outbreak contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_08.ogg")
Schema.voices.Add("Suppressor", "HEADCRAB DEAD8", "Parasitic vacated.", "interlock/player/combine/voicelines/Suppressor/announcekill_headcrab_09.ogg")


Schema.voices.Add("Suppressor", "TARGET DEAD1", "HVT is contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_01.ogg")
Schema.voices.Add("Suppressor", "TARGET DEAD2", "Ordinal, target one is quiet.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_02.ogg")
Schema.voices.Add("Suppressor", "SHES QUIET", "She's quiet.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_03.ogg")
Schema.voices.Add("Suppressor", "", "Ordinal, Alyx is over.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_04.ogg")
Schema.voices.Add("Suppressor", "", "Alyx secure.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_05.ogg")
Schema.voices.Add("Suppressor", "", "Alyx delivered.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_06.ogg")
Schema.voices.Add("Suppressor", "ELIMINATED", "Problem eliminated.", "interlock/player/combine/voicelines/Suppressor/announcekill_player_08.ogg")


Schema.voices.Add("Suppressor", "ZOMBIE DEAD1", "Necro contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_01.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD2", "Necrotic contained.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_02.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD3", "Stay dead.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_03.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD4", "Contaminant eliminated.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_04.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD5", "Necrotic is silent.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_05.ogg")
Schema.voices.Add("Suppressor", "ITS DEAD", "It's dead.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_06.ogg")
Schema.voices.Add("Suppressor", "ZOMBIE DEAD6", "Cleanse successful.", "interlock/player/combine/voicelines/Suppressor/announcekill_zombie_07.ogg")


Schema.voices.Add("Suppressor", "ALPHA", "Alpha.", "interlock/player/combine/voicelines/Suppressor/calloutcode_alpha_01.ogg")
Schema.voices.Add("Suppressor", "AND", "And.", "interlock/player/combine/voicelines/Suppressor/calloutcode_and_01.ogg")
Schema.voices.Add("Suppressor", "BRAVO", "Bravo.", "interlock/player/combine/voicelines/Suppressor/calloutcode_bravo_01.ogg")
Schema.voices.Add("Suppressor", "CHARLIE", "Charlie.", "interlock/player/combine/voicelines/Suppressor/calloutcode_charlie_01.ogg")
Schema.voices.Add("Suppressor", "DELTA", "Delta.", "interlock/player/combine/voicelines/Suppressor/calloutcode_delta_01.ogg")
Schema.voices.Add("Suppressor", "DASH", "Dash.", "interlock/player/combine/voicelines/Suppressor/calloutcode_dash_01.ogg")
Schema.voices.Add("Suppressor", "ECHO", "Echo.", "interlock/player/combine/voicelines/Suppressor/calloutcode_echo_01.ogg")
Schema.voices.Add("Suppressor", "EIGHT", "Eight.", "interlock/player/combine/voicelines/Suppressor/calloutcode_eight_01.ogg")
Schema.voices.Add("Suppressor", "8", "Eight.", "interlock/player/combine/voicelines/Suppressor/calloutcode_eight_01.ogg")
Schema.voices.Add("Suppressor", "ELEVEN", "Eleven.", "interlock/player/combine/voicelines/Suppressor/calloutcode_eleven_01.ogg")
Schema.voices.Add("Suppressor", "11", "Eleven.", "interlock/player/combine/voicelines/Suppressor/calloutcode_eleven_01.ogg")
Schema.voices.Add("Suppressor", "FIFTY", "Fifty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_fifty_01.ogg")
Schema.voices.Add("Suppressor", "50", "Fifty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_fifty_01.ogg")
Schema.voices.Add("Suppressor", "FIVE", "Five.", "interlock/player/combine/voicelines/Suppressor/calloutcode_five_01.ogg")
Schema.voices.Add("Suppressor", "5", "Five.", "interlock/player/combine/voicelines/Suppressor/calloutcode_five_01.ogg")
Schema.voices.Add("Suppressor", "FOURTY", "Fourty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_forty_01.ogg")
Schema.voices.Add("Suppressor", "FORTY", "Fourty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_forty_01.ogg")
Schema.voices.Add("Suppressor", "40", "Fourty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_forty_01.ogg")
Schema.voices.Add("Suppressor", "FOUR", "Four.", "interlock/player/combine/voicelines/Suppressor/calloutcode_four_01.ogg")
Schema.voices.Add("Suppressor", "4", "Four.", "interlock/player/combine/voicelines/Suppressor/calloutcode_four_01.ogg")
Schema.voices.Add("Suppressor", "HUNDRED", "Hundred.", "interlock/player/combine/voicelines/Suppressor/calloutcode_hundred_01.ogg")
Schema.voices.Add("Suppressor", "NINER", "Niner.", "interlock/player/combine/voicelines/Suppressor/calloutcode_niner_01.ogg")
Schema.voices.Add("Suppressor", "9", "Niner.", "interlock/player/combine/voicelines/Suppressor/calloutcode_niner_01.ogg")
Schema.voices.Add("Suppressor", "NULL", "Null.", "interlock/player/combine/voicelines/Suppressor/calloutcode_null_01.ogg")
Schema.voices.Add("Suppressor", "ONE", "One.", "interlock/player/combine/voicelines/Suppressor/calloutcode_one_01.ogg")
Schema.voices.Add("Suppressor", "1", "One.", "interlock/player/combine/voicelines/Suppressor/calloutcode_one_01.ogg")
Schema.voices.Add("Suppressor", "SECTOR", "Sector.", "interlock/player/combine/voicelines/Suppressor/calloutcode_sector_01.ogg")
Schema.voices.Add("Suppressor", "SEVEN", "Seven.", "interlock/player/combine/voicelines/Suppressor/calloutcode_seven_01.ogg")
Schema.voices.Add("Suppressor", "7", "Seven.", "interlock/player/combine/voicelines/Suppressor/calloutcode_seven_01.ogg")
Schema.voices.Add("Suppressor", "SEVENTY", "Seventy.", "interlock/player/combine/voicelines/Suppressor/calloutcode_seventy_01.ogg")
Schema.voices.Add("Suppressor", "70", "Seventy.", "interlock/player/combine/voicelines/Suppressor/calloutcode_seventy_01.ogg")
Schema.voices.Add("Suppressor", "SIX", "Six.", "interlock/player/combine/voicelines/Suppressor/calloutcode_six_01.ogg")
Schema.voices.Add("Suppressor", "6", "Six.", "interlock/player/combine/voicelines/Suppressor/calloutcode_six_01.ogg")
Schema.voices.Add("Suppressor", "SIXTY", "Sixty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_sixty_01.ogg")
Schema.voices.Add("Suppressor", "60", "Sixty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_sixty_01.ogg")
Schema.voices.Add("Suppressor", "TEN", "Ten.", "interlock/player/combine/voicelines/Suppressor/calloutcode_ten_01.ogg")
Schema.voices.Add("Suppressor", "10", "Ten.", "interlock/player/combine/voicelines/Suppressor/calloutcode_ten_01.ogg")
Schema.voices.Add("Suppressor", "THIRTY", "Thirty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_thirty_01.ogg")
Schema.voices.Add("Suppressor", "30", "Thirty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_thirty_01.ogg")
Schema.voices.Add("Suppressor", "THOUSAND", "Thousand.", "interlock/player/combine/voicelines/Suppressor/calloutcode_thousand_01.ogg")
Schema.voices.Add("Suppressor", "THREE", "Three.", "interlock/player/combine/voicelines/Suppressor/calloutcode_three_01.ogg")
Schema.voices.Add("Suppressor", "3", "Three.", "interlock/player/combine/voicelines/Suppressor/calloutcode_three_01.ogg")
Schema.voices.Add("Suppressor", "TWENTY", "Twenty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_twenty_01.ogg")
Schema.voices.Add("Suppressor", "20", "Twenty.", "interlock/player/combine/voicelines/Suppressor/calloutcode_twenty_01.ogg")
Schema.voices.Add("Suppressor", "TWO", "Two.", "interlock/player/combine/voicelines/Suppressor/calloutcode_two_01.ogg")
Schema.voices.Add("Suppressor", "2", "Two.", "interlock/player/combine/voicelines/Suppressor/calloutcode_two_01.ogg")


Schema.voices.Add("Suppressor", "", "Alyx.", "interlock/player/combine/voicelines/Suppressor/calloutentity_alyx_01.ogg")
Schema.voices.Add("Suppressor", "ANTICITIZENS", "Anti-citizens.", "interlock/player/combine/voicelines/Suppressor/calloutentity_anticitizens_01.ogg")
Schema.voices.Add("Suppressor", "ANTLION", "Antlion.", "interlock/player/combine/voicelines/Suppressor/calloutentity_antlion_01.ogg")
Schema.voices.Add("Suppressor", "APF", "APF.", "interlock/player/combine/voicelines/Suppressor/calloutentity_apf_01.ogg")
Schema.voices.Add("Suppressor", "BLADEWALL", "Bladewall.", "interlock/player/combine/voicelines/Suppressor/calloutentity_bladewall_01.ogg")
Schema.voices.Add("Suppressor", "COWALL", "Co-wall.", "interlock/player/combine/voicelines/Suppressor/calloutentity_cowall_01.ogg")
Schema.voices.Add("Suppressor", "FRIENDLY", "Friendly.", "interlock/player/combine/voicelines/Suppressor/calloutentity_friendly_01.ogg")
Schema.voices.Add("Suppressor", "HAMMERWALL", "Hammerwall.", "interlock/player/combine/voicelines/Suppressor/calloutentity_hammerwall_01.ogg")
Schema.voices.Add("Suppressor", "HOSTILES", "Hostiles.", "interlock/player/combine/voicelines/Suppressor/calloutentity_hostiles_01.ogg")
Schema.voices.Add("Suppressor", "3 PARASITICS", "Three parasitics.", "interlock/player/combine/voicelines/Suppressor/calloutentity_manyparasitics_01.ogg")
Schema.voices.Add("Suppressor", "NECROTIC", "Necrotic.", "interlock/player/combine/voicelines/Suppressor/calloutentity_necrotic_01.ogg")
Schema.voices.Add("Suppressor", "PARASITIC", "Parasitic.", "interlock/player/combine/voicelines/Suppressor/calloutentity_parasitic_01.ogg")
Schema.voices.Add("Suppressor", "SAFEMAN", "Safeman.", "interlock/player/combine/voicelines/Suppressor/calloutentity_safeman_01.ogg")
Schema.voices.Add("Suppressor", "WALLHAMMER", "Wallhammer.", "interlock/player/combine/voicelines/Suppressor/calloutentity_wallhammer_01.ogg")

Schema.voices.Add("Suppressor", "ABOVE", "Above.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_above_01.ogg")
Schema.voices.Add("Suppressor", "APARTMENT", "Apartment.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_apartment_01.ogg")
Schema.voices.Add("Suppressor", "BARRELS", "Barrels.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_barrells_01.ogg")
Schema.voices.Add("Suppressor", "BEHIND", "Behind.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_behind_01.ogg")
Schema.voices.Add("Suppressor", "BELOW", "Below.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_below_01.ogg")
Schema.voices.Add("Suppressor", "BRICKS", "Bricks.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_bricks_01.ogg")
Schema.voices.Add("Suppressor", "RIGGS", "Riggs.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_bricks_01.ogg")
Schema.voices.Add("Suppressor", "BRIDGE", "Bridge.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_bridge_01.ogg")
Schema.voices.Add("Suppressor", "BUILDING", "Building.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_building_01.ogg")
Schema.voices.Add("Suppressor", "CAR", "Car.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_car_01.ogg")
Schema.voices.Add("Suppressor", "CRANE", "Crane.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_crane_01.ogg")
Schema.voices.Add("Suppressor", "DOOR", "Door.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_door_01.ogg")
Schema.voices.Add("Suppressor", "ELEVATOR", "Elevator.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_elevator_01.ogg")
Schema.voices.Add("Suppressor", "FRONT", "Front.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_front_01.ogg")
Schema.voices.Add("Suppressor", "HUT", "Hut.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_hut_01.ogg")
Schema.voices.Add("Suppressor", "PIPES", "Pipes.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_pipes_01.ogg")
Schema.voices.Add("Suppressor", "SHACK", "Shack.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_shack_01.ogg")
Schema.voices.Add("Suppressor", "TOILET", "Toilet.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_toilet_01.ogg")
Schema.voices.Add("Suppressor", "TRAINCAR", "Traincar.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_traincar_01.ogg")
Schema.voices.Add("Suppressor", "TRASH", "Trash.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_trash_01.ogg")
Schema.voices.Add("Suppressor", "TRUCK", "Truck.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_truck_01.ogg")
Schema.voices.Add("Suppressor", "TUNNEL", "Tunnel.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_tunnel_01.ogg")
Schema.voices.Add("Suppressor", "VAN", "Van.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_van_01.ogg")
Schema.voices.Add("Suppressor", "WHEELS", "Wheels.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_wheels_01.ogg")
Schema.voices.Add("Suppressor", "WOODPILE", "Woodpile.", "interlock/player/combine/voicelines/Suppressor/calloutlocation_woodpile_01.ogg")


Schema.voices.Add("Suppressor", "CLOSING", "Closing on leader. Initiate condition SHADOW.", "interlock/player/combine/voicelines/Suppressor/choreo_22_2000.ogg")


Schema.voices.Add("Suppressor", "OW ACTIVE HOSTILES", "Overwatch, we have active hostiles. Advise preparations.", "interlock/player/combine/voicelines/Suppressor/combat_idle_012.ogg")
Schema.voices.Add("Suppressor", "TARGET ACTIVE", "Negative, target is still active.", "interlock/player/combine/voicelines/Suppressor/combat_idle_020.ogg")
Schema.voices.Add("Suppressor", "CON ALPHA", "Copy that. Forming condition ALPHA.", "interlock/player/combine/voicelines/Suppressor/combat_idle_030.ogg")
Schema.voices.Add("Suppressor", "CON ALPHA2", "Copy that. Forming condition ALPHA at GRID-NINER-DASH-THREE-SEVEN.", "interlock/player/combine/voicelines/Suppressor/combat_idle_031.ogg")
Schema.voices.Add("Suppressor", "HOLDING FOR", "Holding for advanced directive, over.", "interlock/player/combine/voicelines/Suppressor/combat_idle_040.ogg")
Schema.voices.Add("Suppressor", "RECALIBRATING", "Confirmed, recalibrating.", "interlock/player/combine/voicelines/Suppressor/combat_idle_050.ogg")
Schema.voices.Add("Suppressor", "SETTING UP", "Copy, setting up position.", "interlock/player/combine/voicelines/Suppressor/combat_idle_060.ogg")
Schema.voices.Add("Suppressor", "STILL ACTIVE", "They're still alive.", "interlock/player/combine/voicelines/Suppressor/combat_idle_070.ogg")
Schema.voices.Add("Suppressor", "CC UNDERWAY", "Copy that, contain and control is underway.", "interlock/player/combine/voicelines/Suppressor/combat_idle_080.ogg")
Schema.voices.Add("Suppressor", "RESOLVING", "Resolving", "interlock/player/combine/voicelines/Suppressor/combat_idle_090.ogg")
Schema.voices.Add("Suppressor", "LOCKED AND READY", "10-4, negative on dagger renew - locked and ready.", "interlock/player/combine/voicelines/Suppressor/combat_idle_100.ogg")
Schema.voices.Add("Suppressor", "TAC ADV", "Forming tactical advantage.", "interlock/player/combine/voicelines/Suppressor/combat_idle_110.ogg")
Schema.voices.Add("Suppressor", "STILL HOLDING", "Still holding.", "interlock/player/combine/voicelines/Suppressor/combat_idle_120.ogg")
Schema.voices.Add("Suppressor", "STILL HOLDING2", "Still holding.", "interlock/player/combine/voicelines/Suppressor/combat_idle_121.ogg")
Schema.voices.Add("Suppressor", "HOLDING BIODAT", "Holding for biodat upload.", "interlock/player/combine/voicelines/Suppressor/combat_idle_130.ogg")
Schema.voices.Add("Suppressor", "PREPARING SUNDOWN", "Preparing for sundown.", "interlock/player/combine/voicelines/Suppressor/combat_idle_141.ogg")
Schema.voices.Add("Suppressor", "PREPARE COMMS", "Preparing comms for extended conflict.", "interlock/player/combine/voicelines/Suppressor/combat_idle_150.ogg")
Schema.voices.Add("Suppressor", "NO DAGGERS", "Negative, no daggers needed.", "interlock/player/combine/voicelines/Suppressor/combat_idle_160.ogg")
Schema.voices.Add("Suppressor", "EXTENDING", "Extending conflict duration.", "interlock/player/combine/voicelines/Suppressor/combat_idle_170.ogg")
Schema.voices.Add("Suppressor", "SCANNING BIODATS", "Scanning hostile biodats.", "interlock/player/combine/voicelines/Suppressor/combat_idle_180.ogg")
Schema.voices.Add("Suppressor", "DISREGARDING", "Disregarding last call.", "interlock/player/combine/voicelines/Suppressor/combat_idle_190.ogg")
Schema.voices.Add("Suppressor", "OW 10-9", "Overwatch, ten-niner.", "interlock/player/combine/voicelines/Suppressor/combat_idle_200.ogg")


Schema.voices.Add("Suppressor", "COVER", "Cover me!", "interlock/player/combine/voicelines/Officer/coverme_01.ogg")
Schema.voices.Add("Suppressor", "COVER2", "Cover!", "interlock/player/combine/voicelines/Officer/coverme_02.ogg")
Schema.voices.Add("Suppressor", "COVER3", "Cover on APF!", "interlock/player/combine/voicelines/Officer/coverme_03.ogg")
Schema.voices.Add("Suppressor", "COVER4", "Need covering fire!", "interlock/player/combine/voicelines/Officer/coverme_04.ogg")
Schema.voices.Add("Suppressor", "COVER5", "Requesting cover at APF!", "interlock/player/combine/voicelines/Officer/coverme_05.ogg")
Schema.voices.Add("Suppressor", "COVER AT", "Cover at...", "interlock/player/combine/voicelines/Officer/coverme_07.ogg")


Schema.voices.Add("Suppressor", "GRENADE3", "Evade!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_01.ogg")
Schema.voices.Add("Suppressor", "GRENADE2", "Grenade!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_02.ogg")
Schema.voices.Add("Suppressor", "TAKE COVER", "Take cover!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_03.ogg")
Schema.voices.Add("Suppressor", "GRENADE4", "Live grenade.", "interlock/player/combine/voicelines/Suppressor/danger_grenade_04.ogg")
Schema.voices.Add("Suppressor", "GRENADE5", "Bouncer, bouncer!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_05.ogg")
Schema.voices.Add("Suppressor", "GRENADE6", "Grenade, move!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_06.ogg")
Schema.voices.Add("Suppressor", "WATCH OUT", "Watch out!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_08.ogg")
Schema.voices.Add("Suppressor", "GET BACK", "Get back!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_09.ogg")
Schema.voices.Add("Suppressor", "GRENADE7", "Live bouncer, get back!", "interlock/player/combine/voicelines/Suppressor/danger_grenade_10.ogg")


Schema.voices.Add("Suppressor", "LOF1", "APF, closing.", "interlock/player/combine/voicelines/Suppressor/establishinglof_01.ogg")
Schema.voices.Add("Suppressor", "LOF2", "Switching position.", "interlock/player/combine/voicelines/Suppressor/establishinglof_02.ogg")
Schema.voices.Add("Suppressor", "LOF3", "Fixing viscon.", "interlock/player/combine/voicelines/Suppressor/establishinglof_03.ogg")
Schema.voices.Add("Suppressor", "LOF4", "Holding sightlines.", "interlock/player/combine/voicelines/Suppressor/establishinglof_04.ogg")
Schema.voices.Add("Suppressor", "LOF5", "Realigning to hostile.", "interlock/player/combine/voicelines/Suppressor/establishinglof_05.ogg")
Schema.voices.Add("Suppressor", "LOF6", "Target visual confirmation.", "interlock/player/combine/voicelines/Suppressor/establishinglof_06.ogg")
Schema.voices.Add("Suppressor", "NO VISUAL", "No visual on target. Moving!", "interlock/player/combine/voicelines/Suppressor/establishinglof_08.ogg")
Schema.voices.Add("Suppressor", "LOF8", "Realigning target delta.", "interlock/player/combine/voicelines/Suppressor/establishinglof_09.ogg")
Schema.voices.Add("Suppressor", "STAY THERE", "Stay there!", "interlock/player/combine/voicelines/Suppressor/establishinglof_10.ogg")
Schema.voices.Add("Suppressor", "CHANGING POS1", "Changing position.", "interlock/player/combine/voicelines/Suppressor/establishinglof_11.ogg")
Schema.voices.Add("Suppressor", "CHANGING POS2", "Optimizing location.", "interlock/player/combine/voicelines/Suppressor/establishinglof_12.ogg")
Schema.voices.Add("Suppressor", "CHANGING POS3", "Amending sightlines.", "interlock/player/combine/voicelines/Suppressor/establishinglof_13.ogg")
Schema.voices.Add("Suppressor", "CHANGING POS4", "Problem visual, moving.", "interlock/player/combine/voicelines/Suppressor/establishinglof_14.ogg")
Schema.voices.Add("Suppressor", "CHANGING POS5", "Clearing sightlines.", "interlock/player/combine/voicelines/Suppressor/establishinglof_15.ogg")
Schema.voices.Add("Suppressor", "CONTACT IN", "Contact in three...", "interlock/player/combine/voicelines/Suppressor/establishinglof_17.ogg")
Schema.voices.Add("Suppressor", "EXPOSING", "Exposing primary.", "interlock/player/combine/voicelines/Suppressor/establishinglof_18.ogg")
Schema.voices.Add("Suppressor", "DONT MOVE", "Don't move.", "interlock/player/combine/voicelines/Suppressor/establishinglof_19.ogg")


Schema.voices.Add("Suppressor", "", "Alyx!", "interlock/player/combine/voicelines/Suppressor/fakeout_calltoalyx_01.ogg")
Schema.voices.Add("Suppressor", "", "Hey, Alyx!", "interlock/player/combine/voicelines/Suppressor/fakeout_calltoalyx_02.ogg")
Schema.voices.Add("Suppressor", "", "Hey Alyx, it's us!", "interlock/player/combine/voicelines/Suppressor/fakeout_calltoalyx_03.ogg")
Schema.voices.Add("Suppressor", "", "Alyx, you there?", "interlock/player/combine/voicelines/Suppressor/fakeout_calltoalyx_04.ogg")
Schema.voices.Add("Suppressor", "", "Alyx!", "interlock/player/combine/voicelines/Suppressor/fakeout_calltoalyx_05.ogg")


Schema.voices.Add("Suppressor", "TARGET FRIENDLY", "Cease fire, target is friendly.", "interlock/player/combine/voicelines/Suppressor/fakeout_responseceasefire_01.ogg")
Schema.voices.Add("Suppressor", "STANDING DOWN", "Weapons down! Apf, weapons down!", "interlock/player/combine/voicelines/Suppressor/fakeout_responseceasefire_02.ogg")
Schema.voices.Add("Suppressor", "CEASE FIRE", "Cease fire! Cease fire!", "interlock/player/combine/voicelines/Suppressor/fakeout_responseceasefire_03.ogg")
Schema.voices.Add("Suppressor", "", "Alyx is friendly.", "interlock/player/combine/voicelines/Suppressor/fakeout_responseceasefire_04.ogg")
Schema.voices.Add("Suppressor", "", "Stop fire! Alyx is friendly!", "interlock/player/combine/voicelines/Suppressor/fakeout_responseceasefire_05.ogg")


Schema.voices.Add("Suppressor", "HAHA", "Haha.", "interlock/player/combine/voicelines/Suppressor/fakeout_success_01.ogg")
Schema.voices.Add("Suppressor", "FRIEND GAME", "Friend game effective.", "interlock/player/combine/voicelines/Suppressor/fakeout_success_02.ogg")
Schema.voices.Add("Suppressor", "HOSTILE SCRAMBLED", "Hahaha... hostile is scrambled.", "interlock/player/combine/voicelines/Suppressor/fakeout_success_03.ogg")


Schema.voices.Add("Suppressor", "FIRING", "Firing.", "interlock/player/combine/voicelines/Suppressor/firing_01.ogg")
Schema.voices.Add("Suppressor", "FIRING2", "Engaging target.", "interlock/player/combine/voicelines/Suppressor/firing_02.ogg")
Schema.voices.Add("Suppressor", "WEAPONS FREE4", "Weapons free.", "interlock/player/combine/voicelines/Suppressor/firing_04.ogg")
Schema.voices.Add("Suppressor", "FIRING4", "APF at primary setpoint.", "interlock/player/combine/voicelines/Suppressor/firing_05.ogg")
Schema.voices.Add("Suppressor", "WEAPONS FREE5", "Open fire, weapons free.", "interlock/player/combine/voicelines/Suppressor/firing_06.ogg")
Schema.voices.Add("Suppressor", "WEAPONS FREE6", "Code Three, maintaining cleanup.", "interlock/player/combine/voicelines/Suppressor/firing_07.ogg")
Schema.voices.Add("Suppressor", "FIRING5", "Cleaning sector.", "interlock/player/combine/voicelines/Suppressor/firing_08.ogg")
Schema.voices.Add("Suppressor", "FIRING6", "Daggers commit on hostile.", "interlock/player/combine/voicelines/Suppressor/firing_09.ogg")
Schema.voices.Add("Suppressor", "PROSECUTING", "Prosecuting.", "interlock/player/combine/voicelines/Suppressor/firing_10.ogg")
Schema.voices.Add("Suppressor", "FIRING7", "Engaged and firing.", "interlock/player/combine/voicelines/Suppressor/firing_110.ogg")
Schema.voices.Add("Suppressor", "FIRING8", "Enforcing stability on primary target in sector.", "interlock/player/combine/voicelines/Suppressor/firing_120.ogg")
Schema.voices.Add("Suppressor", "FIRING9", "Target is in line.", "interlock/player/combine/voicelines/Suppressor/firing_130.ogg")
Schema.voices.Add("Suppressor", "FIRING10", "Target is in line and receiving spikes.", "interlock/player/combine/voicelines/Suppressor/firing_131.ogg")
Schema.voices.Add("Suppressor", "ESCALATING", "Escalating force on primary target.", "interlock/player/combine/voicelines/Suppressor/firing_140.ogg")
Schema.voices.Add("Suppressor", "GOING DOWN3", "They're going down.", "interlock/player/combine/voicelines/Suppressor/firing_150.ogg")
Schema.voices.Add("Suppressor", "GOING DOWN2", "They're going down.", "interlock/player/combine/voicelines/Suppressor/firing_151.ogg")
Schema.voices.Add("Suppressor", "GOING DOWN", "They're going down!", "interlock/player/combine/voicelines/Suppressor/firing_152.ogg")
Schema.voices.Add("Suppressor", "ALMOST OVER2", "Almost over.", "interlock/player/combine/voicelines/Suppressor/firing_160.ogg")
Schema.voices.Add("Suppressor", "ALMOST OVER", "It's almost over!", "interlock/player/combine/voicelines/Suppressor/firing_161.ogg")
Schema.voices.Add("Suppressor", "ALMOST OVER3", "It's almost over.", "interlock/player/combine/voicelines/Suppressor/firing_162.ogg")
Schema.voices.Add("Suppressor", "SENDING SPIKES", "Sending spikes.", "interlock/player/combine/voicelines/Suppressor/firing_170.ogg")
Schema.voices.Add("Suppressor", "SENDING SPIKES2", "Sending all spikes to primary target.", "interlock/player/combine/voicelines/Suppressor/firing_180.ogg")
Schema.voices.Add("Suppressor", "SENDING SPIKES3", "Sending all spikes.", "interlock/player/combine/voicelines/Suppressor/firing_190.ogg")
Schema.voices.Add("Suppressor", "DONT RESIST", "Don't resist.", "interlock/player/combine/voicelines/Suppressor/firing_200.ogg")
Schema.voices.Add("Suppressor", "WH ENGAGED", "Wallhammer, is engaged and firing.", "interlock/player/combine/voicelines/Suppressor/firing_210.ogg")
Schema.voices.Add("Suppressor", "ORDINAL FIRING", "Ordinal is engaged and firing.", "interlock/player/combine/voicelines/Suppressor/firing_220.ogg")
Schema.voices.Add("Suppressor", "APF FIRING", "APF is engaged and firing.", "interlock/player/combine/voicelines/Suppressor/firing_230.ogg")


Schema.voices.Add("Suppressor", "TARGET FIRE", "Open fire, priority one.", "interlock/player/combine/voicelines/Suppressor/firing_player_01.ogg")
Schema.voices.Add("Suppressor", "ORDINAL FIRE AT", "Ordinal, open fire at...", "interlock/player/combine/voicelines/Suppressor/firing_player_04.ogg")
Schema.voices.Add("Suppressor", "ANTICITIZEN ONE", "Anti-citizen One confirmed, firing.", "interlock/player/combine/voicelines/Suppressor/firing_player_08.ogg")


Schema.voices.Add("Suppressor", "FLUSHING", "Clearing.", "interlock/player/combine/voicelines/Suppressor/flushing_01.ogg")
Schema.voices.Add("Suppressor", "FLUSHING2", "Distribution on three...", "interlock/player/combine/voicelines/Suppressor/flushing_02.ogg")
Schema.voices.Add("Suppressor", "FLUSHING3", "Flushing sectors.", "interlock/player/combine/voicelines/Suppressor/flushing_03.ogg")
Schema.voices.Add("Suppressor", "FLUSHING4", "Applying pressure. Flare down.", "interlock/player/combine/voicelines/Suppressor/flushing_05.ogg")
Schema.voices.Add("Suppressor", "FLUSHING5", "Flushing hostile.", "interlock/player/combine/voicelines/Suppressor/flushing_06.ogg")
Schema.voices.Add("Suppressor", "FLUSHING6", "Bouncer on last known.", "interlock/player/combine/voicelines/Suppressor/flushing_07.ogg")


Schema.voices.Add("Suppressor", "EXPOSING", "Exposing.", "interlock/player/combine/voicelines/Suppressor/getback_01.ogg")
Schema.voices.Add("Suppressor", "TAKE COVER", "Take cover!", "interlock/player/combine/voicelines/Suppressor/getback_02.ogg")
Schema.voices.Add("Suppressor", "WATCH OUT", "Watch out!", "interlock/player/combine/voicelines/Suppressor/getback_03.ogg")
Schema.voices.Add("Suppressor", "BOUNCER", "Bouncer, bouncer!", "interlock/player/combine/voicelines/Suppressor/getback_04.ogg")
Schema.voices.Add("Suppressor", "GET DOWN", "Get down!", "interlock/player/combine/voicelines/Suppressor/getback_05.ogg")


Schema.voices.Add("Suppressor", "HEAR", "Audible, in sector.", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_01.ogg")
Schema.voices.Add("Suppressor", "HEAR2", "Possible contaminant.", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_02.ogg")
Schema.voices.Add("Suppressor", "HEAR3", "Possible hostile active.", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_03.ogg")
Schema.voices.Add("Suppressor", "MOVEMENT AT", "Movement at...", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_04.ogg")
Schema.voices.Add("Suppressor", "SOUND ON", "Sound on.", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_05.ogg")
Schema.voices.Add("Suppressor", "SOUND ON2", "APF sound on, reporting all contaminants.", "interlock/player/combine/voicelines/Suppressor/hear_suspicious_06.ogg")


Schema.voices.Add("Suppressor", "IDLE1", "Nothing to report.", "interlock/player/combine/voicelines/Suppressor/idle_01.ogg")
Schema.voices.Add("Suppressor", "IDLE2", "Fourteen, eleven, one, fourteen, six, check. Your turn, over.", "interlock/player/combine/voicelines/Suppressor/idle_02.ogg")
Schema.voices.Add("Suppressor", "COPY THAT3", "Copy that.", "interlock/player/combine/voicelines/Suppressor/idle_03.ogg")
Schema.voices.Add("Suppressor", "IDLE3", "Negative movement. Grid SEVEN-DASH-TWO.", "interlock/player/combine/voicelines/Suppressor/idle_04.ogg")
Schema.voices.Add("Suppressor", "RADIALS CLEAR", "Radials clear, over.", "interlock/player/combine/voicelines/Suppressor/idle_06.ogg")
Schema.voices.Add("Suppressor", "HOLDING TRANSMISSION", "Overwatch, holding for transmission.", "interlock/player/combine/voicelines/Suppressor/idle_07.ogg")
Schema.voices.Add("Suppressor", "HOLDING TRANSMISSION2", "Still holding for transmission, over.", "interlock/player/combine/voicelines/Suppressor/idle_08.ogg")
Schema.voices.Add("Suppressor", "SECTOR LOCKDOWN", "Overwatch is confirming sector lockdown. Keep sightlines open, and sound on.", "interlock/player/combine/voicelines/Suppressor/idle_09.ogg")
Schema.voices.Add("Suppressor", "IDLE4", "Outbreak status is code DELTA-SEVEN. Team SUNDOWN is on contact overrun. Copy that.", "interlock/player/combine/voicelines/Suppressor/idle_10.ogg")
Schema.voices.Add("Suppressor", "IDLE5", "Negative... waiting for secondary parameter codes.", "interlock/player/combine/voicelines/Suppressor/idle_11.ogg")
Schema.voices.Add("Suppressor", "UPDATING BIODAT", "Updating biodat... Audibles: Three. Lifevis: Fifteen. Over.", "interlock/player/combine/voicelines/Suppressor/idle_12.ogg")
Schema.voices.Add("Suppressor", "IDLE6", "Roger that. Waiting for contact. Over.", "interlock/player/combine/voicelines/Suppressor/idle_13.ogg")
Schema.voices.Add("Suppressor", "VIROMES", "Viromes inbound. All units advisory, prepare for contact.", "interlock/player/combine/voicelines/Suppressor/idle_14.ogg")
Schema.voices.Add("Suppressor", "IDLE7", "Callout code: TWO-NINER-ZERO... confirmed.", "interlock/player/combine/voicelines/Suppressor/idle_15.ogg")
Schema.voices.Add("Suppressor", "STILL HERE", "Roger that. Still here.", "interlock/player/combine/voicelines/Suppressor/idle_16.ogg")
Schema.voices.Add("Suppressor", "COPY THAT2", "Copy that.", "interlock/player/combine/voicelines/Suppressor/idle_17.ogg")
Schema.voices.Add("Suppressor", "ACCEPT DISSONANCE UPDATE", "Copy, accepted. Update complete in t-minus three seconds. Dissonance resolved.", "interlock/player/combine/voicelines/Suppressor/idle_18.ogg")
Schema.voices.Add("Suppressor", "DISSONANCE UPDATE", "Update is live, acceptance is mandatory.", "interlock/player/combine/voicelines/Suppressor/idle_19.ogg")
Schema.voices.Add("Suppressor", "IDLE8", "Stablization team holding position. Stay alert.", "interlock/player/combine/voicelines/Suppressor/idle_20.ogg")


Schema.voices.Add("Suppressor", "INJURED", "Requesting stimdose.", "interlock/player/combine/voicelines/Suppressor/injured_01.ogg")
Schema.voices.Add("Suppressor", "INJURED2", "I'm hit.", "interlock/player/combine/voicelines/Suppressor/injured_02.ogg")
Schema.voices.Add("Suppressor", "INJURED3", "Taking damage.", "interlock/player/combine/voicelines/Suppressor/injured_03.ogg")
Schema.voices.Add("Suppressor", "INJURED4", "Soikes effective, applying stimdose.", "interlock/player/combine/voicelines/Suppressor/injured_06.ogg")


Schema.voices.Add("Suppressor", "HAHA2", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_01.ogg")
Schema.voices.Add("Suppressor", "HAHA3", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_02.ogg")
Schema.voices.Add("Suppressor", "HAHA4", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_03.ogg")
Schema.voices.Add("Suppressor", "HAHA5", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_04.ogg")
Schema.voices.Add("Suppressor", "HAHA6", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_05.ogg")
Schema.voices.Add("Suppressor", "HAHA7", "Haha.", "interlock/player/combine/voicelines/Suppressor/laugh_06.ogg")


Schema.voices.Add("Suppressor", "LOST ENEMY", "Contaminant not visible.", "interlock/player/combine/voicelines/Suppressor/lostenemy_01.ogg")
Schema.voices.Add("Suppressor", "REQUESTING LOCATION", "Requesting location.", "interlock/player/combine/voicelines/Suppressor/lostenemy_03.ogg")
Schema.voices.Add("Suppressor", "LOST ENEMY2", "Target lost.", "interlock/player/combine/voicelines/Suppressor/lostenemy_04.ogg")
Schema.voices.Add("Suppressor", "LOST ENEMY3", "Location assist for APF.", "interlock/player/combine/voicelines/Suppressor/lostenemy_05.ogg")
Schema.voices.Add("Suppressor", "LOST ENEMY4", "Negative visual on hostile.", "interlock/player/combine/voicelines/Suppressor/lostenemy_06.ogg")
Schema.voices.Add("Suppressor", "LOST ENEMY5", "Lost sight of contaminant.", "interlock/player/combine/voicelines/Suppressor/lostenemy_07.ogg")
Schema.voices.Add("Suppressor", "LOST ENEMY6", "No viscon, no viscon.", "interlock/player/combine/voicelines/Suppressor/lostenemy_08.ogg")


Schema.voices.Add("Suppressor", "LOST VISUAL", "Missing hostile, sector unknown.", "interlock/player/combine/voicelines/Suppressor/lostvisual_01.ogg")
Schema.voices.Add("Suppressor", "LOST VISUAL2", "APF requesting target location.", "interlock/player/combine/voicelines/Suppressor/lostvisual_02.ogg")
Schema.voices.Add("Suppressor", "REQUESTING LOCATION2", "Requesting location.", "interlock/player/combine/voicelines/Suppressor/lostvisual_03.ogg")
Schema.voices.Add("Suppressor", "LOST VISUAL3", "Lost sight of hostile.", "interlock/player/combine/voicelines/Suppressor/lostvisual_04.ogg")
Schema.voices.Add("Suppressor", "LOST VISUAL4", "Need location assistance in sector.", "interlock/player/combine/voicelines/Suppressor/lostvisual_07.ogg")
Schema.voices.Add("Suppressor", "NO VISUAL", "No visual. Ordinal - assist.", "interlock/player/combine/voicelines/Suppressor/lostvisual_08.ogg")
Schema.voices.Add("Suppressor", "LOST VISUAL5", "APF, negative on visual.", "interlock/player/combine/voicelines/Suppressor/lostvisual_09.ogg")
Schema.voices.Add("Suppressor", "LOST VISUAL6", "Possible evasion, requesting sightlines.", "interlock/player/combine/voicelines/Suppressor/lostvisual_10.ogg")


Schema.voices.Add("Suppressor", "TARGET LOST", "Contaminant is quiet, requesting last known sector.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_01.ogg")
Schema.voices.Add("Suppressor", "VISUAL BLACKOUT", "We have total visual blackout.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_02.ogg")
Schema.voices.Add("Suppressor", "TARGET LOST2", "Hostile is quiet.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_03.ogg")
Schema.voices.Add("Suppressor", "TARGET LOST3", "Evasive contaminant - Ordinal, assist.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_04.ogg")
Schema.voices.Add("Suppressor", "CHECK COVER", "Check cover.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_05.ogg")
Schema.voices.Add("Suppressor", "CONTACT CHECK", "Contact check.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_06.ogg")
Schema.voices.Add("Suppressor", "VISUALS LOST", "All visuals lost - eyes on.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_07.ogg")
Schema.voices.Add("Suppressor", "TARGET LOST4", "All contact quiet. Requesting recon.", "interlock/player/combine/voicelines/Suppressor/lostvisual_player_08.ogg")


Schema.voices.Add("Suppressor", "PROXIMITY", "Proximity!", "interlock/player/combine/voicelines/Suppressor/nearpanic_02.ogg")
Schema.voices.Add("Suppressor", "ASSIST", "Assist, assist, assist!", "interlock/player/combine/voicelines/Suppressor/nearpanic_04.ogg")


Schema.voices.Add("Suppressor", "COPY", "Copy.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_01.ogg")
Schema.voices.Add("Suppressor", "CAN DO", "APF can do.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_05.ogg")
Schema.voices.Add("Suppressor", "ROGER", "Roger.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_02.ogg")
Schema.voices.Add("Suppressor", "COPY THAT", "Copy that.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_03.ogg")
Schema.voices.Add("Suppressor", "POSITIVE", "Positive.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_04.ogg")
Schema.voices.Add("Suppressor", "PROCEEDING", "Proceeding.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_04.ogg")
Schema.voices.Add("Suppressor", "AFFIRMATIVE", "Affirmative.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_01.ogg")
Schema.voices.Add("Suppressor", "AFFIRMATIVE2", "Affirmative.", "interlock/player/combine/voicelines/Suppressor/orderresponse_positive_06.ogg")


Schema.voices.Add("Suppressor", "HOLDING", "Holding position.", "interlock/player/combine/voicelines/Suppressor/overwatch_01.ogg")
Schema.voices.Add("Suppressor", "LOCATION LOCKED", "Location locked.", "interlock/player/combine/voicelines/Suppressor/overwatch_02.ogg")
Schema.voices.Add("Suppressor", "WEAPONS READY", "Weapons ready.", "interlock/player/combine/voicelines/Suppressor/overwatch_03.ogg")
Schema.voices.Add("Suppressor", "VISCON LAST", "Viscon on last known position.", "interlock/player/combine/voicelines/Suppressor/overwatch_04.ogg")
Schema.voices.Add("Suppressor", "EYES LAST KNOWN", "Eyes on last known.", "interlock/player/combine/voicelines/Suppressor/overwatch_05.ogg")
Schema.voices.Add("Suppressor", "OBSERVING", "Observing.", "interlock/player/combine/voicelines/Suppressor/overwatch_06.ogg")
Schema.voices.Add("Suppressor", "IN POSITION", "APF, in position.", "interlock/player/combine/voicelines/Suppressor/overwatch_07.ogg")
Schema.voices.Add("Suppressor", "HOLDING2", "Holding focus.", "interlock/player/combine/voicelines/Suppressor/overwatch_08.ogg")
Schema.voices.Add("Suppressor", "STOP SOUND", "Stop sound, stop sound.", "interlock/player/combine/voicelines/Suppressor/overwatch_09.ogg")
Schema.voices.Add("Suppressor", "HOSTILE UNWILLING", "Hostile unwilling, stand by.", "interlock/player/combine/voicelines/Suppressor/overwatch_10.ogg")
Schema.voices.Add("Suppressor", "HOLD", "Hold.", "interlock/player/combine/voicelines/Suppressor/overwatch_11.ogg")
Schema.voices.Add("Suppressor", "WAITING CONTACT", "Waiting for contact.", "interlock/player/combine/voicelines/Suppressor/overwatch_12.ogg")
Schema.voices.Add("Suppressor", "EVALUATING", "Evaluating.", "interlock/player/combine/voicelines/Suppressor/overwatch_13.ogg")
Schema.voices.Add("Suppressor", "AWAITING", "Awaiting problem.", "interlock/player/combine/voicelines/Suppressor/overwatch_14.ogg")
Schema.voices.Add("Suppressor", "WAITING CONTAINMENT", "Waiting for containment.", "interlock/player/combine/voicelines/Suppressor/overwatch_15.ogg")
Schema.voices.Add("Suppressor", "HOLDING3", "APF holding.", "interlock/player/combine/voicelines/Suppressor/overwatch_16.ogg")
Schema.voices.Add("Suppressor", "EYES ON", "APF eyes on.", "interlock/player/combine/voicelines/Suppressor/overwatch_17.ogg")
Schema.voices.Add("Suppressor", "CONT LOCKED", "Contaminant is locked.", "interlock/player/combine/voicelines/Suppressor/overwatch_18.ogg")
Schema.voices.Add("Suppressor", "SECURING EDGE", "APF securing edges.", "interlock/player/combine/voicelines/Suppressor/overwatch_19.ogg")
Schema.voices.Add("Suppressor", "CHECKING EDGES", "Checking all edges.", "interlock/player/combine/voicelines/Suppressor/overwatch_20.ogg")


Schema.voices.Add("Suppressor", "TARGET HURT", "It's vulnerable.", "interlock/player/combine/voicelines/Suppressor/playerishurt_01.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT2", "Target at odds.", "interlock/player/combine/voicelines/Suppressor/playerishurt_02.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT3", "Target compromised.", "interlock/player/combine/voicelines/Suppressor/playerishurt_03.ogg")
Schema.voices.Add("Suppressor", "MOVE IN2", "Move in, move in!", "interlock/player/combine/voicelines/Suppressor/playerishurt_04.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT4", "Contaminant at low value.", "interlock/player/combine/voicelines/Suppressor/playerishurt_05.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT5", "Hostile is tagged.", "interlock/player/combine/voicelines/Suppressor/playerishurt_06.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT6", "Recall on hostile ASAP.", "interlock/player/combine/voicelines/Suppressor/playerishurt_07.ogg")
Schema.voices.Add("Suppressor", "AMPLIFY WEAPONS", "Amplify weapons on APF.", "interlock/player/combine/voicelines/Suppressor/playerishurt_08.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT7", "Red leak on hostile.", "interlock/player/combine/voicelines/Suppressor/playerishurt_09.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT8", "Possible tag on prime.", "interlock/player/combine/voicelines/Suppressor/playerishurt_10.ogg")
Schema.voices.Add("Suppressor", "TARGET HURT9", "APF effective.", "interlock/player/combine/voicelines/Suppressor/playerishurt_11.ogg")
Schema.voices.Add("Suppressor", "ENDING TARGET", "Ending target one.", "interlock/player/combine/voicelines/Suppressor/playerishurt_13.ogg")


Schema.voices.Add("Suppressor", "SEARCH FINISHED", "All sectors scanned.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_01.ogg")
Schema.voices.Add("Suppressor", "SEARCH FINISHED2", "Contact is silent.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_02.ogg")
Schema.voices.Add("Suppressor", "CLEAR2", "Sector clear. Requesting stand by.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_03.ogg")
Schema.voices.Add("Suppressor", "CLEAR", "Area clear.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_04.ogg")
Schema.voices.Add("Suppressor", "CLEAR3", "No contact.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_06.ogg")
Schema.voices.Add("Suppressor", "CLEAR4", "Arena secure.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_07.ogg")
Schema.voices.Add("Suppressor", "CLEAR5", "Looks clean.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_08.ogg")
Schema.voices.Add("Suppressor", "CONTACT LOST", "Contact lost, looks clear.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_09.ogg")
Schema.voices.Add("Suppressor", "NOTHING HERE", "Nothing here.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_10.ogg")
Schema.voices.Add("Suppressor", "STAYING SHARP", "Staying sharp, walls up.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_11.ogg")
Schema.voices.Add("Suppressor", "INEFFECTIVE CONTAMINANT", "Ineffective contaminant, requesting standdown.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_12.ogg")
Schema.voices.Add("Suppressor", "STANDBY BRAVO", "Standby for code bravo.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_13.ogg")
Schema.voices.Add("Suppressor", "NOTHING", "Nothing.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_14.ogg")
Schema.voices.Add("Suppressor", "CLEAR6", "Shadow clear.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_15.ogg")
Schema.voices.Add("Suppressor", "END SHADOW", "Request end on condition shadow.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_16.ogg")
Schema.voices.Add("Suppressor", "NOT HERE", "Not here.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_18.ogg")
Schema.voices.Add("Suppressor", "SEARCH FINISHED3", "Location clear. Recall assist.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_19.ogg")
Schema.voices.Add("Suppressor", "SEARCH FINISHED4", "All sectors clear. Recall.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_finish_20.ogg")


Schema.voices.Add("Suppressor", "SEARCHING", "Viscon processing", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_01.ogg")
Schema.voices.Add("Suppressor", "SEARCHING2", "Still searching.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_02.ogg")
Schema.voices.Add("Suppressor", "SEARCHING3", "Still sweeping.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_03.ogg")
Schema.voices.Add("Suppressor", "SHADOW ACTIVE", "Condition shadow active.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_06.ogg")
Schema.voices.Add("Suppressor", "SEARCHING4", "Recon in progress.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_07.ogg")
Schema.voices.Add("Suppressor", "TARGET SHADOW", "Target is still shadow.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_09.ogg")
Schema.voices.Add("Suppressor", "CLEAR MOVING", "Sector clear, advancing.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_10.ogg")
Schema.voices.Add("Suppressor", "CLEAR MOVING2", "Null sector, proceeding.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_11.ogg")
Schema.voices.Add("Suppressor", "CLEAR MOVING3", "Area cleaned, move in.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_12.ogg")
Schema.voices.Add("Suppressor", "SEARCHING5", "Eyes still active.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_13.ogg")
Schema.voices.Add("Suppressor", "NOTHING HERE2", "Nothing here.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_14.ogg")
Schema.voices.Add("Suppressor", "HOSTILE QUIET", "Hostile is still quiet.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_15.ogg")
Schema.voices.Add("Suppressor", "SCAN COMPLETE", "Scan complete. Resuming.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_16.ogg")
Schema.voices.Add("Suppressor", "STILL NO VISUAL", "Still no visual.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_17.ogg")
Schema.voices.Add("Suppressor", "RADIALS CLEAR", "Radials clear, resume.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_search_18.ogg")


Schema.voices.Add("Suppressor", "SEARCH START", "Spread it out.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_01.ogg")
Schema.voices.Add("Suppressor", "SEARCH START2", "Distributing.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_03.ogg")
Schema.voices.Add("Suppressor", "SEARCH START3", "APF out.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_04.ogg")
Schema.voices.Add("Suppressor", "SEARCH START4", "Deploying and scanning.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_06.ogg")
Schema.voices.Add("Suppressor", "CLEANUP COMMENCING", "Cleanup commencing", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_07.ogg")
Schema.voices.Add("Suppressor", "SWEEPING HOSTILES", "Sweeping for hostiles.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_09.ogg")
Schema.voices.Add("Suppressor", "SWEEPING CONTAMINANT", "Sweeping for contaminant.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_10.ogg")
Schema.voices.Add("Suppressor", "SEARCHING6", "Searching shadows", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_11.ogg")
Schema.voices.Add("Suppressor", "CLOSING ARENA", "Closing arena.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_12.ogg")
Schema.voices.Add("Suppressor", "CONTAINMENT PROCEEDING", "Containment proceeding.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_13.ogg")
Schema.voices.Add("Suppressor", "REPORTING SIGHTLINES", "Reporting all sightlines.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_14.ogg")
Schema.voices.Add("Suppressor", "FORM TARGET IN", "Formation on target in three...", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_15.ogg")
Schema.voices.Add("Suppressor", "PROCEED EXTRACTION", "Proceeding with hostile extraction.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_16.ogg")
Schema.voices.Add("Suppressor", "INITIATE SHADOW", "Initiate condition shadow.", "interlock/player/combine/voicelines/Suppressor/reconnoiter_start_17.ogg")


Schema.voices.Add("Suppressor", "GO SHARP", "Go sharp, target!", "interlock/player/combine/voicelines/Suppressor/refindenemy_01.ogg")
Schema.voices.Add("Suppressor", "CONTACT AT", "Target contact at...", "interlock/player/combine/voicelines/Suppressor/refindenemy_02.ogg")
Schema.voices.Add("Suppressor", "CONTACT", "Viscon, viscon!", "interlock/player/combine/voicelines/Suppressor/refindenemy_03.ogg")
Schema.voices.Add("Suppressor", "THERE", "There!", "interlock/player/combine/voicelines/Suppressor/refindenemy_04.ogg")
Schema.voices.Add("Suppressor", "CONTACT2", "Viscon, hostile found.", "interlock/player/combine/voicelines/Suppressor/refindenemy_05.ogg")
Schema.voices.Add("Suppressor", "OVER THERE", "Over there!", "interlock/player/combine/voicelines/Suppressor/refindenemy_06.ogg")
Schema.voices.Add("Suppressor", "MOVEMENT", "Movement.", "interlock/player/combine/voicelines/Suppressor/refindenemy_07.ogg")
Schema.voices.Add("Suppressor", "REFIND", "Animal is in the pit.", "interlock/player/combine/voicelines/Suppressor/refindenemy_08.ogg")
Schema.voices.Add("Suppressor", "CONTACT3", "Hostile contact!", "interlock/player/combine/voicelines/Suppressor/refindenemy_09.ogg")
Schema.voices.Add("Suppressor", "GO", "Go go go!", "interlock/player/combine/voicelines/Suppressor/refindenemy_10.ogg")
Schema.voices.Add("Suppressor", "REFIND2", "APF contact, in sector!", "interlock/player/combine/voicelines/Suppressor/refindenemy_11.ogg")
Schema.voices.Add("Suppressor", "CONTACT5", "Hostile live, check radials.", "interlock/player/combine/voicelines/Suppressor/refindenemy_12.ogg")
Schema.voices.Add("Suppressor", "CONTACT6", "Sightline confirmed.", "interlock/player/combine/voicelines/Suppressor/refindenemy_13.ogg")
Schema.voices.Add("Suppressor", "CONTACT7", "Sightline confirmed on prime.", "interlock/player/combine/voicelines/Suppressor/refindenemy_14.ogg")
Schema.voices.Add("Suppressor", "INTERCEPTING", "APF intercepting.", "interlock/player/combine/voicelines/Suppressor/refindenemy_15.ogg")
Schema.voices.Add("Suppressor", "CONTACT CONFIRMED", "Location confirmed. Enforcing stability.", "interlock/player/combine/voicelines/Suppressor/refindenemy_16.ogg")
Schema.voices.Add("Suppressor", "VISCON IN 3", "Visual confirmation on three.", "interlock/player/combine/voicelines/Suppressor/refindenemy_17.ogg")
Schema.voices.Add("Suppressor", "ACTIVE VISUAL AT", "Active visual at...", "interlock/player/combine/voicelines/Suppressor/refindenemy_18.ogg")


Schema.voices.Add("Suppressor", "RELOADING", "Reloading.", "interlock/player/combine/voicelines/Suppressor/reload_01.ogg")
Schema.voices.Add("Suppressor", "RELOADING2", "Refill on APF.", "interlock/player/combine/voicelines/Suppressor/reload_02.ogg")
Schema.voices.Add("Suppressor", "RELOADING3", "APF low - four... three... two... one!", "interlock/player/combine/voicelines/Suppressor/reload_03.ogg")
Schema.voices.Add("Suppressor", "RELOADING4", "Recharging!", "interlock/player/combine/voicelines/Suppressor/reload_05.ogg")
Schema.voices.Add("Suppressor", "RELOADING5", "Empty!", "interlock/player/combine/voicelines/Suppressor/reload_06.ogg")
Schema.voices.Add("Suppressor", "RELOADING6", "Empty dagger on APF!", "interlock/player/combine/voicelines/Suppressor/reload_07.ogg")
Schema.voices.Add("Suppressor", "RELOADING7", "Provisions low, reloading.", "interlock/player/combine/voicelines/Suppressor/reload_08.ogg")
Schema.voices.Add("Suppressor", "RELOADING8", "Renewing dagger!", "interlock/player/combine/voicelines/Suppressor/reload_09.ogg")


Schema.voices.Add("Suppressor", "RETREAT", "Ripcord!", "interlock/player/combine/voicelines/Suppressor/retreat_02.ogg")
Schema.voices.Add("Suppressor", "RETREAT2", "Ripcord on APF.", "interlock/player/combine/voicelines/Suppressor/retreat_03.ogg")
Schema.voices.Add("Suppressor", "RETREAT3", "Retreating!", "interlock/player/combine/voicelines/Suppressor/retreat_04.ogg")
Schema.voices.Add("Suppressor", "RETREAT4", "Falling back!", "interlock/player/combine/voicelines/Suppressor/retreat_05.ogg")
Schema.voices.Add("Suppressor", "RETREAT5", "Sector is too hot!", "interlock/player/combine/voicelines/Suppressor/retreat_06.ogg")
Schema.voices.Add("Suppressor", "RETREAT6", "Finding cover!", "interlock/player/combine/voicelines/Suppressor/retreat_07.ogg")
Schema.voices.Add("Suppressor", "RETREAT7", "APF, regrouping!", "interlock/player/combine/voicelines/Suppressor/retreat_08.ogg")
Schema.voices.Add("Suppressor", "RETREAT8", "Sector volatile. Finding shade.", "interlock/player/combine/voicelines/Suppressor/retreat_10.ogg")
Schema.voices.Add("Suppressor", "RETREAT9", "Ripcord, ripcord!", "interlock/player/combine/voicelines/Suppressor/retreat_02.ogg")


Schema.voices.Add("Suppressor", "MULTIPLE CONTACT", "Secondaries identified.", "interlock/player/combine/voicelines/Suppressor/sees_company_01.ogg")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT2", "Viscon on multiple unknowns.", "interlock/player/combine/voicelines/Suppressor/sees_company_02.ogg")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT3", "We have viscon on secondaries.", "interlock/player/combine/voicelines/Suppressor/sees_company_03.ogg")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT4", "Check silhouettes. Possible multipliers.", "interlock/player/combine/voicelines/Suppressor/sees_company_04.ogg")
Schema.voices.Add("Suppressor", "MULTIPLE CONTACT5", "We have multiple contaminants.", "interlock/player/combine/voicelines/Suppressor/sees_company_05.ogg")


Schema.voices.Add("Suppressor", "TARGET GRENADES", "Target-One has bouncers.", "interlock/player/combine/voicelines/Suppressor/sees_grenades_01.ogg")
Schema.voices.Add("Suppressor", "TARGET GRENADES2", "Hostile has bouncers. Be alert.", "interlock/player/combine/voicelines/Suppressor/sees_grenades_02.ogg")
Schema.voices.Add("Suppressor", "TARGET GRENADES3", "Contaminant has grenades. Disperse.", "interlock/player/combine/voicelines/Suppressor/sees_grenades_03.ogg")


Schema.voices.Add("Suppressor", "TARGET RELOADING", "Hostile reloading, dagger advantage.", "interlock/player/combine/voicelines/Suppressor/sees_reloading_01.ogg")
Schema.voices.Add("Suppressor", "TARGET RELOADING2", "Advantage now!", "interlock/player/combine/voicelines/Suppressor/sees_reloading_03.ogg")
Schema.voices.Add("Suppressor", "TARGET RELOADING3", "APF - contaminant is vulnerable!", "interlock/player/combine/voicelines/Suppressor/sees_reloading_04.ogg")
Schema.voices.Add("Suppressor", "", "Alyx reloading, full response active.", "interlock/player/combine/voicelines/Suppressor/sees_reloading_05.ogg")


Schema.voices.Add("Suppressor", "TARGET UPGRADES", "Spikes boosted on target one.", "interlock/player/combine/voicelines/Suppressor/sees_upgrades_01.ogg")
Schema.voices.Add("Suppressor", "TARGET UPGRADES2", "Overwatch, target one has boosters.", "interlock/player/combine/voicelines/Suppressor/sees_upgrades_02.ogg")
Schema.voices.Add("Suppressor", "TARGET UPGRADES3", "Ordinal, spikes are boosted.", "interlock/player/combine/voicelines/Suppressor/sees_upgrades_03.ogg")
Schema.voices.Add("Suppressor", "TARGET UPGRADES4", "APF - target has illegal spikes.", "interlock/player/combine/voicelines/Suppressor/sees_upgrades_04.ogg")
Schema.voices.Add("Suppressor", "TARGET UPGRADES5", "Boosters active on prime, respond with caution.", "interlock/player/combine/voicelines/Suppressor/sees_upgrades_05.ogg")


Schema.voices.Add("Suppressor", "MANDOWN", "Overwatch, request reserve action.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_01.ogg")
Schema.voices.Add("Suppressor", "MANDOWN2", "Overwatch, sector is not secure!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_02.ogg")
Schema.voices.Add("Suppressor", "MANDOWN3", "Sector niner, outbreak, outbreak, outbreak!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_03.ogg")
Schema.voices.Add("Suppressor", "MANDOWN4", "Overwatch, sector not controlled.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_05.ogg")
Schema.voices.Add("Suppressor", "MANDOWN5", "Overwatch, sector is overrun.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_06.ogg")
Schema.voices.Add("Suppressor", "MANDOWN6", "Overwatch, request SKYSHIELD!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_07.ogg")
Schema.voices.Add("Suppressor", "MANDOWN7", "Overwatch, recommend new formation.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_09.ogg")
Schema.voices.Add("Suppressor", "MANDOWN8", "Friendly is down!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_10.ogg")
Schema.voices.Add("Suppressor", "X IS QUIET", "...is quiet, requesting replacement", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_11.ogg")
Schema.voices.Add("Suppressor", "WE HAVE PROBLEM", "We have a problem.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_08.ogg")


Schema.voices.Add("Suppressor", "LAST UNIT", "Overwatch, APF reporting solo.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_01.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT2", "Overwatch, APF is last unit, requesting immediate assist.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_02.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT3", "Agh, requesting shadow!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_03.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT4", "Overwatch, outbreak is uncontained.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_04.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_05.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT5", "Overwatch, solo contact, excessive hostiles!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_06.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT6", "Survival mark deployed.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_07.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT7", "Overwatch, requesting extraction on APF.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_08.ogg")
Schema.voices.Add("Suppressor", "LAST UNIT8", "Overwatch, APF is last responder.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_lastman_09.ogg")


Schema.voices.Add("Suppressor", "LEADER DOWN", "Overwatch, Ordinal is down.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_01.ogg")
Schema.voices.Add("Suppressor", "LEADER DOWN2", "Ordinal is quiet, requesting assist!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_02.ogg")
Schema.voices.Add("Suppressor", "LEADER DOWN3", "Ordinal is condition SUNDOWN!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_03.ogg")
Schema.voices.Add("Suppressor", "", "", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_04.ogg")
Schema.voices.Add("Suppressor", "LEADER DOWN4", "Overwatch, Ordinal omitted, responding!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_05.ogg")
Schema.voices.Add("Suppressor", "LEADER DOWN5", "Ordinal is silent, administer full response.", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_06.ogg")
Schema.voices.Add("Suppressor", "LEADER DOWN6", "Ordinal is flatline, Ordinal is flatline!", "interlock/player/combine/voicelines/Suppressor/squadmemberlost_leader_07.ogg")


Schema.voices.Add("Suppressor", "SUPPRESSING", "Suppressing!", "interlock/player/combine/voicelines/Suppressor/suppressing_01.ogg")
Schema.voices.Add("Suppressor", "SUPPRESSING AT", "Suppressing at...", "interlock/player/combine/voicelines/Suppressor/suppressing_02.ogg")
Schema.voices.Add("Suppressor", "SUPPRESSING2", "APF forcing compliance!", "interlock/player/combine/voicelines/Suppressor/suppressing_03.ogg")
Schema.voices.Add("Suppressor", "SUPPRESSIN3", "Barrage on last known!", "interlock/player/combine/voicelines/Suppressor/suppressing_04.ogg")
Schema.voices.Add("Suppressor", "SUPPRESSING AT2", "Antibody-Protection-Force active on...", "interlock/player/combine/voicelines/Suppressor/suppressing_05.ogg")


Schema.voices.Add("Suppressor", "SPIKES CLOSE", "Spikes close, no damage.", "interlock/player/combine/voicelines/Suppressor/takingfire_01.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE2", "Missed.", "interlock/player/combine/voicelines/Suppressor/takingfire_02.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE3", "Target error, take advantage.", "interlock/player/combine/voicelines/Suppressor/takingfire_03.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE4", "APF - hostile is inaccurate!", "interlock/player/combine/voicelines/Suppressor/takingfire_04.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE5", "Almost.", "interlock/player/combine/voicelines/Suppressor/takingfire_05.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE6", "Missed again, taking advantage.", "interlock/player/combine/voicelines/Suppressor/takingfire_07.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE7", "Target has failed.", "interlock/player/combine/voicelines/Suppressor/takingfire_08.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE8", "Exercise advantage on hostile.", "interlock/player/combine/voicelines/Suppressor/takingfire_09.ogg")
Schema.voices.Add("Suppressor", "HOSTILE FAILED", "Hostile failed, reforming.", "interlock/player/combine/voicelines/Suppressor/takingfire_10.ogg")
Schema.voices.Add("Suppressor", "TAUNT", "Spikes ineffective. Target is unskilled.", "interlock/player/combine/voicelines/Suppressor/takingfire_11.ogg")


Schema.voices.Add("Suppressor", "TAUNT2", "Hostile is experiencing extreme panic.", "interlock/player/combine/voicelines/Suppressor/taunt_010.ogg")
Schema.voices.Add("Suppressor", "TAUNT3", "Hostile is overwhelmed.", "interlock/player/combine/voicelines/Suppressor/taunt_020.ogg")
Schema.voices.Add("Suppressor", "TAUNT4", "Target is at low motivation, take advantage.", "interlock/player/combine/voicelines/Suppressor/taunt_030.ogg")
Schema.voices.Add("Suppressor", "TAUNT5", "Target is at low motivation.", "interlock/player/combine/voicelines/Suppressor/taunt_031.ogg")
Schema.voices.Add("Suppressor", "YOU CAN COME OUT", "You can come out now!", "interlock/player/combine/voicelines/Suppressor/taunt_042.ogg")
Schema.voices.Add("Suppressor", "WE CAN HELP YOU2", "Attention hostile target, we can help you, it is safe.", "interlock/player/combine/voicelines/Suppressor/taunt_050.ogg")
Schema.voices.Add("Suppressor", "WE CAN HELP YOU", "We can help you, it is safe.", "interlock/player/combine/voicelines/Suppressor/taunt_051.ogg")
Schema.voices.Add("Suppressor", "TAUNT6", "Suspect is above legal aggression threshold. Taking advantage.", "interlock/player/combine/voicelines/Suppressor/taunt_060.ogg")
Schema.voices.Add("Suppressor", "ESCALATING2", "Proceeding with escalation.", "interlock/player/combine/voicelines/Suppressor/taunt_070.ogg")
Schema.voices.Add("Suppressor", "NON COMPLIANT", "Suspect is non-compliant with code 10-307.", "interlock/player/combine/voicelines/Suppressor/taunt_071.ogg")
Schema.voices.Add("Suppressor", "ESCALATING3", "Code 10-307, proceeding with escalation.", "interlock/player/combine/voicelines/Suppressor/taunt_072.ogg")
Schema.voices.Add("Suppressor", "TAUNT7", "Hostile is hesitating.", "interlock/player/combine/voicelines/Suppressor/taunt_081.ogg")
Schema.voices.Add("Suppressor", "TAUNT8", "Hostile attacks are ineffective, proceeding with containment.", "interlock/player/combine/voicelines/Suppressor/taunt_090.ogg")
Schema.voices.Add("Suppressor", "STANDING DOWN2", "Activating code 10-108, standing down.", "interlock/player/combine/voicelines/Suppressor/taunt_100.ogg")
Schema.voices.Add("Suppressor", "SUSPEND FIRE", "Suspend fire, target is friendly.", "interlock/player/combine/voicelines/Suppressor/taunt_111.ogg")
Schema.voices.Add("Suppressor", "STANDING DOWN3", "Standing down, code 10-40.", "interlock/player/combine/voicelines/Suppressor/taunt_120.ogg")
Schema.voices.Add("Suppressor", "CEASEFIRE ON TARGET", "Ceasing fire, target is non-hostile.", "interlock/player/combine/voicelines/Suppressor/taunt_131.ogg")
Schema.voices.Add("Suppressor", "DO NOT SHOOT", "Copy, do not shoot. Compliance confirmed.", "interlock/player/combine/voicelines/Suppressor/taunt_140.ogg")
Schema.voices.Add("Suppressor", "FRIENDLY2", "Target is friendly.", "interlock/player/combine/voicelines/Suppressor/taunt_150.ogg")
Schema.voices.Add("Suppressor", "FRIENDLY3", "Stand down, target is friendly.", "interlock/player/combine/voicelines/Suppressor/taunt_151.ogg")
Schema.voices.Add("Suppressor", "FRIENDLY4", "All units stand down, target is friendly.", "interlock/player/combine/voicelines/Suppressor/taunt_152.ogg")
Schema.voices.Add("Suppressor", "FRIENDLY5", "Friendly confirmed, cease fire.", "interlock/player/combine/voicelines/Suppressor/taunt_160.ogg")
Schema.voices.Add("Suppressor", "WAIT AND SEE2", "Overwatch, we have a wait and see at grid NINER-DASH-FIVE.", "interlock/player/combine/voicelines/Suppressor/taunt_170.ogg")
Schema.voices.Add("Suppressor", "WAIT AND SEE", "Overwatch, we have a wait and see.", "interlock/player/combine/voicelines/Suppressor/taunt_171.ogg")
Schema.voices.Add("Suppressor", "INJURED7", "Affirmative, target is low value.", "interlock/player/combine/voicelines/Suppressor/taunt_182.ogg")
Schema.voices.Add("Suppressor", "HOSTILE UNAWARE", "Copy that, hostile is unaware and ready for containment.", "interlock/player/combine/voicelines/Suppressor/taunt_191.ogg")
Schema.voices.Add("Suppressor", "INJURED8", "Hostile is showing fatigue. Prepare containment.", "interlock/player/combine/voicelines/Suppressor/taunt_200.ogg")


Schema.voices.Add("Suppressor", "NEGATIVE", "Negative.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_01.ogg")
Schema.voices.Add("Suppressor", "NEGATORY", "Negatory.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_05.ogg")
Schema.voices.Add("Suppressor", "NO", "No.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_04.ogg")
Schema.voices.Add("Suppressor", "CANT COMPLY", "Can't comply.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_02.ogg")
Schema.voices.Add("Suppressor", "DENIED", "Denied.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_06.ogg")
Schema.voices.Add("Suppressor", "NEGATIVE3", "Overwatch, negative", "interlock/player/combine/voicelines/Suppressor/unabletocommence_03.ogg")
Schema.voices.Add("Suppressor", "NEGATIVE2", "That's a negative.", "interlock/player/combine/voicelines/Suppressor/unabletocommence_07.ogg")


Schema.voices.Add("Suppressor", "UNDERFIRE", "Spikes confirmation, suppressing active.", "interlock/player/combine/voicelines/Suppressor/underattack_01.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE2", "Hostile is live.", "interlock/player/combine/voicelines/Suppressor/underattack_02.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE3", "Contact! Hostile at...", "interlock/player/combine/voicelines/Suppressor/underattack_03.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE4", "APF is ready to oppress.", "interlock/player/combine/voicelines/Suppressor/underattack_04.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE5", "We have live contaminants.", "interlock/player/combine/voicelines/Suppressor/underattack_05.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE6", "Distributing.", "interlock/player/combine/voicelines/Suppressor/underattack_06.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE7", "Target is hostile, daggers free.", "interlock/player/combine/voicelines/Suppressor/underattack_07.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE8", "Target oppressing!", "interlock/player/combine/voicelines/Suppressor/underattack_08.ogg")
Schema.voices.Add("Suppressor", "UNDERFIRE9", "Overwatch, we have spikes.", "interlock/player/combine/voicelines/Suppressor/underattack_09.ogg")
Schema.voices.Add("Suppressor", "CONDITION DELTA", "Preparing condition delta.", "interlock/player/combine/voicelines/Suppressor/underattack_10.ogg")
Schema.voices.Add("Suppressor", "TAKING FIRE", "Taking fire.", "interlock/player/combine/voicelines/Suppressor/underattack_11.ogg")
Schema.voices.Add("Suppressor", "EXECUTING RESPONSE", "Executing full response.", "interlock/player/combine/voicelines/Suppressor/underattack_12.ogg")


Schema.voices.Add("Suppressor", "CHATTER1", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/choreo_22_2004.ogg")
Schema.voices.Add("Suppressor", "CHATTER2", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_01.ogg")
Schema.voices.Add("Suppressor", "CHATTER3", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_02.ogg")
Schema.voices.Add("Suppressor", "CHATTER4", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_03.ogg")
Schema.voices.Add("Suppressor", "CHATTER5", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_04.ogg")
Schema.voices.Add("Suppressor", "CHATTER6", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_05.ogg")
Schema.voices.Add("Suppressor", "CHATTER7", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_06.ogg")
Schema.voices.Add("Suppressor", "CHATTER8", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_07.ogg")
Schema.voices.Add("Suppressor", "CHATTER9", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/Suppressor_radio_idle_08.ogg")
Schema.voices.Add("Suppressor", "CHATTER10", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/29_0010.ogg")
Schema.voices.Add("Suppressor", "CHATTER11", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/29_0011.ogg")
Schema.voices.Add("Suppressor", "CHATTER12", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/29_0012.ogg")
Schema.voices.Add("Suppressor", "CHATTER13", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/29_0013.ogg")
Schema.voices.Add("Suppressor", "CHATTER14", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/30_0019.ogg")
Schema.voices.Add("Suppressor", "CHATTER15", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/30_0021.ogg")
Schema.voices.Add("Suppressor", "CHATTER16", "**Indistinct Radio Chatter**", "interlock/player/combine/voicelines/Chatter/30_0022.ogg")

Schema.voices.AddClass("Suppressor", function(ply)
    return ( ply:Team() == FACTION_OTA ) and ( ply:GetModel():find("combine_suppresor") )
end)
